#!/usr/bin/perl

open OUT, "> localization.lua";
print OUT << 'EOD';
--[[
	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.

	Version: <%version%>
]]

EOD

for $file (<locales/*.utf8>) {
	$file =~ /locales.([^.]+).utf8/;
	$locale = $1;
	if ($locale ne "enEN") {
		push(@locales, $locale);
	}
}

print OUT "-- Default locale strings are defined in english,\n-- override them in the locale specific blocks\n";
open(DATA, "< locales/enEN.utf8");
while (<DATA>) {
	s/[\r\n]+//g;
	s/([\200-\377])/sprintf("\\%d",ord($1))/eg;
	if (/^(\w+)\s*=/) {
		$defined{$1} = 1;
	}
	print OUT "$_\n";
}
close DATA;

print OUT "\n";

for $locale (@locales) {
	%localized = ();
	print OUT "-- Locale strings for the $locale locale\n";
	print OUT "if GetLocale() == \"$locale\" then\n";
	open(DATA, "< locales/$locale.utf8");
	while (<DATA>) {
		s/[\r\n]+//g;
		s/([\200-\377])/sprintf("\\%d",ord($1))/eg;
		if (/^(\w+)\s*=/) {
			$localized{$1} = 1;
		}
		print OUT "\t$_\n";
	}
	close DATA;
	$missing = 0;
	for $defined (sort(keys(%defined))) {
		unless ($localized{$defined}) {
			unless ($missing) {
				print OUT "\n-- The following definitions are missing in this locale:\n";
				$missing = 1;
			}
			print OUT"--\t$defined = \"\";\n";
		}
	}
	
	print OUT "end\n\n";
}

