--[[
	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.


	$Id$
	Version: <%version%>
]]






-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================






_AUCT = {};

AUCT_VALID_LOCALES = {["daDK"] = true, ["deDE"] = true, ["enUS"] = true, ["esES"] = true, ["frFR"] = true};

function Auctioneer_SetLocaleStrings(locale)
-- Default locale strings are defined in English
	
	
	
	_AUCT['TimeShort'] = "Short";
	_AUCT['TimeMed'] = "Medium";
	_AUCT['TimeLong'] = "Long";
	_AUCT['TimeVlong'] = "Very Long";
	
	_AUCT['FrmtWelcome'] = "Auctioneer v%s loaded";
	
	_AUCT['FrmtBrokerHeader'] = "Minimum profit: %s, HSP = 'Highest Sellable Price'";
	_AUCT['FrmtBrokerLine'] = "%s, Last %s seen, HSP: %s, BO: %s, Prof: %s";
	_AUCT['FrmtBrokerDone'] = "Brokering done";
	_AUCT['FrmtBidbrokerHeader'] = "Minimum profit: %s, HSP = 'Highest Sellable Price'";
	_AUCT['FrmtBidbrokerMinbid'] = "minBid"
	_AUCT['FrmtBidbrokerCurbid'] = "curBid"
	_AUCT['FrmtBidbrokerLine'] = "%s, Last %s seen, HSP: %s, %s: %s, Prof: %s, Time: %s";
	_AUCT['FrmtBidbrokerDone'] = "Bid brokering done";
	_AUCT['FrmtPctlessHeader'] = "Percent Less than Highest Sellable Price (HSP): %d%%";
	_AUCT['FrmtPctlessLine'] = "%s, Last %d seen, HSP: %s, BO: %s, Prof: %s, Less %s";
	_AUCT['FrmtPctlessDone'] = "Percent less done.";
	_AUCT['FrmtCompeteHeader'] = "Competing auctions at least %s less per item.";
	_AUCT['FrmtCompeteLine'] = "%s, Bid: %s, BO %s vs %s, %s less";
	_AUCT['FrmtCompeteDone'] = "Competing auctions done.";
	_AUCT['FrmtNoauct'] = "No auctions found for the item: %s";
	_AUCT['FrmtMedianLine'] = "Of last %d seen, median BO for 1 %s is: %s";
	_AUCT['FrmtLowLine'] = "%s, BO: %s, Seller: %s, For one: %s, Less than median: %s";
	_AUCT['FrmtHspLine'] = "Highest Sellable Price for one %s is: %s";
	
	_AUCT['FrmtInfoSeen'] = "Seen %d times at auction total";
	_AUCT['FrmtInfoForone'] = "For 1: %s min/%s BO (%s bid) [in %d's]";
	_AUCT['FrmtInfoAverage'] = "%s min/%s BO (%s bid)"
	_AUCT['FrmtInfoHistmed'] = "Last %d, median BO (ea)";
	_AUCT['FrmtInfoSnapmed'] = "Scanned %d, median BO (ea)";
	_AUCT['FrmtInfoSgststx'] = "Suggested price for your %d stack: %s min/%s BO";
	_AUCT['FrmtInfoSgst'] = "Suggested price: %s min/%s BO";
	
	_AUCT['FrmtInfoBidrate'] = "%d%% have bid, %d%% have BO";
	_AUCT['FrmtInfoNever'] = "Never seen at %s";
	_AUCT['FrmtInfoAlsoseen'] = "Seen %d times at %s";
	
	_AUCT['FrmtInfoHeadMulti'] = "Averages for %d items:";
	_AUCT['FrmtInfoMinMulti'] = "  Starting bid (%s ea)";
	_AUCT['FrmtInfoBidMulti'] = "  Bidded (%s%s ea)";
	_AUCT['FrmtInfoBuyMulti'] = "  Buyout (%s%s ea)";
	
	_AUCT['FrmtInfoHeadOne'] = "Averages for this item:";
	_AUCT['FrmtInfoMinOne'] = "  Starting bid";
	_AUCT['FrmtInfoBidOne'] = "  Bidded%s";
	_AUCT['FrmtInfoBuyOne'] = "  Buyout%s";
	
	_AUCT['FrmtInfoBuymedian'] = "  Buyout median";
	
	_AUCT['FrmtInfoStacksize'] = "  Average stack size: %d items";
	
	_AUCT['FrmtUnknownLocale'] = "The locale you specified ('%s') is unknown. Valid locales are:";
	_AUCT['FrmtUnknownRf']     = "Invalid parameter ('%s'). The parameter must be formated like: [realm]-[faction]. For example: Al'Akir-Horde";
	_AUCT['FrmtUnknownArg']    = "'%s' is no valid argument for '%s'";
	
	_AUCT['FrmtActRemove'] = "Removing auction signature %s from current AH snapshot.";
	
	_AUCT['FrmtAuctinfoHist'] = "%d historical";
	_AUCT['FrmtAuctinfoSnap'] = "%d last scan";
	_AUCT['FrmtAuctinfoLow'] = "Snapshot low";
	_AUCT['FrmtAuctinfoNolow'] = "Item not seen last snapshot";
	_AUCT['FrmtAuctinfoOrig'] = "Original bid";
	_AUCT['FrmtAuctinfoSugbuy'] = "Suggested buyout";
	_AUCT['FrmtAuctinfoSugbid'] = "Suggested bid";
	_AUCT['FrmtAuctinfoMktprice'] = "Market price";
	
	_AUCT['FrmtWarnMarkup'] = "Marking up vendor by %s%%";
	_AUCT['FrmtWarnUndercut'] = "Undercutting by %s%%";
	_AUCT['FrmtWarnNocomp'] = "No competition";
	_AUCT['FrmtWarnAbovemkt'] = "Competiton above market";
	_AUCT['FrmtWarnToolow'] = "Cannot match lowest price";
	_AUCT['FrmtWarnMyprice'] = "Using my current price";
	_AUCT['FrmtWarnNodata'] = "No data for HSP";
	_AUCT['FrmtWarnUser'] = "Using user pricing";
	
	_AUCT['CmdOff'] = "off";
	_AUCT['CmdOn'] = "on";
	_AUCT['CmdAlt'] = "alt";
	_AUCT['CmdCtrl'] = "ctrl";
	_AUCT['CmdShift'] = "shift";
	_AUCT['CmdToggle'] = "toggle";
	_AUCT['CmdDisable'] = "disable";
	_AUCT['CmdClear'] = "clear";
	_AUCT['CmdClearAll'] = "all";
	_AUCT['CmdClearSnapshot'] = "snapshot";
	_AUCT['CmdAlso'] = "also";
	_AUCT['CmdAlsoOpposite'] = "opposite";
	_AUCT['CmdLocale'] = "locale";
	_AUCT['CmdDefault'] = "default";
	_AUCT['CmdPrintin'] = "print-in";
	_AUCT['CmdAuctionClick'] = "auction-click";
	
	_AUCT['CmdBroker'] = "broker";
	_AUCT['CmdBidbroker'] = "bidbroker";
	_AUCT['CmdBidbrokerShort'] = "bb";
	_AUCT['CmdEmbed'] = "embed";
	_AUCT['CmdPercentless'] = "percentless";
	_AUCT['CmdPercentlessShort'] = "pl";
	_AUCT['CmdCompete'] = "compete";
	_AUCT['CmdScan'] = "scan";
	_AUCT['CmdAutofill'] = "autofill";
	
	_AUCT['CmdProtectWindow'] = "protect-window"
	_AUCT['CmdProtectWindow0'] = "never"
	_AUCT['CmdProtectWindow1'] = "scan"
	_AUCT['CmdProtectWindow2'] = "always"
	_AUCT['CmdAuctionDuration'] = "auction-duration"
	_AUCT['CmdAuctionDuration0'] = "last"
	_AUCT['CmdAuctionDuration1'] = "2h"
	_AUCT['CmdAuctionDuration2'] = "8h"
	_AUCT['CmdAuctionDuration3'] = "24h"
	
	_AUCT['CmdPctBidmarkdown'] = "pct-bidmarkdown";
	_AUCT['CmdPctMarkup']      = "pct-markup";
	_AUCT['CmdPctMaxless']     = "pct-maxless";
	_AUCT['CmdPctNocomp']      = "pct-nocomp";
	_AUCT['CmdPctUnderlow']    = "pct-underlow";
	_AUCT['CmdPctUndermkt']    = "pct-undermkt";
	
	_AUCT['OptClear'] = "([Item]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
	_AUCT['OptAlso'] = "(realm-faction|".._AUCT['CmdAlsoOpposite']..")"
	_AUCT['OptLocale'] = "<locale>";
	_AUCT['OptBroker'] = "<silver_profit>";
	_AUCT['OptBidbroker'] = "<silver_profit>";
	_AUCT['OptPercentless'] = "<percent>";
	_AUCT['OptCompete'] = "<silver_less>";
	_AUCT['OptScan'] = "";
	_AUCT['OptScale'] = "<scale_factor>";
	_AUCT['OptScaleDefault'] = 1.0;
	_AUCT['OptDefault'] = "(<option>|".._AUCT['CmdClearAll']..")";
	_AUCT['OptPrintin'] = "(<frameIndex>[Number]|<frameName>[String])";
	_AUCT['OptProtectWindow'] = "(".._AUCT['CmdProtectWindow0'].."||".._AUCT['CmdProtectWindow1'].."||".._AUCT['CmdProtectWindow2']..")";
	_AUCT['OptAuctionDuration'] = "(".._AUCT['CmdAuctionDuration0'].."||".._AUCT['CmdAuctionDuration1'].."||".._AUCT['CmdAuctionDuration2'].."||".._AUCT['CmdAuctionDuration3']..")";
	
	_AUCT['OptPctBidmarkdown'] = "<percent>";
	_AUCT['OptPctMarkup'] = "<percent>";
	_AUCT['OptPctMaxless'] = "<percent>";
	_AUCT['OptPctNocomp'] = "<percent>";
	_AUCT['OptPctUnderlow'] = "<percent>";
	_AUCT['OptPctUndermkt'] = "<percent>";
	
	_AUCT['ShowVerbose'] = "show-verbose";
	_AUCT['ShowAverage'] = "show-average";
	_AUCT['ShowLink'] = "show-link";
	_AUCT['ShowMedian'] = "show-median";
	_AUCT['ShowStats'] = "show-stats";
	_AUCT['ShowSuggest'] = "show-suggest";
	_AUCT['ShowEmbedBlank'] = "show-embed-blankline";
	_AUCT['ShowRedo'] = "show-warning";
	
	_AUCT['HelpOnoff'] = "Turns the auction data display on and off";
	_AUCT['HelpDisable'] = "Stops Auctioneer from automatically loading next time you log in";
	_AUCT['HelpVerbose'] = "Select whether to show averages and suggestions verbosely (or off to show them on a single line)";
	_AUCT['HelpAverage'] = "Select whether to show item's average auction price";
	_AUCT['HelpLink'] = "Select whether to show the link id in the tooltip";
	_AUCT['HelpMedian'] = "Select whether to show item's median buyout price";
	_AUCT['HelpSuggest'] = "Select whether to show item's suggested auction price";
	_AUCT['HelpStats'] = "Select whether to show item's bidded/buyout percentages";
	_AUCT['HelpEmbedBlank'] = "Select whether to show a blank line between the tooltip info and the auction info when embedded mode is on";
	
	_AUCT['HelpClear'] = "Clear the specified item's data (you must shift click insert the item(s) into the command) You may also specify the special keywords \"all\" or \"snapshot\"";
	_AUCT['HelpAlso'] = "Also display another server's values in the tooltip. For realm, insert the realmname and for faction the faction's name. For example: \"/auctioneer also Al'Akir-Horde\". The special keyword \"opposite\" means the opposite faction, \"off\" disables the functionality.";
	_AUCT['HelpLocale'] = "Change the locale that is used to display Auctioneer messages";
	_AUCT['HelpBroker'] = "Show any auctions from the most recent scan that may be bid on and then resold for profit";
	_AUCT['HelpBidbroker'] = "Show short or medium term auctions from the recent scan that may be bid on for profit";
	_AUCT['HelpEmbed'] = "Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
	_AUCT['HelpPercentless'] = "Show any recently scanned auctions whose buyout is a certain percent less than the highest sellable price";
	_AUCT['HelpCompete'] = "Show any recently scanned auctions whose buyout is less than one of your items";
	_AUCT['HelpScan'] = "Perform a scan of the auction house at the next visit, or while you are there (there is also a button in the auction pane). Choose which categories you want to scan with the checkboxes.";
	_AUCT['HelpAutofill'] = "Set whether to autofill prices when dropping new auction items into the auction house window";
	
	_AUCT['HelpPctBidmarkdown'] = "Set the percentage that Auctioneer will mark down bids from the buyout price";
	_AUCT['HelpPctMarkup'] = "The percentage that vendor prices will be marked up when no other values are available";
	_AUCT['HelpPctMaxless'] = "Set the maximum percentage that Auctioneer will undercut market value before it gives up";
	_AUCT['HelpPctNocomp'] = "The percentage that Auctioneer will undercut market value when there is no competition";
	_AUCT['HelpPctUnderlow'] = "Set the percentage that Auctioneer will undercut the lowest auction price";
	_AUCT['HelpPctUndermkt'] = "Percentage to cut market value by when unable to beat competition (due to maxless)";
	_AUCT['HelpRedo'] = "Select whether to show a warning when the currently scanned AH page has taken too long to scan due to server lag.";
	_AUCT['HelpDefault'] = "Set an Auctioneer option to it's default value. You may also specify the special keyword \"all\" to set all Auctioneer options to their default values."
	_AUCT['HelpPrintin'] = "Select which frame Auctioneer will print out it's messages. You can either specify the frame's name or the frame's index.";
	_AUCT['HelpAuctionClick'] = "Allows you to Alt-Click an item in your bag to automatically start an auction for it";
	_AUCT['HelpProtectWindow'] = "Prevents you from accidentally closing the Auction House interface";
	_AUCT['HelpAuctionDuration'] = "Set the default auction duration upon opening the Auction House interface";
	_AUCT['HelpLoad'] = "Change Auctioneer's load settings for this toon";
	
	_AUCT['DisableMsg'] = "Disabling automatic loading of Auctioneer";
	
	_AUCT['StatOn'] = "Displaying configured auction data";
	_AUCT['StatOff'] = "Not displaying any auction data";
	
	_AUCT['FrmtActClearall'] = "Clearing all auction data for %s";
	_AUCT['FrmtActClearsnap'] = "Clearing current Auction House snapshot.";
	_AUCT['FrmtActClearOk'] = "Cleared data for item: %s";
	_AUCT['FrmtActClearFail'] = "Unable to find item: %s";
	_AUCT['FrmtActEnable'] = "Displaying item's %s data";
	_AUCT['FrmtActDisable'] = "Not displaying item's %s data";
	_AUCT['FrmtActEnabledOn'] = "Displaying item's %s on %s";
	_AUCT['FrmtActSet'] = "Set %s to '%s'";
	_AUCT['FrmtActUnknown'] = "Unknown command keyword: '%s'";
	_AUCT['FrmtActDefaultall'] = "All Auctioneer options have been reset to default settings.";
	_AUCT['FrmtActDefault'] = "Auctioneer's %s option has been reset to its default setting";
	_AUCT['FrmtPrintin'] = "Auctioneer's messages will now print on the \"%s\" chat frame";
	_AUCT['FrmtAutostart'] = "Automatically starting auction for %s minimum, %s buyout (%dh)"
	_AUCT['FrmtProtectWindow'] = "Auction House window protection set to: %s";
	_AUCT['FrmtAuctionDuration'] = "Default auction duration set to: %s";
	
	_AUCT['TextScan'] = "Scan";
	_AUCT['TextAuction'] = "auction";
	_AUCT['TextNone'] = "none";
	_AUCT['TextUsage'] = "Usage:";
	
	_AUCT['TextGeneral'] = "General";
	_AUCT['TextCombat'] = "Combat";
	
	
	
	_AUCT['AuctionScanStart'] = "Auctioneer: scanning %s page 1...";
	_AUCT['AuctionPageN'] = "Auctioneer: scanning %s page %d of %d\nAuctions per second: %s\nEstimated time left: %s";
	_AUCT['AuctionScanDone'] = "Auctioneer: auction scanning finished";
	_AUCT['AuctionScanNexttime'] = "Auctioneer will perform a full auction scan the next time you talk to an auctioneer.";
	_AUCT['AuctionScanNocat'] = "You must have at least one category selected to scan.";
	_AUCT['AuctionScanRedo'] = "Current page took more than %d seconds to complete, retrying page.";
	
	_AUCT['MesgConvert'] = "Auctioneer Database Conversion. Please backup your SavedVariables\\Auctioneer.lua first.%s%s";
	_AUCT['MesgNotconverting'] = "Auctioneer is not converting your database, but will not function until you do.";
	_AUCT['MesgConvertYes'] = "Convert";
	_AUCT['MesgConvertNo'] = "Disable Auctioneer";
	
	_AUCT['MesgNotLoaded'] = "Auctioneer is not loaded. Type /auctioneer for more info.";
	
	_AUCT['AuctionTotalAucts'] = "Total auctions scanned: %s";
	_AUCT['AuctionNewAucts'] = "New auctions scanned: %s";
	_AUCT['AuctionOldAucts'] = "Previously scanned: %s";
	_AUCT['AuctionDefunctAucts'] = "Defunct auctions removed: %s";
	_AUCT['AuctionDiscrepancies'] = "Discrepancies: %s";
	
	
	
	_AUCT['GuiRememberText'] = "Remember price";
	_AUCT['GuiNoWorldMap'] = "Auctioneer: suppressed displaying of world map"
	
	_AUCT['GuiMainHelp'] = "Contains settings for Auctioneer \nan AddOn that displays item info and analyzes auction data. \nClick the \"Scan\" button at the AH to collect auction data.";
	_AUCT['GuiMainEnable'] = "Enable Auctioneer";
	_AUCT['GuiLocale'] = "Set locale to";
	_AUCT['GuiVerbose'] = "Verbose Mode";
	_AUCT['GuiStatsEnable'] = "Show Stats";
	
	_AUCT['GuiStatsHeader'] = "Item Price Statistics";
	_AUCT['GuiStatsHelp'] = "Show the following statistics in the tooltip.";
	_AUCT['GuiAverages'] = "Show Averages";
	_AUCT['GuiMedian'] = "Show Medians";
	_AUCT['GuiSuggest'] = "Show Suggested Prices";
	
	_AUCT['GuiEmbedHeader'] = "Embed";
	_AUCT['GuiEmbed'] = "Embed info in in-game tooltip";
	_AUCT['GuiEmbedBlankline'] = "Show blankline in in-game tooltip";
	
	_AUCT['GuiClearHeader'] = "Clear Data";
	_AUCT['GuiClearHelp'] = "Clears Auctioneer data. \nSelect either all data or the current snapshot.\nWARNING: These actions are NOT undoable.";
	_AUCT['GuiClearall'] = "Clear All Auctioneer Data";
	_AUCT['GuiClearallHelp'] = "Click here to clear all of Auctioneer data for the current server-realm.";
	_AUCT['GuiClearallNote'] = "for the current server-faction";
	_AUCT['GuiClearallButton'] = "Clear All";
	_AUCT['GuiClearsnap'] = "Clear Snapshot data";
	_AUCT['GuiClearsnapHelp'] = "Click here to clear the last Auctioneer snapshot data.";
	_AUCT['GuiClearsnapButton'] = "Clear Snapshot";
	
	_AUCT['GuiPercentsHeader'] = "Auctioneer Threshold Percents";
	_AUCT['GuiPercentsHelp'] = "WARNING: The following setting are for Power Users ONLY.\nAdjust the following values to change how aggresive Auctioneer will be when deciding profitable levels.";
	_AUCT['GuiBidmarkdown'] = "Bid Markdown Percent";
	_AUCT['GuiMarkup'] = "Vendor Price Markup Percent";
	_AUCT['GuiMaxless'] = "Max Market Undercut Percent";
	_AUCT['GuiNocomp'] = "No Competition Undercut Percent";
	_AUCT['GuiUnderlow'] = "Lowest Auction Undercut";
	_AUCT['GuiUndermkt'] = "Undercut Market When Maxless";
	
	_AUCT['GuiOtherHeader'] = "Other Options";
	_AUCT['GuiOtherHelp'] = "Miscellaneous Auctioneer Options";
	_AUCT['GuiAutofill'] = "Autofill prices in the AH";
	_AUCT['GuiAlso'] = "Also display data for";
	_AUCT['GuiAlsoOpposite'] = "Now also displaying data for opposite faction.";
	_AUCT['GuiAlsoOff'] = "No longer displaying other realm-faction data.";
	_AUCT['GuiAlsoDisplay'] = "Displaying data for %s";
	_AUCT['GuiLink'] = "Show LinkID";
	_AUCT['GuiReloadui'] = "Reload User Interface";
	_AUCT['GuiReloaduiHelp'] = "Click here to reload the WoW User Interface after changing the locale so that the language in this configuration screen matches the one you selected.\nNote: This operation may take a few minutes.";
	_AUCT['GuiReloaduiButton'] = "ReloadUI";
	_AUCT['GuiReloaduiFeedback'] = "Now Reloading the WoW UI";
	
	_AUCT['GuiRedo'] = "Show Long Scan Warning";
	_AUCT['GuiDefaultAllButton'] = "Reset All";
	_AUCT['GuiDefaultAll'] = "Reset All Auctioneer Options";
	_AUCT['GuiDefaultAllHelp'] = "Click here to set all Auctioneer options to their default values.\nWARNING: This action is NOT undoable.";
	_AUCT['GuiDefaultOption'] = "Reset this setting";
	_AUCT['GuiPrintin'] = "Select the desired message frame";
	_AUCT['GuiProtectWindow'] = "Prevent accidental closing of AH window";
	_AUCT['GuiAuctionDuration'] = "Default auction duration";
	
	_AUCT['GuiAuctionHouseHeader'] = "Auction House window";
	_AUCT['GuiAuctionHouseHeaderHelp'] = "Change the behavior of the Auction House window";
	_AUCT['GuiLoad'] = "Load Auctioneer automatically";
	_AUCT['GuiLoad_Never'] = 'never';
	_AUCT['GuiLoad_Always'] = 'always';
	_AUCT['GuiLoad_AuctionHouse'] = 'at Auction House';
-- Locale strings for the daDK locale
	if locale == "daDK" then
		-- Encoded in UTF8
		
		
		_AUCT['TimeShort'] = "Kort";
		_AUCT['TimeMed'] = "Medium";
		_AUCT['TimeLong'] = "Lang";
		_AUCT['TimeVlong'] = "Meget Lang";
		
		_AUCT['FrmtWelcome'] = "Auctioneer v%s er indl\195\166st";
		
		_AUCT['FrmtBrokerHeader'] = "Minimum profit: %s, HSP = 'H\195\184jeste S\195\166lgende Pris'";
		_AUCT['FrmtBrokerLine'] = "%s, Last %s seen, HSP: %s, BO: %s, Prof: %s";
		_AUCT['FrmtBrokerDone'] = "Liste f\195\166rdig.";
		_AUCT['FrmtBidbrokerHeader'] = "Minimum profit: %s, HSP = 'H\195\184jeste S\195\166lgende Pris'";
		_AUCT['FrmtBidbrokerMinbid'] = "Mindste bud";
		_AUCT['FrmtBidbrokerCurbid'] = "Nuv\195\166rende bud";
		_AUCT['FrmtBidbrokerLine'] = "%s, sidst %s set, HSP: %s, %s: %s, Profit: %s, Tid: %s";
		_AUCT['FrmtBidbrokerDone'] = "Prisliste f\195\166rdig";
		_AUCT['FrmtPctlessHeader'] = "Procent mindre end h\195\184seste s\195\166lgende pris(HSP): %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, sidst %d set, HSP: %s, BO: %s, Profit: %s, Mindre %s";
		_AUCT['FrmtPctlessDone'] = "Udregning af Procenter f\195\166rdig.";
		_AUCT['FrmtCompeteHeader'] = "Konkurerende auktioner er mindst %s under pr. vare.";
		_AUCT['FrmtCompeteLine'] = "%s, Bud: %s, BO %s mod %s, %s mindre";
		_AUCT['FrmtCompeteDone'] = "Competing auctions done.";
		_AUCT['FrmtNoauct'] = "Ingen auktioner blev fundet for: %s";
		_AUCT['FrmtMedianLine'] = "Af sidste %d set, middel BO for 1 %s er: %s";
		_AUCT['FrmtLowLine'] = "%s, BO: %s, s\195\166lger: %s, For en: %s, under middel: %s";
		_AUCT['FrmtHspLine'] = "H\195\184jeste S\195\166lgende Pris for en %s er: %s";
		
		_AUCT['FrmtInfoSeen'] = "Set %d gange p\195\165 auktion ialt";
		_AUCT['FrmtInfoForone'] = "For 1: %s min/%s BO (%s bud) [i %d's]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s BO (%s bud)";
		_AUCT['FrmtInfoHistmed'] = "Sidste %d, middel BO (stk)";
		_AUCT['FrmtInfoSnapmed'] = "Skannede %d, middel BO (stk)";
		_AUCT['FrmtInfoSgststx'] = "Prisforslag for dine %d stk: %s min/%s BO";
		_AUCT['FrmtInfoSgst'] = "Prisforslag: %s min/%s BO";
		
		_AUCT['FrmtInfoBidrate'] = "%d%% har budt, %d%% har BO";
		_AUCT['FrmtInfoNever'] = "Aldrig set p\195\165 %s";
		_AUCT['FrmtInfoAlsoseen'] = "Set %d gange p\195\165 %s";
		
		_AUCT['FrmtInfoHeadMulti'] = "Middel for %d stk.:";
		_AUCT['FrmtInfoMinMulti'] = "  Start bud (%s stk.)";
		_AUCT['FrmtInfoBidMulti'] = "  Bud (%s%s stk.)";
		_AUCT['FrmtInfoBuyMulti'] = "  Opk\195\184bt (%s%s Stk)";
		
		_AUCT['FrmtInfoHeadOne'] = "Middel for denne vare:";
		_AUCT['FrmtInfoMinOne'] = "  Start bud";
		_AUCT['FrmtInfoBidOne'] = "  Bud%s";
		_AUCT['FrmtInfoBuyOne'] = "  Opk\195\184bt%s";
		
		_AUCT['FrmtInfoBuymedian'] = "  Opk\195\184bs median";
		
		_AUCT['FrmtInfoStacksize'] = "  Normal bundt st\195\184rrelse: %d stk.";
		
		_AUCT['FrmtUnknownLocale'] = "Sproget du har valgt: ('%s') findes ikke. Gyldige sprog er:";
		_AUCT['FrmtUnknownRf']     = "Ugyldig parameter ('%s'). Parameteret skal se s\195\165dan ud: [realm]-[faction]. Eksempelvis: Al'Akir-Horde";
		_AUCT['FrmtUnknownArg']    = "'%s' er ikke et gyldigt argument for '%s'";
		
		_AUCT['FrmtActRemove'] = "Fjerner auktion %s fra auktionshuset.";
		
		_AUCT['FrmtAuctinfoHist'] = "%d histoisk";
		_AUCT['FrmtAuctinfoSnap'] = "%d sidst set";
		_AUCT['FrmtAuctinfoLow'] = "Mindste pris";
		_AUCT['FrmtAuctinfoNolow'] = "Ikke set ved sidste skanning.Item not seen last snapshot";
		_AUCT['FrmtAuctinfoOrig'] = "Oprindeligt bud";
		_AUCT['FrmtAuctinfoSugbuy'] = "Foresl\195\165et opk\195\184bspris";
		_AUCT['FrmtAuctinfoSugbid'] = "Foresl\195\165et bud";
		_AUCT['FrmtAuctinfoMktprice'] = "Markets pris";
		
		_AUCT['FrmtWarnMarkup'] = "Overbyde forhandlere med %s%%";
		_AUCT['FrmtWarnUndercut'] = "Underbyde med %s%%";
		_AUCT['FrmtWarnNocomp'] = "Ingen konkurrence";
		_AUCT['FrmtWarnAbovemkt'] = "Din pris ligger over markedet";
		_AUCT['FrmtWarnToolow'] = "Din pris ligger under markedet";
		_AUCT['FrmtWarnMyprice'] = "Bruger din nuv\195\166rende pris";
		_AUCT['FrmtWarnNodata'] = "Ingen data for HSP";
		_AUCT['FrmtWarnUser'] = "Bruger din nuv\195\166rende pris";
		
		_AUCT['CmdOff'] = "off";
		_AUCT['CmdOn'] = "on";
		_AUCT['CmdAlt'] = "alt";
		_AUCT['CmdCtrl'] = "ctrl";
		_AUCT['CmdShift'] = "shift";
		_AUCT['CmdToggle'] = "toggle";
		_AUCT['CmdDisable'] = "disable";
		_AUCT['CmdClear'] = "clear";
		_AUCT['CmdClearAll'] = "all";
		_AUCT['CmdClearSnapshot'] = "snapshot";
		_AUCT['CmdAlso'] = "also";
		_AUCT['CmdAlsoOpposite'] = "opposite";
		_AUCT['CmdLocale'] = "locale";
		_AUCT['CmdDefault'] = "default";
		_AUCT['CmdPrintin'] = "print-in";
		_AUCT['CmdAuctionClick'] = "auction-click";
		
		_AUCT['CmdBroker'] = "broker";
		_AUCT['CmdBidbroker'] = "bidbroker";
		_AUCT['CmdBidbrokerShort'] = "bb";
		_AUCT['CmdEmbed'] = "embed";
		_AUCT['CmdPercentless'] = "percentless";
		_AUCT['CmdPercentlessShort'] = "pl";
		_AUCT['CmdCompete'] = "compete";
		_AUCT['CmdScan'] = "scan";
		_AUCT['CmdAutofill'] = "autofill";
		
		_AUCT['CmdProtectWindow'] = "protect-window"
		_AUCT['CmdProtectWindow0'] = "never"
		_AUCT['CmdProtectWindow1'] = "scan"
		_AUCT['CmdProtectWindow2'] = "always"
		_AUCT['CmdAuctionDuration'] = "auction-duration"
		_AUCT['CmdAuctionDuration0'] = "last"
		_AUCT['CmdAuctionDuration1'] = "2h"
		_AUCT['CmdAuctionDuration2'] = "8h"
		_AUCT['CmdAuctionDuration3'] = "24h"
		
		_AUCT['CmdPctBidmarkdown'] = "pct-bidmarkdown";
		_AUCT['CmdPctMarkup']      = "pct-markup";
		_AUCT['CmdPctMaxless']     = "pct-maxless";
		_AUCT['CmdPctNocomp']      = "pct-nocomp";
		_AUCT['CmdPctUnderlow']    = "pct-underlow";
		_AUCT['CmdPctUndermkt']    = "pct-undermkt";
		
		_AUCT['OptClear'] = "([Item]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
		_AUCT['OptAlso'] = "(realm-faction|".._AUCT['CmdAlsoOpposite']..")";
		_AUCT['OptLocale'] = "<sprog>";
		_AUCT['OptBroker'] = "<fortjenste_i_ s\195\184lv>";
		_AUCT['OptBidbroker'] = "<fortjenste_i_ s\195\184lv>";
		_AUCT['OptPercentless'] = "<procent>";
		_AUCT['OptCompete'] = "<S\195\184lv_under>";
		_AUCT['OptScan'] = "";
		_AUCT['OptScale'] = "<skalerings_faktor>";
		_AUCT['OptScaleDefault'] = 1.0;
		_AUCT['OptDefault'] = "(<option>|".._AUCT['CmdClearAll']..")";
		_AUCT['OptPrintin'] = "(<frameIndex>[Number]|<frameName>[String])";
		_AUCT['OptProtectWindow'] = "(".._AUCT['CmdProtectWindow0'].."||".._AUCT['CmdProtectWindow1'].."||".._AUCT['CmdProtectWindow2']..")";
		_AUCT['OptAuctionDuration'] = "(".._AUCT['CmdAuctionDuration0'].."||".._AUCT['CmdAuctionDuration1'].."||".._AUCT['CmdAuctionDuration2'].."||".._AUCT['CmdAuctionDuration3']..")";
		
		_AUCT['OptPctBidmarkdown'] = "<procent>";
		_AUCT['OptPctMarkup'] = "<procent>";
		_AUCT['OptPctMaxless'] = "<procent>";
		_AUCT['OptPctNocomp'] = "<procent>";
		_AUCT['OptPctUnderlow'] = "<procent>";
		_AUCT['OptPctUndermkt'] = "<procent>";
		
		_AUCT['ShowVerbose'] = "show-verbose";
		_AUCT['ShowAverage'] = "show-average";
		_AUCT['ShowLink'] = "show-link";
		_AUCT['ShowMedian'] = "show-median";
		_AUCT['ShowStats'] = "show-stats";
		_AUCT['ShowSuggest'] = "show-suggest";
		_AUCT['ShowEmbedBlank'] = "show-embed-blankline";
		_AUCT['ShowRedo'] = "show-warning";
		
		_AUCT['HelpOnoff'] = "Sl\195\165r visning af auktions data til og fra.";
		_AUCT['HelpDisable'] = "G\195\184r at Auctioneer ikke indl\195\166ses automatisk n\195\166ste gang du logger ind.";
		_AUCT['HelpVerbose'] = "V\195\166lger hvordan teksten formuleres. (forslag, middelpriser eller off for at vise dem p\195\165 en enkelt linje.)";
		_AUCT['HelpAverage'] = "V\195\166lger om middelprisen p\195\165 en auktion skal vises.";
		_AUCT['HelpLink'] = "V\195\166lger om der skal vises link id i tooltippet.";
		_AUCT['HelpMedian'] = "V\195\166lger om der skal vises middel opk\195\184bspris.";
		_AUCT['HelpSuggest'] = "V\195\166lger om der skal vises foresl\195\165et salgspris ved auktion.";
		_AUCT['HelpStats'] = "V\195\166lger om der skal vises bud/opk\195\184bs pris i procenter.";
		_AUCT['HelpEmbedBlank'] = "V\195\166lg om der skal v\195\166re blanke linjer mellem tooltip info og auktions info n\195\165r embedded mode er valgt";
		
		_AUCT['HelpClear'] = "Sletter data for et specifikt objekt (du skal shift-klikke p\195\165 objektet s\195\165 det kommer ned i kommando boxen.) Du kan ogs\195\165 specifisere enkelte n\195\184gle ord som all eller snapshot";
		_AUCT['HelpAlso'] = "Viser ogs\195\165 en anden servers priser i tooltipet. For realm, inds\195\166t realmnavnet og faction navnet. Som eksempel: \"/auctioneer also Al'Akir-Horde\". Det speciale n\195\184gleord \"opposite\" betyder den modstridne fraktion, \"off\" stopper denne funktion.";
		_AUCT['HelpLocale'] = "Skifter sprog p\195\165 auctioneer scriptet.";
		_AUCT['HelpBroker'] = "Viser auktioner fra sidste scanning som kan blive opk\195\184bt og solgt med fortjeneste.";
		_AUCT['HelpBidbroker'] = "Viser korte og middel auktioner som kan blive budt p\195\165 og solgt med fortjeneste.";
		_AUCT['HelpEmbed'] = "Indrammer teksten i spillets egen tooltip (bem\195\166rk: nogle muligheder vil v\195\166re utilg\195\166ngelige i denne mode.)";
		_AUCT['HelpPercentless'] = "Viser objekter fra sidste skanning hvis opk\195\184bspris er en bestemt procent lavere end den h\195\184jst s\195\166lgende pris.";
		_AUCT['HelpCompete'] = "Viser objekter fra sidste skanning som har lavere opk\195\184bspris end dine ting.";
		_AUCT['HelpScan'] = "Udf\195\184rer en scan af auktionshuset n\195\166ste gang du bes\195\184ger det, eller mens du er der.(Der er ogs\195\165 en knap i auktionshuset under browse, der kan du ogs\195\165 v\195\166lge hvilke katagorier du \195\184nsker at skanne ved at bruge flueben..";
		_AUCT['HelpAutofill'] = "S\195\166t om Auctioneer skal autoudfylde priser n\195\165r objekter overf\195\184res til auktionshusets boks.";
		
		_AUCT['HelpPctBidmarkdown'] = "S\195\166t procenter Auctioneer vil s\195\166tte prisen under objektets opk\195\184bspris.";
		_AUCT['HelpPctMarkup'] = "Procenten som Auctioneer vil overbyde forhandleren p\195\165 et objekt hvor prisen ikke kendes.";
		_AUCT['HelpPctMaxless'] = "S\195\166t den maksimale procent som Auctioneer vil g\195\165 under markeds v\195\166rdi inden den giver op.";
		_AUCT['HelpPctNocomp'] = "Procenten Auctioneer vil g\195\165 under markedet pris n\195\165r der ikke findes konkurrenter";
		_AUCT['HelpPctUnderlow'] = "S\195\166t procenter some Auctioneer vil g\195\165 under den laveste pris";
		_AUCT['HelpPctUndermkt'] = "Procenter Auctioneer vil bruge hvis den ikke kan g\195\165 under konkurrenter (pga. maks/min)";
		_AUCT['HelpRedo'] = "V\195\166lg om der skal vises en advarsel hvis den nuv\195\166rende skanning har taget for lang tid p\195\165 grund af server lag.";
		_AUCT['HelpDefault'] = "S\195\166tter Auctioneer til dens standart v\195\166rdi. Du kan eventuelt bruge n\195\184gleord som: \"all\" for at s\195\166tte alle valg til deres standard v\195\166rdier.";
		_AUCT['HelpPrintin'] = "V\195\166lg hvilken ramme Auctioneer vil skrive til. Du kan enten angive et ramme navn eller rammens indeks nummer.";
		_AUCT['HelpAuctionClick'] = "Giver dig mulighed for at Alt-klikke p\195\165 et objekt i dine tasker for automatisk at starte en auktion for det";
		_AUCT['HelpProtectWindow'] = "Prevents you from accidentally closing the Auction House interface";
		_AUCT['HelpAuctionDuration'] = "Set the default auction duration upon opening the Auction House interface";
		_AUCT['HelpLoad'] = "Change Auctioneer's load settings for this toon";
		
		_AUCT['DisableMsg'] = "Stopper automatisk indl\195\166sning af Auctioneer";
		
		_AUCT['StatOn'] = "Viser kofigureret auktions data.";
		_AUCT['StatOff'] = "Viser ikke nogen auktions data.";
		
		_AUCT['FrmtActClearall'] = "Fjerner alle data for auktionen %s";
		_AUCT['FrmtActClearsnap'] = "Fjerner nuv\195\166rende Auktionhus data.";
		_AUCT['FrmtActClearOk'] = "Fjerner data for objektet: %s";
		_AUCT['FrmtActClearFail'] = "Kan ikke finde objektet: %s";
		_AUCT['FrmtActEnable'] = "Viser data for: %s ";
		_AUCT['FrmtActDisable'] = "Viser ikke data for: %s ";
		_AUCT['FrmtActEnabledOn'] = "Viser objektet: %s p\195\165 %s";
		_AUCT['FrmtActSet'] = "S\195\166tter %s til '%s'";
		_AUCT['FrmtActUnknown'] = "Ukendt commando eller n\195\184gleord: '%s'";
		_AUCT['FrmtActDefaultall'] = "Alle Auctioneers valg er blevet nulstillet til standard v\195\166rdier.";
		_AUCT['FrmtActDefault'] = "Auctioneer's %s valg er blevet nulstillet til standard v\195\166rdier";
		_AUCT['FrmtPrintin'] = "Auctioneer's beskeder vil du blive skrevet til \"%s\" chat ramme";
		_AUCT['FrmtAutostart'] = "Starter automatisk auktion for %s minimum, %s opk\195\184b (%dh)";
		_AUCT['FrmtProtectWindow'] = "Auction House window protection set to: %s";
		_AUCT['FrmtAuctionDuration'] = "Default auction duration set to: %s";
		
		_AUCT['TextScan'] = "Skan";
		_AUCT['TextAuction'] = "auktion";
		_AUCT['TextNone'] = "ingen";
		_AUCT['TextUsage'] = "Brug:";
		
		_AUCT['TextGeneral'] = "General";
		_AUCT['TextCombat'] = "Combat";
		
		-- AH Scanning localizations
		
		_AUCT['AuctionScanStart'] = "Auctioneer: skanner %s side 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: skanner nu %s side %d af %d\nAuktioner pr sekund: %s\nBeregnet tid tilbage: %s";
		_AUCT['AuctionScanDone'] = "Auctioneer: Skanningen af auktionerne er f\195\166rdig.";
		_AUCT['AuctionScanNexttime'] = "Auctioneer vil udf\195\184re en komplet scanning af auktionshuset n\195\166ste gang du snakker med en auktion\195\166r.";
		_AUCT['AuctionScanNocat'] = "Du skal v\195\166lge mindst en kategori for at kan skanne.";
		_AUCT['AuctionScanRedo'] = "Nuv\195\166rende side tog mere end %d sekunder at f\195\166rdig\195\184re, fors\195\184ger at indl\195\166se siden igen.";
		
		_AUCT['MesgConvert'] = "Konventere Auctioneer Databasen. Tag venligst en backup af SavedVariables\\Auctioneer.lua inden.%s%s";
		_AUCT['MesgNotconverting'] = "Auctioneer konventere ikke din database, men vil ikke virke f\195\184r du g\195\184r.";
		_AUCT['MesgConvertYes'] = "Konventer nu";
		_AUCT['MesgConvertNo'] = "Indl\195\166s ikke Auctioneer";
		
		_AUCT['MesgNotLoaded'] = "Auctioneer er ikke indl\195\166st. Skriv /auctioneer for mere info.";
		
		_AUCT['AuctionTotalAucts'] = "Auktioner skannet ialt: %s";
		_AUCT['AuctionNewAucts'] = "Nye auktioner skannet: %s";
		_AUCT['AuctionOldAucts'] = "Skannet f\195\184r: %s";
		_AUCT['AuctionDefunctAucts'] = "Afsluttede auktioner fjernet: %s";
		_AUCT['AuctionDiscrepancies'] = "Uoverensstemmelser: %s";
		
		-- GUI localizations
		
		_AUCT['GuiRememberText'] = "Husk prisen";
		_AUCT['GuiNoWorldMap'] = "Auctioneer: suppressed displaying of world map"
		
		_AUCT['GuiMainHelp'] = "Indeholder v\195\166rdier for Auctioneer \nan AddOn som viser information og analysere data. \nKlik p\195\165 \"Skan\" knappen p\195\165 AH for at indsamle auktions data.";
		_AUCT['GuiMainEnable'] = "Start Auctioneer";
		_AUCT['GuiLocale'] = "S\195\166t sprog til";
		_AUCT['GuiVerbose'] = "Tekst Mode";
		_AUCT['GuiStatsEnable'] = "Vis Stats";
		
		_AUCT['GuiStatsHeader'] = "Objekt Pris Statestik";
		_AUCT['GuiStatsHelp'] = "Vis f\195\184lgende statestikker i tooltippet.";
		_AUCT['GuiAverages'] = "Vis middel";
		_AUCT['GuiMedian'] = "Vis middel";
		_AUCT['GuiSuggest'] = "Vis foresl\195\165ede priser";
		
		_AUCT['GuiEmbedHeader'] = "Indrammet";
		_AUCT['GuiEmbed'] = "Indrammet info i spillets tooltip";
		_AUCT['GuiEmbedBlankline'] = "Viser blank linje i spillets tooltip";
		
		_AUCT['GuiClearHeader'] = "Slet Data";
		_AUCT['GuiClearHelp'] = "Slet Auctioneer data. \nV\195\166lg alle data eller det nuv\195\166rende snapshot.\nADVARSEL: Disse handlinger kan IKKE fortrydes.";
		_AUCT['GuiClearall'] = "Slet Alle Auctioneer Data";
		_AUCT['GuiClearallHelp'] = "Klik her for at fjere all data fra Auctioneer for den nuv\195\166rende server og realm.";
		_AUCT['GuiClearallNote'] = "for den nuv\195\166rende server-faction";
		_AUCT['GuiClearallButton'] = "Slet alt";
		_AUCT['GuiClearsnap'] = "Slet Snapshot data";
		_AUCT['GuiClearsnapHelp'] = "Klik her for at slette den sidste skanning af auktionen.";
		_AUCT['GuiClearsnapButton'] = "Fjern Snapshot";
		
		_AUCT['GuiPercentsHeader'] = "Auctioneer Threshold Percents";
		_AUCT['GuiPercentsHelp'] = "Advarsel: De f\195\184lgende valgmuligheder er KUN for Superbrugere.\nVed at \195\166ndre p\195\165 f\195\184lgende muligheder \195\166ndre du hvor aggresivt Auctioneer vil v\195\166re n\195\165r den udregner profit.";
		_AUCT['GuiBidmarkdown'] = "Neds\195\166t bud med xx procent";
		_AUCT['GuiMarkup'] = "Procent overbud iht. forhandler";
		_AUCT['GuiMaxless'] = "Procent maks. under markeds pris";
		_AUCT['GuiNocomp'] = "Procent under markedets pris ved ingen konkurence";
		_AUCT['GuiUnderlow'] = "Laveste auktionspris";
		_AUCT['GuiUndermkt'] = "Underbyd markedet n\195\165r der ingen maxpris findes.";
		
		_AUCT['GuiOtherHeader'] = "Andre valg";
		_AUCT['GuiOtherHelp'] = "Diverse valg til Auctioneer";
		_AUCT['GuiAutofill'] = "Autoudfyld priser p\195\165 AH";
		_AUCT['GuiAlso'] = "Vis ogs\195\165 data for";
		_AUCT['GuiAlsoOpposite'] = "Viser nu ogs\195\165 data for modsatte fraktion.";
		_AUCT['GuiAlsoOff'] = "Viser ikke l\195\166ngre data fra andre realm-fraktioner.";
		_AUCT['GuiAlsoDisplay'] = "Viser data for %s";
		_AUCT['GuiLink'] = "Viser LinkID";
		_AUCT['GuiReloadui'] = "Genindl\195\166ser brugerflade.";
		_AUCT['GuiReloaduiHelp'] = "Klik her for at genindl\195\166se WoW brugerfladen efter at have \195\166ndret sprog.\nBem\195\166rk: Dette kan tage et par minutter.";
		_AUCT['GuiReloaduiButton'] = "Genindl\195\166sUI";
		_AUCT['GuiReloaduiFeedback'] = "Genindl\195\166ser nu WoW UI";
		
		_AUCT['GuiRedo'] = "Vis advarsel ved lang skanning.";
		_AUCT['GuiDefaultAllButton'] = "Nulstil alt";
		_AUCT['GuiDefaultAll'] = "Nulstil alle Auctioneer valg";
		_AUCT['GuiDefaultAllHelp'] = "Klik her for at s\195\166tte alle Auctioneer valg til standard v\195\166rdier.\nADVARSEL: Denne handling kan IKKE fortrydes.";
		_AUCT['GuiDefaultOption'] = "Nulstil denne ops\195\166tning.";
		_AUCT['GuiPrintin'] = "V\195\166lg den \195\184nskede chat ramme.";
		_AUCT['GuiProtectWindow'] = "Prevent accidental closing of AH window";
		_AUCT['GuiAuctionDuration'] = "Default auction duration";
		
		_AUCT['GuiAuctionHouseHeader'] = "Auction House window";
		_AUCT['GuiAuctionHouseHeaderHelp'] = "Change the behavior of the Auction House window";
		_AUCT['GuiLoad'] = "Load Auctioneer automatically";
		_AUCT['GuiLoad_Never'] = 'never';
		_AUCT['GuiLoad_Always'] = 'always';
		_AUCT['GuiLoad_AuctionHouse'] = 'at Auction House';
	end

-- Locale strings for the deDE locale
	if locale == "deDE" then
		-- Encoded in UTF8
		
		
		_AUCT['TimeShort'] = "Kurz";
		_AUCT['TimeMed'] = "Mittel";
		_AUCT['TimeLong'] = "Lang";
		_AUCT['TimeVlong'] = "Sehr lang";
		
		_AUCT['FrmtWelcome'] = "Auctioneer v%s geladen";
		
		_AUCT['FrmtBrokerHeader'] = "Mindestprofit: %s, HVP = 'H\195\182chster verk\195\164uflicher Preis'";
		_AUCT['FrmtBrokerLine'] = "%s, zuletzt %s gesehen, HVP: %s, Sofortkauf: %s, Profit: %s";
		_AUCT['FrmtBrokerDone'] = "Brokern fertig";
		_AUCT['FrmtBidbrokerHeader'] = "Mindest Profit: %s, HVP = 'H\195\182chster verk\195\164uflicher Preis'";
		_AUCT['FrmtBidbrokerMinbid'] = "min. Gebot"
		_AUCT['FrmtBidbrokerCurbid'] = "akt. Gebot"
		_AUCT['FrmtBidbrokerLine'] = "%s, zuletzt %s gesehen, HVP: %s, %s: %s, Profit: %s, Restzeit: %s";
		_AUCT['FrmtBidbrokerDone'] = "Gebotbrokern fertig";
		_AUCT['FrmtPctlessHeader'] = "Prozent billiger als der 'H\195\182chster verk\195\164uflicher Preis (HVP)': %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, zuletzt %d gesehen, HSP: %s, Sofortkauf: %s, Prof: %s, Billiger %s";
		_AUCT['FrmtPctlessDone'] = "Prozent unter HSP fertig.";
		_AUCT['FrmtCompeteHeader'] = "Konkurrierende Auktionen mindestens %s billiger pro St\195\188ck.";
		_AUCT['FrmtCompeteLine'] = "%s, Gebot: %s, Sofortkauf %s vs %s, %s billiger";
		_AUCT['FrmtCompeteDone'] = "Konkurrierende Auktionen fertig.";
		_AUCT['FrmtNoauct'] = "Keine Aktionen f\195\188r %s gefunden.";
		_AUCT['FrmtMedianLine'] = "Der Median der %d zuletzt gesehenen %s liegt bei %s/St\195\188ck.";
		_AUCT['FrmtLowLine'] = "%s, Sofortkauf: %s, Verk\195\164ufer: %s, %s/St\195\188ck, %s unter dem Median";
		_AUCT['FrmtHspLine'] = "H\195\182chster verk\195\164uflicher Preis pro %s ist: %s";
		
		_AUCT['FrmtInfoSeen'] = "Insgesamt %d mal in Auktionen gesehen";
		_AUCT['FrmtInfoForone'] = "Pro St\195\188ck: %s min/%s Sofortkauf (%s geboten) [in %d]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s Sofortkauf (%s geboten)"
		_AUCT['FrmtInfoHistmed'] = "Sofortkauf-Median (pro St\195\188ck) der %d letzten Auktionen:";
		_AUCT['FrmtInfoSnapmed'] = "Sofortkauf-Median (pro St\195\188ck) aus %d gescannten Auktionen:";
		_AUCT['FrmtInfoSgststx'] = "Empfohlener Preis f\195\188r diesen %der Stapel: %s min/%s Sofortkauf";
		_AUCT['FrmtInfoSgst'] = "Empfohlener Preis: %s min/%s Sofortkauf";
		
		_AUCT['FrmtInfoBidrate'] = "%d%% haben Gebote, %d%% haben Sofortkauf";
		_AUCT['FrmtInfoNever'] = "Noch in keiner %s gesehen";
		_AUCT['FrmtInfoAlsoseen'] = "%d mal in einer %s gesehen";
		
		_AUCT['FrmtInfoHeadMulti'] = "Durchschnitt f\195\188r %d St\195\188ck:";
		_AUCT['FrmtInfoMinMulti'] = "  Min. Startgebot (%s pro St\195\188ck)";
		_AUCT['FrmtInfoBidMulti'] = "  Geboten (%s%s pro St\195\188ck)";
		_AUCT['FrmtInfoBuyMulti'] = "  Sofortkauf (%s%s pro St\195\188ck)";
		
		_AUCT['FrmtInfoHeadOne'] = "Durchschnitt f\195\188r diesen Gegenstand:";
		_AUCT['FrmtInfoMinOne'] = "  Min. Startgebot";
		_AUCT['FrmtInfoBidOne'] = "  Geboten%s";
		_AUCT['FrmtInfoBuyOne'] = "  Sofortkauf%s";
		
		_AUCT['FrmtInfoBuymedian'] = "  Sofortkauf-Median";
		
		_AUCT['FrmtInfoStacksize'] = "  Durchschnittliche Stapelgr\195\182\195\159e: %d St\195\188ck";
		
		_AUCT['FrmtUnknownLocale'] = "Das angegebene Gebietsschema ('%s') ist unbekannt. G\195\188ltige Gebietsschemen sind:";
		_AUCT['FrmtUnknownRf'] = "Der angegebene Parameter ('%s') ist ung\195\188ltig. Der Parameter muss das Format: [Realm]-[Fraktion] haben. Zum Beispiel: Kil'Jaeden-Alliance";
		_AUCT['FrmtUnknownArg'] = "'%s' ist kein g\195\188ltiges Argument f\195\188r '%s'";
		
		_AUCT['FrmtActRemove'] = "Entferne Aktionssignatur %s von dem derzeitigen AH-Abbild.";
		
		_AUCT['FrmtAuctinfoHist'] = "%d historisch";
		_AUCT['FrmtAuctinfoSnap'] = "%d aus letztem Scan";
		_AUCT['FrmtAuctinfoLow'] = "billigster Snapshot";
		_AUCT['FrmtAuctinfoNolow'] = "Nicht im letzten Snapshot gesehn";
		_AUCT['FrmtAuctinfoOrig'] = "Original-Gebot";
		_AUCT['FrmtAuctinfoSugbuy'] = "Empf. Sofortkauf";
		_AUCT['FrmtAuctinfoSugbid'] = "Empf. Gebot";
		_AUCT['FrmtAuctinfoMktprice'] = "Marktpreis";
		
		_AUCT['FrmtWarnMarkup'] = "%s%% erh\195\182hter H\195\164ndlerpreis";
		_AUCT['FrmtWarnUndercut'] = "Unterbiete um %s%%";
		_AUCT['FrmtWarnNocomp'] = "Monopol";
		_AUCT['FrmtWarnAbovemkt'] = "Konkurrenz keine Gefahr";
		_AUCT['FrmtWarnToolow'] = "Konkurrenz zu g\195\188nstig";
		_AUCT['FrmtWarnMyprice'] = "Verwende eigenen Preis";
		_AUCT['FrmtWarnNodata'] = "Keine HVP-Daten";
		_AUCT['FrmtWarnUser'] = "Verwende letzte Preisvorgabe";
		
		_AUCT['CmdOff'] = "off";
		_AUCT['CmdOn'] = "on";
		_AUCT['CmdAlt'] = "alt";
		_AUCT['CmdCtrl'] = "ctrl";
		_AUCT['CmdShift'] = "shift";
		_AUCT['CmdToggle'] = "toggle";
		_AUCT['CmdDisable'] = "disable";
		_AUCT['CmdClear'] = "clear";
		_AUCT['CmdClearAll'] = "all";
		_AUCT['CmdClearSnapshot'] = "snapshot";
		_AUCT['CmdAlso'] = "also";
		_AUCT['CmdAlsoOpposite'] = "opposite";
		_AUCT['CmdLocale'] = "locale";
		_AUCT['CmdDefault'] = "default";
		_AUCT['CmdPrintin'] = "print-in";
		_AUCT['CmdAuctionClick'] = "auction-click";
		
		_AUCT['CmdBroker'] = "broker";
		_AUCT['CmdBidbroker'] = "bidbroker";
		_AUCT['CmdBidbrokerShort'] = "bb";
		_AUCT['CmdEmbed'] = "embed";
		_AUCT['CmdPercentless'] = "percentless";
		_AUCT['CmdPercentlessShort'] = "pl";
		_AUCT['CmdCompete'] = "compete";
		_AUCT['CmdScan'] = "scan";
		_AUCT['CmdAutofill'] = "autofill";
		
		_AUCT['CmdProtectWindow'] = "protect-window"
		_AUCT['CmdProtectWindow0'] = "never"
		_AUCT['CmdProtectWindow1'] = "scan"
		_AUCT['CmdProtectWindow2'] = "always"
		_AUCT['CmdAuctionDuration'] = "auction-duration"
		_AUCT['CmdAuctionDuration0'] = "last"
		_AUCT['CmdAuctionDuration1'] = "2h"
		_AUCT['CmdAuctionDuration2'] = "8h"
		_AUCT['CmdAuctionDuration3'] = "24h"
		
		_AUCT['CmdPctBidmarkdown'] = "pct-bidmarkdown";
		_AUCT['CmdPctMarkup'] = "pct-markup";
		_AUCT['CmdPctMaxless'] = "pct-maxless";
		_AUCT['CmdPctNocomp'] = "pct-nocomp";
		_AUCT['CmdPctUnderlow'] = "pct-underlow";
		_AUCT['CmdPctUndermkt'] = "pct-undermkt";
		
		_AUCT['OptClear'] = "([Gegenstand]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
		_AUCT['OptAlso'] = "(Realm-Fraktion|".._AUCT['CmdAlsoOpposite']..")"
		_AUCT['OptLocale'] = "<Gebietsschema>";
		_AUCT['OptBroker'] = "<Gewinn in Silber>";
		_AUCT['OptBidbroker'] = "<Gewinn in Silber>";
		_AUCT['OptPercentless'] = "<Prozent>";
		_AUCT['OptCompete'] = "<Preisnachlass in Silber>";
		_AUCT['OptScan'] = "";
		_AUCT['OptScale'] = "<Skalierungsfaktor>";
		_AUCT['OptScaleDefault'] = 1.0;
		_AUCT['OptDefault'] = "(<Option>|".._AUCT['CmdClearAll']..")";
		_AUCT['OptPrintin'] = "(<Index>[Nummer]|<Name>[Zeichenfolge])";
		_AUCT['OptProtectWindow'] = "(".._AUCT['CmdProtectWindow0'].."||".._AUCT['CmdProtectWindow1'].."||".._AUCT['CmdProtectWindow2']..")";
		_AUCT['OptAuctionDuration'] = "(".._AUCT['CmdAuctionDuration0'].."||".._AUCT['CmdAuctionDuration1'].."||".._AUCT['CmdAuctionDuration2'].."||".._AUCT['CmdAuctionDuration3']..")";
		
		_AUCT['OptPctBidmarkdown'] = "<Prozent>";
		_AUCT['OptPctMarkup'] = "<Prozent>";
		_AUCT['OptPctMaxless'] = "<Prozent>";
		_AUCT['OptPctNocomp'] = "<Prozent>";
		_AUCT['OptPctUnderlow'] = "<Prozent>";
		_AUCT['OptPctUndermkt'] = "<Prozent>";
		
		_AUCT['ShowVerbose'] = "show-verbose";
		_AUCT['ShowAverage'] = "show-average";
		_AUCT['ShowLink'] = "show-link";
		_AUCT['ShowMedian'] = "show-median";
		_AUCT['ShowStats'] = "show-stats";
		_AUCT['ShowSuggest'] = "show-suggest";
		_AUCT['ShowEmbedBlank'] = "show-embed-blankline";
		_AUCT['ShowRedo'] = "show-warning";
		
		_AUCT['HelpOnoff'] = "Schaltet die Anzeige der Auktionsdaten ein/aus.";
		_AUCT['HelpDisable'] = "Verhindert das automatische Laden von Auctioneer beim Login";
		_AUCT['HelpVerbose'] = "Schaltet die detaillierte Anzeige der Durchschnittswerte und Preisempfehlungen ein/aus. Deaktivieren reduziert die Datenanzeige auf eine Zeile.";
		_AUCT['HelpAverage'] = "Schaltet die Anzeige des durchschnittlichen Auktionspreises ein/aus.";
		_AUCT['HelpLink'] = "Schaltet die Anzeige der Link-ID im Tooltip ein/aus.";
		_AUCT['HelpMedian'] = "Schaltet die Anzeige des Median-Sofortkaufpreises ein/aus.";
		_AUCT['HelpSuggest'] = "Schaltet die Anzeige des empfohlenen Auktionspreises ein/aus.";
		_AUCT['HelpStats'] = "Schaltet die Prozentanzeige der/des Gebote/Sofortkaufes ein/aus.";
		_AUCT['HelpEmbedBlank'] = "Schaltet die Anzeige einer Leerzeile zwischen der Tooltipinfo und der Auktionsinfo im Embedded-Mode ein/aus.";
		
		_AUCT['HelpClear'] = "L\195\182scht die Daten der angegebene Gegenst\195\164nde (Gegenst\195\164nde durch Shift+Linksklick dem Befehl hinzuf\195\188gen) Es k\195\182nnen auch die speziellen Keywords \"".._AUCT['CmdClearAll'].."\" und \"".._AUCT['CmdClearSnapshot'].."\" hinzugef\195\188gt werden.";
		_AUCT['HelpAlso'] = "Zeigt ebenfalls die Werte anderer Server im Tooltip an. Setze den Namen des Realms f\195\188r Realm und den Namen der Faktion f\195\188r Fraktion ein. Zum Beispiel: \"/auctioneer also Kil'Jaeden-Alliance\". Das spezielle Keywort \"".._AUCT['CmdAlsoOpposite'].."\" bedeutet die gegnerische Franktion, \"off\" deaktiviert die Funktionalit\195\164t.";
		_AUCT['HelpLocale'] = "\195\132ndert das Gebietsschema das zur Anzeige von Auctioneer-Meldungen verwendet wird.";
		_AUCT['HelpBroker'] = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, die per Sofortkauf gekauft und mit Gewinn wieder verkauft werden k\195\182nnen.";
		_AUCT['HelpBidbroker'] = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans mit kurzer oder mittlerer Restlaufzeit an, die per Gebot ersteigert und mit Gewinn wieder verkauft werden k\195\182nnen.";
		_AUCT['HelpEmbed'] = "Bindet den Auktionsinfotext in den WoW-Tooltip ein (Hinweis: Einige Funktionen sind in diesem Modus deaktiviert).";
		_AUCT['HelpPercentless'] = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, deren Sofortkaufpreis einen gewissen Prozentsatz unter dem h\195\182chstm\195\182glichen Verkaufspreis liegt.";
		_AUCT['HelpCompete'] = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, deren Sofortkaufpreis geringer ist als der eines eigenen im AH angebotenen Gegenstandes.";
		_AUCT['HelpScan'] = "F\195\188hrt einen Scan des Auktionshauses beim n\195\164chsten Besuch durch bzw. sofort, wenn man schon dort ist (es gibt ebenfalls einen Knopf im Auktionshausfenster). \195\156ber die Auswahlboxen k\195\182nnen die zu scannenden Kategorien gew\195\164hlt werden.";
		_AUCT['HelpAutofill'] = "Gibt an, ob die Preise automatisch ausgef\195\188llt werden sollen, wenn ein Gegenstand ins Auktionshaus gelegt wird.";
		
		_AUCT['HelpPctBidmarkdown'] = "Legt den Prozentsatz fest, um den das Mindestgebot niedriger als der Sofortkaufpreis ist.";
		_AUCT['HelpPctMarkup'] = "Legt den Prozentsatz f\195\188r erh\195\182hte H\195\164ndlerpreise fest, der verwendet wird, falls sonst keine anderen Werte verf\195\188gbar sind.";
		_AUCT['HelpPctMaxless'] = "Legt den maximalen Prozentsatz fest, um den der Marktpreis versucht wird zu verringern, bevor aufgegeben wird";
		_AUCT['HelpPctNocomp'] = "Legt den Prozentsatz fest, um den der Marktpreis gesenkt wird, wenn kein konkurierendes Angebot existiert.";
		_AUCT['HelpPctUnderlow'] = "Legt den Prozentsatz fest, um den das g\195\188nstigste konkurierende Angebot unterboten wird.";
		_AUCT['HelpPctUndermkt'] = "Legt den Prozentsatz fest, um den der Marktpreis gesenkt wird, wenn durch den gew\195\164hlten Preozentsatz f\195\188r maxless ein konkurierendes Angebot nicht unterboten werden kann.";
		_AUCT['HelpRedo'] = "Legt fest, ob eine Warnung angezeigt werden soll, wenn die zuletzt gescannte Seite im AH wegen Serverlag zu lange braucht."
		_AUCT['HelpDefault'] = "Setzt die angegebene Auctioneer-Option auf ihren Standardwert zur\195\188ck. Mit dem Schl\195\188sselwort \"".._AUCT['CmdClearAll'].."\" werden alle Auctioneer-Optionen zur\195\188ckgesetzt."
		_AUCT['HelpPrintin'] = "Ausw\195\164hlen in welchem Fenster die Auctioneer-Meldungen angezeigt werden. Es kann entweder der Fensterindex oder der Fenstername angegeben werden.";
		_AUCT['HelpAuctionClick'] = "Erlaubt es mittels Alt-Klick automatisch eine Auktion f\195\188r einen Gegenstand aus deiner Tasche zu starten";
		_AUCT['HelpProtectWindow'] = "Verhindert das versehentliche Schlie\195\159en des Auktionshaus-Fensters.";
		_AUCT['HelpAuctionDuration'] = "Setzt die Standard-Auktionsdauer beim \195\150ffnen des Auktionshaus-Fensters";
		_AUCT['HelpLoad'] = "\195\132ndert das Ladeverhalten von Auctioneer f\195\188r diesen Charakter";
		
		_AUCT['DisableMsg'] = "Das automatische Laden von Auctioneer wird deaktiviert";
		
		_AUCT['StatOn'] = "Auktionsdaten werden angezeigt.";
		_AUCT['StatOff'] = "Auktionsdaten werden nicht angezeigt.";
		
		_AUCT['FrmtActClearall'] = "L\195\182sche alle Auktionsdaten f\195\188r %s";
		_AUCT['FrmtActClearsnap'] = "L\195\182sche aktuelles Auktionshaus-Abbild.";
		_AUCT['FrmtActClearOk'] = "Daten f\195\188r %s wurden gel\195\182scht";
		_AUCT['FrmtActClearFail'] = "Kann %s nicht finden";
		_AUCT['FrmtActEnable'] = "%s wird angezeigt";
		_AUCT['FrmtActDisable'] = "%s wird nicht angezeigt";
		_AUCT['FrmtActEnabledOn'] = "Zeige %s auf %s";
		_AUCT['FrmtActSet'] = "Setze %s auf '%s'";
		_AUCT['FrmtActUnknown'] = "Unbekannter Befehl: '%s'";
		_AUCT['FrmtActDefaultall'] = "Alle Einstellungen wurden auf Standardwerte zur\195\188ckgesetzt.";
		_AUCT['FrmtActDefault'] = "%s wurde auf den Standardwert zur\195\188ckgesetzt.";
		_AUCT['FrmtPrintin'] = "Die Auctioneer-Meldungen werden nun im Chat-Fenster \"%s\" angezeigt";
		_AUCT['FrmtAutostart'] = "Automatischer Start der Auktion f\195\188r %s Minimum, %s Sofortkauf (%dh)"
		_AUCT['FrmtProtectWindow'] = "Der Schutzmodus des Auktionshaus-Fensters wurde auf \"%s\" gesetzt";
		_AUCT['FrmtAuctionDuration'] = "Die Standard-Auktionsdauer wurde auf \"%s\" gesetzt";
		
		_AUCT['TextScan'] = "Scannen";
		_AUCT['TextAuction'] = "Auktion";
		_AUCT['TextNone'] = "nichts";
		_AUCT['TextUsage'] = "Syntax:";
		
		_AUCT['TextGeneral'] = "Allgemein";
		_AUCT['TextCombat'] = "Kampflog";
		
		-- AH Scanning localizations
		
		_AUCT['AuctionScanStart'] = "Auctioneer: Scanne %s Seite 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: Scanne %s Seite %d von %d\nAuktionen pro Sekunde: %s\nGesch\195\164tzte Restzeit: %s";
		_AUCT['AuctionScanDone'] = "Auctioneer: Scanvorgang abgeschlossen";
		_AUCT['AuctionScanNexttime'] = "Auctioneer wird einen kompletten Auktionsscan durchf\195\188hren, wenn das n\195\164chste mal mit einem Auktionator gesprochen wird.";
		_AUCT['AuctionScanNocat'] = "Es muss mindestens eine Kategorie ausgew\195\164hlt sein, um den Scanvorgang zu starten.";
		_AUCT['AuctionScanRedo'] = "Aktuelle Seite braucht l\195\164nger als %d Sekunden. Fahre mit n\195\164chster Seite fort.";
		
		_AUCT['MesgConvert'] = "Auctioneer Datenbankkonvertierung. Bitte zuerst ein Backup von SavedVariables\\Auctioneer.lua anlegen!%s%s";
		_AUCT['MesgNotconverting'] = "Die Datenbank von Auctioneer wird nicht konvertiert. Auctioneer bleibt deaktiviert, solange die Datenbank nicht konvertiert wurde.";
		_AUCT['MesgConvertYes'] = "Konvertieren";
		_AUCT['MesgConvertNo'] = "Deaktiviere Auctioneer";
		
		_AUCT['MesgNotLoaded'] = "Auctioneer ist nicht geladen. Geben Sie /auctioneer ein um mehr Informationen zu erhalten.";
		
		_AUCT['AuctionTotalAucts'] = "Insgesammt gescannte Auktionen: %s";
		_AUCT['AuctionNewAucts'] = "Davon neu: %s";
		_AUCT['AuctionOldAucts'] = "Davon alt: %s";
		_AUCT['AuctionDefunctAucts'] = "Abgelaufene Auktionen: %s";
		_AUCT['AuctionDiscrepancies'] = "Unstimmigkeiten: %s";
		
		-- GUI localizations
		
		_AUCT['GuiRememberText'] = "Preis merken";
		_AUCT['GuiNoWorldMap'] = "Auctioneer: Die Anzeige der Weltkarte wurde unterdr\195\188ckt"
		
		_AUCT['GuiMainHelp'] = "Einstellungen f\195\188r Auctioneer, \neinem AddOn das zus\195\164tzliche Informationen von Gegenst\195\164nden anzeigt und Auktionsdaten analysiert.\nDr\195\188cke den \"Scannen\"-Knopf im Auktionshaus, um Auktionsdaten zu sammeln.";
		_AUCT['GuiMainEnable'] = "Auctioneer aktivieren";
		_AUCT['GuiLocale'] = "Setze das Gebietsschema auf";
		_AUCT['GuiVerbose'] = "Detaillierte Informationen";
		_AUCT['GuiStatsEnable'] = "Statistiken anzeigen";
		
		_AUCT['GuiStatsHeader'] = "Preisstatistiken";
		_AUCT['GuiStatsHelp'] = "Zeigt die folgenden Statistiken im Tooltip an.";
		_AUCT['GuiAverages'] = "Zeige den Durchschnitt an.";
		_AUCT['GuiMedian'] = "Zeige den Median an.";
		_AUCT['GuiSuggest'] = "Zeige empfohlene Preise an.";
		
		_AUCT['GuiEmbedHeader'] = "Art der Anzeige";
		_AUCT['GuiEmbed'] = "In-Game Tooltip zur Anzeige verwenden";
		_AUCT['GuiEmbedBlankline'] = "Leerzeile in den In-Game Tooltip einf\195\188gen";
		
		_AUCT['GuiClearHeader'] = "Daten l\195\182schen";
		_AUCT['GuiClearHelp'] = "Auctioneerdaten l\195\182schen.\nW\195\164hle entweder alle Daten oder nur den aktuellen Snapshot aus.\nWARNUNG: Das L\195\182schen kann nicht r\195\188ckg\195\164ngig gemacht werden!"
		_AUCT['GuiClearall'] = "L\195\182sche alle Auctioneerdaten";
		_AUCT['GuiClearallHelp'] = "Hier dr\195\188cken, um die gesamten Auctioneerdaten des aktuellen Realms zu l\195\182schen.";
		_AUCT['GuiClearallNote'] = "der aktuellen Fraktion auf dem aktuellen Realm";
		_AUCT['GuiClearallButton'] = "Alles l\195\182schen";
		_AUCT['GuiClearsnap'] = "Snapshotdaten l\195\182schen";
		_AUCT['GuiClearsnapHelp'] = "Hier dr\195\188cken, um die aktuellen Snapshotdaten von Auctioneer zu l\195\182schen.";
		_AUCT['GuiClearsnapButton'] = "L\195\182schen";
		
		_AUCT['GuiPercentsHeader'] = "Auctioneer Prozentschwellwerte";
		_AUCT['GuiPercentsHelp'] = "WARNUNG: Die folgenden Einstellungen sind nur f\195\188r erfahrene Benutzer.\nDie folgenden Werte k\195\182nnen ge\195\164ndert werden, um festzulegen, wie aggressiv Auctioneer vorgehen soll, um den profitabelsten Preis zu berechnen.";
		_AUCT['GuiBidmarkdown'] = "Gebot um x% unterbieten";
		_AUCT['GuiMarkup'] = "H\195\164ndlerpreis um x% erh\195\182hen";
		_AUCT['GuiMaxless'] = "Marktpreis um max. x% unterbieten";
		_AUCT['GuiNocomp'] = "Marktpreis um x% im Monopol\nverringern";
		_AUCT['GuiUnderlow'] = "Marktpreis um x% verringern, wenn\nKonkurrenz keine Gefahr ist";
		_AUCT['GuiUndermkt'] = "Marktpreis um x% verringern, wenn\nKonkurrenz zu g\195\188nstig ist";
		
		_AUCT['GuiOtherHeader'] = "Sonstige Optionen";
		_AUCT['GuiOtherHelp'] = "Sonstige Auctioneer-Optionen";
		_AUCT['GuiAutofill'] = "Preise im Auktionshaus automatisch eintragen";
		_AUCT['GuiAlso'] = "Zeige zus\195\164tzlich Daten f\195\188r \nfolgende(n) Realm/Fraktion an";
		_AUCT['GuiAlsoOpposite'] = "Daten der gegnerischen Fraktion werden jetzt ebenfalls angezeigt.";
		_AUCT['GuiAlsoOff'] = "Es werden keine Daten mehr f\195\188r einen anderen Realm / eine andere Fraktion angezeigt.";
		_AUCT['GuiAlsoDisplay'] = "Zeige Daten fpr %s an";
		_AUCT['GuiLink'] = "Zeige LinkID an";
		_AUCT['GuiReloadui'] = "Benutzeroberfl\195\164che neu laden";
		_AUCT['GuiReloaduiHelp'] = "Hier klicken um die WoW-Benutzeroberfl\195\164che nach einer \n\195\132nderung des Gebietsschemas neu zu laden, und dadurch \ndie Sprache des Konfigurationsmen\195\188s diesem entspricht.\nHinweis: Dieser Vorgang kann einige Minuten dauern.";
		_AUCT['GuiReloaduiButton'] = "Neu laden";
		_AUCT['GuiReloaduiFeedback'] = "WoW-Benutzeroberfl\195\164che wird neu geladen";
		
		_AUCT['GuiRedo'] = "Zeige Warnung bei langer Scan-Dauer";
		_AUCT['GuiDefaultAllButton'] = "Zur\195\188cksetzen";
		_AUCT['GuiDefaultAll'] = "Alle Einstellungen zur\195\188cksetzen";
		_AUCT['GuiDefaultAllHelp'] = "Hier klicken um alle Auctioneer-Optionen auf ihren Standardwert zu setzen.\nWARNUNG: Dieser Vorgang kann NICHT r\195\188ckg\195\164ngig gemacht werden.";
		_AUCT['GuiDefaultOption'] = "Zur\195\188cksetzen folgender Einstellung";
		_AUCT['GuiPrintin'] = "Fenster f\195\188r Meldungen ausw\195\164hlen";
		_AUCT['GuiProtectWindow'] = "Schlie\195\159en des AH-Fensters verhindern";
		_AUCT['GuiAuctionDuration'] = "Standard-Auktionsdauer";
		
		_AUCT['GuiAuctionHouseHeader'] = "Auktionshaus-Fenster";
		_AUCT['GuiAuctionHouseHeaderHelp'] = "\195\132ndert das Verhalten des Auktionshaus-Fensters";
		_AUCT['GuiLoad'] = "Auctioneer automatisch laden";
		_AUCT['GuiLoad_Never'] = 'nie';
		_AUCT['GuiLoad_Always'] = 'immer';
		_AUCT['GuiLoad_AuctionHouse'] = 'im Auktionshaus';
	end

-- Locale strings for the esES locale
	if locale == "esES" then
		-- Encoded in UTF8
		
		
		_AUCT['TimeShort'] = "Corto";
		_AUCT['TimeMed'] = "Mediano";
		_AUCT['TimeLong'] = "Largo";
		_AUCT['TimeVlong'] = "Muy Largo";
		
		_AUCT['FrmtWelcome'] = "Auctioneer versi\195\179n %s cargado";
		
		_AUCT['FrmtBrokerHeader'] = "Ganancia Minima: %s, PMV = 'Precio Maximo de Venta'";
		_AUCT['FrmtBrokerLine'] = "%s, Ultimo(s) %s visto(s), PMV: %s, BO: %s, Prof: %s";
		_AUCT['FrmtBrokerDone'] = "Corredor finalizado";
		_AUCT['FrmtBidbrokerHeader'] = "Ganancia Minima: %s, PMV = 'Precio Maximo de Venta'";
		_AUCT['FrmtBidbrokerMinbid'] = "OfertaMinima"
		_AUCT['FrmtBidbrokerCurbid'] = "OfertaCorriente"
		_AUCT['FrmtBidbrokerLine'] = "%s, Ultimo(s) %s visto(s), PMV: %s, %s: %s, Ganancia: %s, Tiempo: %s";
		_AUCT['FrmtBidbrokerDone'] = "Corredor de ofertas finalizado";
		_AUCT['FrmtPctlessHeader'] = "Porcentaje bajo el Precio Maximo de Venta (PMV): %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, Ultimo(s) %d visto(s), PMV: %s, OC: %s, Ganancia: %s, menos %s";
		_AUCT['FrmtPctlessDone'] = "Porcentajes menores finalizado.";
		_AUCT['FrmtCompeteHeader'] = "Subastas compitiendo por al menos %s debajo por art\195\173culo.";
		_AUCT['FrmtCompeteLine'] = "%s, Oferta: %s, OC %s vs %s, %s menos";
		_AUCT['FrmtCompeteDone'] = "Subastas compitiendo finalizado.";
		_AUCT['FrmtNoauct'] = "No se hallaron subastas para el art\195\173culo: %s";
		_AUCT['FrmtMedianLine'] = "De los \195\186ltimos(s) %d vistos, OC mediano por 1 %s es: %s";
		_AUCT['FrmtLowLine'] = "%s, BO: %s, Vendedor: %s, Por uno: %s, Menos que el mediano: %s";
		_AUCT['FrmtHspLine'] = "Precio Maximo de Venta por uno %s es: %s";
		
		_AUCT['FrmtInfoSeen'] = "Visto un total de %d veces en subasta";
		_AUCT['FrmtInfoForone'] = "Por 1: %s min/%s OC (%s oferta) [en %d's]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s OC (%s oferta)"
		_AUCT['FrmtInfoHistmed'] = "\195\154ltimo(s) %d, OC mediano (c/u)";
		_AUCT['FrmtInfoSnapmed'] = "Explorados %d, OC mediano (c/u)";
		_AUCT['FrmtInfoSgststx'] = "Precio sugerido para su lote de %d: %s min/%s OC";
		_AUCT['FrmtInfoSgst'] = "Precio sugerido: %s min/%s OC";
		
		_AUCT['FrmtInfoBidrate'] = "%d%% tienen ofertas, %d%% tienen OC";
		_AUCT['FrmtInfoNever'] = "Nunca visto en %s";
		_AUCT['FrmtInfoAlsoseen'] = "Visto %d veces en %s";
		
		_AUCT['FrmtInfoHeadMulti'] = "Promedios para %d art\195\173culos:";
		_AUCT['FrmtInfoMinMulti'] = "  Oferta a empezar (%s c/u)";
		_AUCT['FrmtInfoBidMulti'] = "  Oferta (%s%s c/u)";
		_AUCT['FrmtInfoBuyMulti'] = "  Opci\195\179n a compra(%s%s c/u)";
		
		_AUCT['FrmtInfoHeadOne'] = "Promedios para este art\195\173culo:";
		_AUCT['FrmtInfoMinOne'] = "  Oferta a empezar";
		_AUCT['FrmtInfoBidOne'] = " %s con propuestas";
		_AUCT['FrmtInfoBuyOne'] = " %s con opci\195\179n a compra";
		
		_AUCT['FrmtInfoBuymedian'] = "  Opci\195\179n a compra mediano";
		
		_AUCT['FrmtInfoStacksize'] = "  Tama\195\177o promedio del paquete: %d art\195\173culos";
		
		_AUCT['FrmtUnknownLocale'] = "La localizaci\195\179n que usted especifico ('%s') no es valida. Locales v\195\161lidos son:"; 
		_AUCT['FrmtUnknownRf']     = "Parametro inv\195\161lido ('%s'). El par\195\161metro debe de estar en la forma de: [reino]-[facci\195\179n]. Por ejemplo: Al'Akir-Horde";
		_AUCT['FrmtUnknownArg']    = "'%s' no es un argumento valido de '%s'";
		
		_AUCT['FrmtActRemove'] = "Eliminando firma %s de la imagen actual de la casa de subastas.";
		
		_AUCT['FrmtAuctinfoHist'] = "%d Hist\195\179ricamente";
		_AUCT['FrmtAuctinfoSnap'] = "%d en la \195\186ltima exploraci\195\179n";
		_AUCT['FrmtAuctinfoLow'] = "M\195\173nimo de la \195\186ltima exploraci\195\179n";
		_AUCT['FrmtAuctinfoNolow'] = "Art\195\173culo no fue visto en ultima imagen";
		_AUCT['FrmtAuctinfoOrig'] = "Oferta Original";
		_AUCT['FrmtAuctinfoSugbuy'] = "Opci\195\179n a compra sugerida";
		_AUCT['FrmtAuctinfoSugbid'] = "Oferta sugerida";
		_AUCT['FrmtAuctinfoMktprice'] = "Precio del mercado";
		
		_AUCT['FrmtWarnMarkup'] = "Superando vendedor por %s%%";
		_AUCT['FrmtWarnUndercut'] = "Socavando por %s%%";
		_AUCT['FrmtWarnNocomp'] = "Sin competencia";
		_AUCT['FrmtWarnAbovemkt'] = "Competencia sobre mercado";
		_AUCT['FrmtWarnToolow'] = "Imposible igualar minimo";
		_AUCT['FrmtWarnMyprice'] = "Usando mi precio actual";
		_AUCT['FrmtWarnNodata'] = "Sin informaci\195\179n para PMV";
		_AUCT['FrmtWarnUser'] = "Usando precio de usuario";
		
		_AUCT['CmdOff'] = "apagado";
		_AUCT['CmdOn'] = "prendido";
		_AUCT['CmdAlt'] = "alt";
		_AUCT['CmdCtrl'] = "ctrl";
		_AUCT['CmdShift'] = "shift";
		_AUCT['CmdToggle'] = "invertir";
		_AUCT['CmdDisable'] = "deshabilitar";
		_AUCT['CmdClear'] = "borrar";
		_AUCT['CmdClearAll'] = "todo";
		_AUCT['CmdClearSnapshot'] = "imagen";
		_AUCT['CmdAlso'] = "tambien";
		_AUCT['CmdAlsoOpposite'] = "opuesta";
		_AUCT['CmdLocale'] = "localidad";
		_AUCT['CmdDefault'] = "original";
		_AUCT['CmdPrintin'] = "imprimir-en";
		_AUCT['CmdAuctionClick'] = "auction-click";
		
		_AUCT['CmdBroker'] = "corredor";
		_AUCT['CmdBidbroker'] = "corredorofertas";
		_AUCT['CmdBidbrokerShort'] = "co";
		_AUCT['CmdEmbed'] = "integrado";
		_AUCT['CmdPercentless'] = "porcientomenos";
		_AUCT['CmdPercentlessShort'] = "pm";
		_AUCT['CmdCompete'] = "competir";
		_AUCT['CmdScan'] = "explorar";
		_AUCT['CmdAutofill'] = "autoinsertar";
		
		_AUCT['CmdProtectWindow'] = "protejer-ventana"
		_AUCT['CmdProtectWindow0'] = "nunca"
		_AUCT['CmdProtectWindow1'] = "explorar"
		_AUCT['CmdProtectWindow2'] = "siempre"
		_AUCT['CmdAuctionDuration'] = "duracion-subasta"
		_AUCT['CmdAuctionDuration0'] = "ultima"
		_AUCT['CmdAuctionDuration1'] = "2h"
		_AUCT['CmdAuctionDuration2'] = "8h"
		_AUCT['CmdAuctionDuration3'] = "24h"
		
		_AUCT['CmdPctBidmarkdown'] = "pct-menosoferta";
		_AUCT['CmdPctMarkup']      = "pct-mas";
		_AUCT['CmdPctMaxless']     = "pct-sinmaximo";
		_AUCT['CmdPctNocomp']      = "pct-sincomp";
		_AUCT['CmdPctUnderlow']    = "pct-bajomenor";
		_AUCT['CmdPctUndermkt']    = "pct-bajomercado";
		
		_AUCT['OptClear'] = "([Art\195\173culo]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
		_AUCT['OptAlso'] = "(reino-facci\195\179n|".._AUCT['CmdAlsoOpposite']..")"
		_AUCT['OptLocale'] = "<localidad>";
		_AUCT['OptBroker'] = "<ganancia_plata>";
		_AUCT['OptBidbroker'] = "<ganancia_plata>";
		_AUCT['OptPercentless'] = "<porciento>";
		_AUCT['OptCompete'] = "<plata_menos>";
		_AUCT['OptScan'] = "";
		_AUCT['OptScale'] = "<escala>";
		_AUCT['OptScaleDefault'] = 1.0;
		_AUCT['OptDefault'] = "(<opci\195\179n>|".._AUCT['CmdClearAll']..")";
		_AUCT['OptPrintin'] = "(<indiceVentana>[N\195\186mero]|<nombreVentana>[Serie])";
		_AUCT['OptProtectWindow'] = "(".._AUCT['CmdProtectWindow0'].."||".._AUCT['CmdProtectWindow1'].."||".._AUCT['CmdProtectWindow2']..")";
		_AUCT['OptAuctionDuration'] = "(".._AUCT['CmdAuctionDuration0'].."||".._AUCT['CmdAuctionDuration1'].."||".._AUCT['CmdAuctionDuration2'].."||".._AUCT['CmdAuctionDuration3']..")";
		
		_AUCT['OptPctBidmarkdown'] = "<porciento>";
		_AUCT['OptPctMarkup'] = "<porciento>";
		_AUCT['OptPctMaxless'] = "<porciento>";
		_AUCT['OptPctNocomp'] = "<porciento>";
		_AUCT['OptPctUnderlow'] = "<porciento>";
		_AUCT['OptPctUndermkt'] = "<porciento>";
		
		_AUCT['ShowVerbose'] = "ver-literal";
		_AUCT['ShowAverage'] = "ver-promedio";
		_AUCT['ShowLink'] = "ver-enlace";
		_AUCT['ShowMedian'] = "ver-mediano";
		_AUCT['ShowStats'] = "ver-estadisticas";
		_AUCT['ShowSuggest'] = "ver-sugerencia";
		_AUCT['ShowEmbedBlank'] = "ver-integrado-lineavacia";
		_AUCT['ShowRedo'] = "ver-advertencia";
		
		_AUCT['HelpOnoff'] = "Enciende o apaga la informacion sobre las subastas";
		_AUCT['HelpDisable'] = "Impide que Auctioneer se carge automaticamente la proxima vez que usted entre al juego";
		_AUCT['HelpVerbose'] = "Selecciona para mostrar promedios literales (O apaga para que aparezcan en una sola linea)";
		_AUCT['HelpAverage'] = "Selecciona para mostrar precio promedio de la subasta para el art\195\173culo";
		_AUCT['HelpLink'] = "Selecciona para mostrar el numero de enlace del art\195\173culo en la caja de ayuda";
		_AUCT['HelpMedian'] = "Selecciona para mostrar el precio promedio para la opci\195\179n a compra";
		_AUCT['HelpSuggest'] = "Selecciona para mostrar el precio sugerido de subasta para el art\195\173culo";
		_AUCT['HelpStats'] = "Selecciona para mostrar porcentajes para ofertas/opci\195\179n a compra del art\195\173culo";
		_AUCT['HelpEmbedBlank'] = "Selecciona para mostrar una linea en blanco entre informacion de la caja de ayuda y la informacion de subasta cuando el modo integrado esta seleccionado";
		_AUCT['HelpClear'] = "Eliminar la informacion existente sobre el art\195\173culo(se debe usar shift-click para insertar el/los articulo(s) en el comando) Tambien se pueden especificar las palabras claves \"todo\" or \"imagen\"";
		
		_AUCT['HelpAlso'] = "Mostrar tambi\195\169n los valores de otros servidores en la caja de ayuda. Para el reino escribe el nombre del reino y para facci\195\179n escribe el nombre de la facci\195\179n. Por ejemplo: \"/auctioneer tambien Al'Akir-Horde\". La palabra clave \"opuesta\" significa facci\195\179n opuesta, \"apagar\" desabilita la funci\195\179n.";
		_AUCT['HelpLocale'] = "Cambiar la localidad que Auctioneer usa para sus mensajes";
		_AUCT['HelpBroker'] = "Muestra las subastas de la exploraci\195\179n mas reciente en las cuales se puede poner una oferta para luego revenderlas para ganancia";
		_AUCT['HelpBidbroker'] = "Muestra subastas de corto o medio termino de la exploraci\195\179n mas reciente a las cuales se puede poner una oferta y obtener ganancia";
		_AUCT['HelpEmbed'] = "Insertar el texto en la caja de ayuda original del juego (nota: algunas capacidades se desabilitan cuando esta opci\195\179n es seleccionada)";
		_AUCT['HelpPercentless'] = "Muestra cualquier subasta recientemente explorada en la que la compra de participaciones es un porcentaje menor del precio de venta mas alto.";
		_AUCT['HelpCompete'] = "Muestra cualquier subasta explorada recientemente cuya opci\195\179n a compra es menor que alguno de tus art\195\173culos";
		_AUCT['HelpScan'] = "Realiza una exploracion de la casa de subastas en la proxima visita, o mientras este alli (tambien existe un bot\195\179n en el panel de la casa de subastas). Seleccione alli las categorias a explorar.";
		_AUCT['HelpAutofill'] = "Auto-completar precios cuando se a\195\177adan art\195\173culos a subastar en el panel de la casa de subastas";
		
		_AUCT['HelpPctBidmarkdown'] = "Ajusta el porcentaje del precio de compra por debajo del cual Auctioneer marcara las ofertas";
		_AUCT['HelpPctMarkup'] = "El porcentaje que sera incrementado el precio de venta del vendedor cuando no existan otros valores disponibles.";
		_AUCT['HelpPctMaxless'] = "Ajusta el maximo porcentaje por debajo del valor de mercado que Auctioneer tratara de igualar antes de darse por vencido.";
		_AUCT['HelpPctNocomp'] = "El porcentaje bajo el precio del mercado que Auctioneer usar\195\161 cuando no hay competencia";
		_AUCT['HelpPctUnderlow'] = "Ajusta el porcentaje bajo el menor precio m\195\173nimo de subasta que Auctioneer aplicar\195\161";
		_AUCT['HelpPctUndermkt'] = "Porcentaje a usar cuando sea imposible vencer a la competencia (debido al sinmaximo)";
		_AUCT['HelpRedo'] = "Selecciona para mostrat una advertencia cuando la p\195\161gina corriente en la casa de subastas ha tomado demasiado tiempo para explorar debido a problemas con el servidor.";
		_AUCT['HelpDefault'] = "Revertir una opci\195\179n de Auctioneer a su configuraci\195\179n de f\195\161brica. Tambi\195\169n puede especificar la palabra clave \"todo\" pata revertir todas las opciones de Auctioneer a sus configuraciones de f\195\161brica."
		_AUCT['HelpPrintin'] = "Selecciona cual ventana de mensajes va a usar Auctioneer para imprimir su informacion. Puede especificar el nombre o el \195\173ndice de la ventana.";
		_AUCT['HelpAuctionClick'] = "Allows you to Alt-Click an item in your bag to automatically start an auction for it";
		_AUCT['HelpProtectWindow'] = "Previene que usted cierre accidentalmente el interf\195\161z de la Casa de Subastas";
		_AUCT['HelpAuctionDuration'] = "Fijar la duraci\195\179n de las subastas al abrir el interf\195\161z de la Casa de Subastas";
		_AUCT['HelpLoad'] = "Cambiar las opciones de carga de Auctioneer para este personaje";
		
		_AUCT['DisableMsg'] = "Deshabilitando la auto-carga de Auctioneer";
		
		_AUCT['StatOn'] = "Mostrando la configuracion corriente para la informacion de subastas";
		_AUCT['StatOff'] = "Ocultando toda informaci\195\179n de subastas";
		
		_AUCT['FrmtActClearall'] = "Eliminando toda la informaci\195\179n de subastas para %s";
		_AUCT['FrmtActClearsnap'] = "Eliminando la imagen actual de la casa de subastas.";
		_AUCT['FrmtActClearOk'] = "Informacion eliminada para el art\195\173culo: %s";
		_AUCT['FrmtActClearFail'] = "Imposible encontrar art\195\173culo: %s";
		_AUCT['FrmtActEnable'] = "Mostrando informacion del art\195\173culo: %s ";
		_AUCT['FrmtActDisable'] = "Ocultando informacion de articulo: %s ";
		_AUCT['FrmtActEnabledOn'] = "Mostrando %s de los art\195\173culos usando %s";
		_AUCT['FrmtActSet'] = "%s ajustado(a) a '%s'";
		_AUCT['FrmtActUnknown'] = "Comando o palabra clave desconocida: '%s'";
		_AUCT['FrmtActDefaultall'] = "Todas las opciones de Auctioneer han sido revertidas a sus configuraciones de f\195\161brica.";
		_AUCT['FrmtActDefault'] = "La opci\195\179n %s de Auctioneer ha sido revertida a su configuraci\195\179n de f\195\161brica.";
		_AUCT['FrmtPrintin'] = "Los mensajes de Auctioneer se imprimir\195\161n en la ventana de comunicaci\195\179n \"%s\"";
		_AUCT['FrmtAutostart'] = "Comenzando subasta automaticamente por %s m\195\173nimo, %s opci\195\179n a compra (%dh)"
		_AUCT['FrmtProtectWindow'] = "Protecci\195\179n de la ventana de la Casa de Subastas fijado a: %s";
		_AUCT['FrmtAuctionDuration'] = "Duraci\195\179n de las subastas fijado a: %s";
		
		_AUCT['TextScan'] = "Explorar";
		_AUCT['TextAuction'] = "Subasta";
		_AUCT['TextNone'] = "ningun";
		_AUCT['TextUsage'] = "Uso:";
		
		_AUCT['TextGeneral'] = _AUCT['TextGeneral'];
		_AUCT['TextCombat'] = _AUCT['TextCombat'];
		
		-- AH Scanning localizations
		
		_AUCT['AuctionScanStart'] = "Auctioneer: Explorando \"%s\" p\195\161gina 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: Explorando \"%s\" p\195\161gina %d de %d\nSubastas por segundo: %s\nTiempo estimado para completar: %s";
		_AUCT['AuctionScanDone'] = "Auctioneer: La exploraci\195\179n de las subastas ha finalizado";
		_AUCT['AuctionScanNexttime'] = "Auctioneer ejecutara una exploracion de las subastas la proxima vez que usted hable con un subastador.";
		_AUCT['AuctionScanNocat'] = "Usted debe tener al menos una categoria seleccionada para poder explorar.";
		_AUCT['AuctionScanRedo'] = "La p\195\161gina corriente ha tomado mas de %d segundos para completar. Tratando p\195\161gina otra vez.";
		
		_AUCT['MesgConvert'] = "Conversi\195\179n de base de datos de Auctioneer. Favor de hacer una copia del SavedVariables\\Auctioneer.lua para la reserva primero.%s%s";
		_AUCT['MesgNotconverting'] = "Auctioneer no convertir\195\161 su base de datos, pero no funcionar\195\161 hasta que la base de datos sea convertida.";
		_AUCT['MesgConvertYes'] = "Convertir";
		_AUCT['MesgConvertNo'] = "Deshabilitar Auctioneer";
		
		_AUCT['MesgNotLoaded'] = "Auctioneer no esta cargado. Escriba /auctioneer para mas informaci\195\179n.";
		
		_AUCT['AuctionTotalAucts'] = "Total de subastas exploradas: %s";
		_AUCT['AuctionNewAucts'] = "Nuevas subastas exploradas: %s";
		_AUCT['AuctionOldAucts'] = "Subastas exploradas previamente: %s";
		_AUCT['AuctionDefunctAucts'] = "Subastas viejas removidas: %s";
		_AUCT['AuctionDiscrepancies'] = "Discrepancias: %s";
		
		-- GUI localizations
		
		_AUCT['GuiRememberText'] = "Recordar precio";
		_AUCT['GuiNoWorldMap'] = "Auctioneer: suprimi\195\179 la exhibici\195\179n del mapa del mundo"
		
		_AUCT['GuiMainHelp'] = "Contiene ajustes para Auctioneer \nun aditamento que muestra informacion sobre art\195\173culos y analiza informaci\195\179n de subastas. \nSeleccione \"Explorar\" en la casa de subastas para coleccionar informacion sobre las subastas.";
		_AUCT['GuiMainEnable'] = "Encender Auctioneer";
		_AUCT['GuiLocale'] = "Ajustar localidad a";
		_AUCT['GuiVerbose'] = "Modo literal";
		_AUCT['GuiStatsEnable'] = "Ver estad\195\173sticas";
		
		_AUCT['GuiStatsHeader'] = "Estad\195\173sticas de precios de art\195\173culos";
		_AUCT['GuiStatsHelp'] = "Mostrar las siguientes estad\195\173sticas en la caja de ayuda.";
		_AUCT['GuiAverages'] = "Mostrar Promedios";
		_AUCT['GuiMedian'] = "Mostrar Medianos";
		_AUCT['GuiSuggest'] = "Mostrar Precios Sugeridos";
		
		_AUCT['GuiEmbedHeader'] = "Integraci\195\179n";
		_AUCT['GuiEmbed'] = "Integrar informaci\195\179n en la caja de ayuda";
		_AUCT['GuiEmbedBlankline'] = "Mostrar linea en blanco.";
		
		_AUCT['GuiClearHeader'] = "Eliminar Informaci\195\179n";
		_AUCT['GuiClearHelp'] = "Elimina la informacion de Auctioneer. \nSelecciona si eliminar toda la informaci\195\179n o solamente la im\195\161gen corriente.\nADVERTENCIA: Estas acciones NO son reversibles.";
		_AUCT['GuiClearall'] = "Eliminar toda la informaci\195\179n";
		_AUCT['GuiClearallHelp'] = "Seleccione aqui para eliminar toda la informaci\195\179n de Auctioneer para el reino-facci\195\179n corriente.";
		_AUCT['GuiClearallNote'] = "el reino-facci\195\179n corriente.";
		_AUCT['GuiClearallButton'] = "Eliminar Todo";
		_AUCT['GuiClearsnap'] = "Eliminar imagen corriente";
		_AUCT['GuiClearsnapHelp'] = "Presione aqui para eliminar la ultima imagen de informacion de Auctioneer.";
		_AUCT['GuiClearsnapButton'] = "Eliminar Imagen";
		
		_AUCT['GuiPercentsHeader'] = "Limites de Porcentajes de Auctioneer";
		_AUCT['GuiPercentsHelp'] = "ADVERTENCIA: Las siguientes opciones son para usuarios expertos SOLAMENTE.\nAjuste los siguientes valores para cambiar cuan agresivo es Auctioneer al determinar niveles provechosos.";
		_AUCT['GuiBidmarkdown'] = "Porciento menos oferta";
		_AUCT['GuiMarkup'] = "Porciento sobre vendedor";
		_AUCT['GuiMaxless'] = "Porciento m\195\161ximo bajo mercado";
		_AUCT['GuiNocomp'] = "Porciento sin competencia.";
		_AUCT['GuiUnderlow'] = "Porciento bajo menor subasta";
		_AUCT['GuiUndermkt'] = "Porciento bajo mercado";
		
		_AUCT['GuiOtherHeader'] = "Otras Opciones";
		_AUCT['GuiOtherHelp'] = "Opciones miscel\195\161neas de Auctioneer";
		_AUCT['GuiAutofill'] = "Autocompletar precios en la casa de subastas";
		_AUCT['GuiAlso'] = "Tambi\195\169n mostrar valores para";
		_AUCT['GuiAlsoOpposite'] = "Mostrando informaci\195\179n para la facci\195\179n opuesta.";
		_AUCT['GuiAlsoOff'] = "No mostrando informaci\195\179n para otro reino-facci\195\179n";
		_AUCT['GuiAlsoDisplay'] = "Mostrando informaci\195\179n para %s";
		_AUCT['GuiLink'] = "Ver numero de enlace";
		_AUCT['GuiReloadui'] = "Recargar Interf\195\161z";
		_AUCT['GuiReloaduiHelp'] = "Presione aqui para recargar el interf\195\161z de WoW luego de haber seleccionado una localidad diferente. Esto es para que el lenguaje de configuraci\195\179n sea el mismo que el de Auctioneer.\nNota: Esta operaci\195\179n puede tomar unos minutos.";
		_AUCT['GuiReloaduiButton'] = "Recargar";
		_AUCT['GuiReloaduiFeedback'] = "Recargando el Interf\195\161z de WoW";
		
		_AUCT['GuiRedo'] = "Mostrar Advertencia de Exploraci\195\179n";
		_AUCT['GuiDefaultAllButton'] = "Revertir Todo";
		_AUCT['GuiDefaultAll'] = "Revertir todas las opciones";
		_AUCT['GuiDefaultAllHelp'] = "Seleccione aqui para revertir todas las opciones de Auctioneer a sus configuraciones de f\195\161brica.\nADVERTENCIA: Esta acci\195\179n NO es reversible.";
		_AUCT['GuiDefaultOption'] = "Revertir esta opci\195\179n";
		_AUCT['GuiPrintin'] = "Seleccione la ventana deseada";
		_AUCT['GuiProtectWindow'] = "Prevenir el cierre de la ventana de la CDS";
		_AUCT['GuiAuctionDuration'] = "Duraci\195\179n de las subastas";
		
		_AUCT['GuiAuctionHouseHeader'] = "Ventana de la Casa de Subastas";
		_AUCT['GuiAuctionHouseHeaderHelp'] = "Modificar el comportamiento de la ventana de la Casa de Subastas";
		_AUCT['GuiLoad'] = "Cargar Auctioneer auctomaticamente";
		_AUCT['GuiLoad_Never'] = 'nunca';
		_AUCT['GuiLoad_Always'] = 'siempre';
		_AUCT['GuiLoad_AuctionHouse'] = 'en la Casa de Subastas';
	end

-- Locale strings for the frFR locale
	if locale == "frFR" then
		-- Encoded in UTF8
		
		_AUCT['FrmtBrokerHeader'] = "Profit Minimum: %s, HSP = 'Prix de vente maximum', AI = 'Achat Imm\195\169diat'";
		_AUCT['FrmtBrokerLine'] = "%s, Derniers %s vus, HSP: %s, AI: %s, Prof: %s";
		_AUCT['FrmtBrokerDone'] = "Brokering termin\195\169";
		_AUCT['FrmtBidbrokerHeader'] = "Profit minimum: %s, HSP = 'Prix de vente maximum'";
		_AUCT['FrmtBidbrokerMinbid'] = "EnchMin"
		_AUCT['FrmtBidbrokerCurbid'] = "EnchAct"
		_AUCT['FrmtBidbrokerLine'] = "%s, Derniers %s vus, HSP: %s, %s: %s, Prof: %s, Temps: %s";
		_AUCT['FrmtBidbrokerDone'] = "Bid brokering termin\195\169";
		_AUCT['FrmtPctlessHeader'] = "Percentage inf\195\169rieur au HSP: %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, Derniers %d vus, HSP: %s, AI: %s, Prof: %s, Moins %s";
		_AUCT['FrmtPctlessDone'] = "Percentage inf\195\169rieur termin\195\169.";
		_AUCT['FrmtCompeteHeader'] = "Encheres comp\195\169titives au moins %s de moins par objet.";
		_AUCT['FrmtCompeteLine'] = "%s, Ench: %s, BO %s vs %s, %s de moins";
		_AUCT['FrmtCompeteDone'] = "Ench\195\168res comp\195\169titives termin\195\169es.";
		_AUCT['FrmtNoauct'] = "Pas d'ench\195\168re trouv\195\169e pour l'objet: %s";
		_AUCT['FrmtMedianLine'] = "Des derniers %d vus, l'achat moyen pour 1 %s est de: %s";
		_AUCT['FrmtLowLine'] = "%s, BO: %s, Vendeur: %s, L'unit\195\169: %s, Moins de la moyenne: %s";
		_AUCT['FrmtHspLine'] = "Prix de vente maximum pour un %s est de: %s";
		_AUCT['FrmtInfoSeen'] = "Vu %d fois aux ench\195\168res";
		_AUCT['FrmtInfoForone'] = "Pour 1: %s min/%s achat (%s ench\195\168re) [par %d]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s achat (%s ench\195\168re)"
		_AUCT['FrmtInfoHistmed'] = "Derniers %d vus, achat moyen:";
		_AUCT['FrmtInfoSnapmed'] = "Vu %d fois au dernier scan, achat moyen:";
		_AUCT['FrmtInfoBidrate'] = "%d%% avec ench\195\168re, %d%% avec achat imm\195\169diat";
		_AUCT['FrmtInfoNever'] = "Jamais vu aux ench\195\168res";
		_AUCT['FrmtInfoAlsoseen'] = "Vu %d fois aux %s";
		
		-- AH Scanning localizations
		_AUCT['AuctionScanStart'] = "Auctioneer: Scan de la cat\195\169gorie '%s': page 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: Scan de la cat\195\169gorie '%s': page %d sur %d";
		_AUCT['AuctionScanDone'] = "Auctioneer: Scan termin\195\169";
		_AUCT['AuctionScanNexttime'] = "Auctioneer fera un scan complet de la maison des ventes la prochaine fois que vous parlerez \195\160 un commisaire-priseur.";
		

	end

end

Auctioneer_SetLocaleStrings(GetLocale());

