#!/usr/bin/perl

open OUT, "> localization.lua";
print OUT << 'EOD';
--[[
	$Id$
	Version: <%version%>

	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.

	You may find the source versions of this file at the
	project webpage, in the SVN repository.
	Please visit the homepage for more information.
		http://enchantrix.org/trac

	$Id$
	Version: <%version%>
]]

EOD

for $i (1..5) { print OUT "\n"; }
for $i (1..6) {
	print OUT "-- ============= AUTOMATICALLY GENERATED FILE =============\n";
	print OUT "-- ================= DON'T EDIT THIS FILE =================\n\n";
}
for $i (1..5) { print OUT "\n"; }


for $file (<locales/*.utf8>) {
	$file =~ /locales.([^.]+).utf8/;
	$locale = $1;
	if ($locale ne "enUS") {
		push(@locales, $locale);
	}
}

print OUT "-- Default locale strings are defined in English\n";
open(DATA, "< locales/enUS.utf8");
while (<DATA>) {
	s/\xEF\xBB\xBF//;
	s/[\r\n]+/\n/g;
	s/([\200-\377])/sprintf("\\%d",ord($1))/eg;
	s/\-\-.*$//;
	if (/^(\w+)\s*=/) {
		$defined{$1} = 1;
	}
	if ($_ ne "") {
		print OUT "$_";
	}
}
close DATA;

print OUT "\n";

for $locale (@locales) {
	%localized = ();
	print OUT "-- Locale strings for the $locale locale\n";
	print OUT "if GetLocale() == \"$locale\" then\n";
	open(DATA, "< locales/$locale.utf8");
	while (<DATA>) {
		s/\xEF\xBB\xBF//;
		s/[\r\n]+/\n/g;
		s/([\200-\377])/sprintf("\\%d",ord($1))/eg;
		if (s/^(\w+)\s*=\s*/$1=/) {
			$localized{$1} = 1;
		}
		print OUT "$_";
	}
	close DATA;
	print OUT "\n";

	$missing = 0;
	for $defined (sort(keys(%defined))) {
		unless ($localized{$defined}) {
			unless ($missing) {
				print OUT "\n-- The following definitions are missing in this locale:\n";
				$missing = 1;
			}
			print OUT"--\t$defined = \"\";\n";
		}
	}
	
	print OUT "end\n\n";
}

