--[[
	$Id$
	Version: <%version%>

	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.

	You may find the source versions of this file at the
	project webpage, in the SVN repository.
	Please visit the homepage for more information.
		http://enchantrix.org/trac

	$Id$
	Version: <%version%>
]]






-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================






ENCH_VALID_LOCALES = {["daDK"] = true, ["deDE"] = true, ["enUS"] = true, ["esES"] = true, ["frFR"] = true};

function Enchantrix_SetLocaleStrings(locale)
	-- Default locale strings are defined in English
	
	
	
	
	ENCH_FRMT_WELCOME = "Enchantrix v%s loaded";
	ENCH_FRMT_CREDIT = "  (go to http://enchantrix.org/ to share your data)";
	
	ENCH_ARG_SPELLNAME = "Disenchant";
	
	ENCH_CMD_OFF = "off";
	ENCH_CMD_ON = "on";
	ENCH_CMD_TOGGLE = "toggle";
	ENCH_CMD_DISABLE = "disable";
	ENCH_CMD_CLEAR = "clear";
	ENCH_CMD_CLEAR_ALL = "all";
	ENCH_CMD_LOCALE = "locale";
	ENCH_CMD_DEFAULT = "default";
	ENCH_CMD_PRINTIN = "print-in";
	
	ENCH_CMD_FIND_BUYAUCT = "percentless";
	ENCH_CMD_FIND_BIDAUCT = "bidbroker";
	
	ENCH_CMD_FIND_BUYAUCT_SHORT = "pl";
	ENCH_CMD_FIND_BIDAUCT_SHORT = "bb";
	
	ENCH_OPT_CLEAR = "([Item]|"..ENCH_CMD_CLEAR_ALL..")";
	ENCH_OPT_LOCALE = "<locale>";
	ENCH_OPT_FIND_BUYAUCT = "<percent>";
	ENCH_OPT_FIND_BIDAUCT = "<silver>";
	ENCH_OPT_DEFAULT = "(<option>|"..ENCH_CMD_CLEAR_ALL..")";
	ENCH_OPT_PRINTIN = "(<frameIndex>[Number]|<frameName>[String])";
	
	ENCH_SHOW_EMBED = "embed";
	ENCH_SHOW_HEADER = "header";
	ENCH_SHOW_COUNT = "counts";
	ENCH_SHOW_RATE = "rates";
	ENCH_SHOW_VALUE = "valuate";
	ENCH_SHOW_GUESS_AUCTIONEER_HSP = "valuate-hsp";
	ENCH_SHOW_GUESS_AUCTIONEER_MED = "valuate-median";
	ENCH_SHOW_GUESS_BASELINE = "valuate-baseline";
	
	ENCH_HELP_ONOFF = "Turns the enchant data display on and off";
	ENCH_HELP_DISABLE = "Stops enchantrix from automatically loading next time you log in";
	ENCH_HELP_EMBED = "Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
	ENCH_HELP_HEADER = "Select whether to show the header line";
	ENCH_HELP_COUNT = "Select whether to show the exact counts in the database";
	ENCH_HELP_RATE = "Select whether to show the average quantity of disenchant";
	
	ENCH_HELP_VALUE = "Select whether to show item's estimated values based on the proportions of possible disenchants";
	ENCH_HELP_GUESS_AUCTIONEER_HSP = "If valuation is enabled, and you have Auctioneer installed, display the sellable price (HSP) valuation of disenchanting the item.";
	ENCH_HELP_GUESS_AUCTIONEER_MEDIAN = "If valuation is enabled, and you have Auctioneer installed, display the median based valuation of disenchanting the item.";
	ENCH_HELP_GUESS_NOAUCTIONEER = "The "..ENCH_SHOW_GUESS_AUCTIONEER_HSP.." and "..ENCH_SHOW_GUESS_AUCTIONEER_MED.." commands are not available because you do not have auctioneer installed";
	ENCH_HELP_GUESS_BASELINE = "If valuation is enabled, (Auctioneer not needed) display the baseline valuation of disenchanting the item, based upon the inbuilt prices.";
	
	ENCH_HELP_CLEAR = "Clear the specified item's data (you must shift click insert the item(s) into the command) You may also specify the special keyword \"all\"";
	ENCH_HELP_LOCALE = "Change the locale that is used to display Enchantrix messages";
	ENCH_HELP_FIND_BUYAUCT = "Find auctions whose possible disenchant value is a certain percent less than the buyout price";
	ENCH_HELP_FIND_BIDAUCT = "Find auctions whose possible disenchant value is a certain silver amount less than the bid price";
	ENCH_HELP_DEFAULT = "Set an Enchantrix option to it's default value. You may also specify the special keyword \"all\" to set all Enchantrix options to their default values."
	ENCH_HELP_PRINTIN = "Select which frame Enchantix will print out it's messages. You can either specify the frame's name or the frame's index.";
	
	ENCH_MESG_NOTLOADED = "Enchantrix is not loaded. Type /enchantrix for more info.";
	ENCH_MESG_DISABLE = "Disabling automatic loading of Enchantrix";
	
	ENCH_STAT_ON = "Displaying configured enchant data";
	ENCH_STAT_OFF = "Not displaying any enchant data";
	
	ENCH_FRMT_ACT_CLEARALL = "Clearing all enchant data";
	ENCH_FRMT_ACT_CLEAR_OK = "Cleared data for item: %s";
	ENCH_FRMT_ACT_CLEAR_FAIL = "Unable to find item: %s";
	ENCH_FRMT_ACT_ENABLE = "Displaying item's %s data";
	ENCH_FRMT_ACT_DISABLE = "Not displaying item's %s data";
	ENCH_FRMT_ACT_ENABLED_ON = "Displaying item's %s on %s";
	ENCH_FRMT_ACT_SET = "Set %s to '%s'";
	
	ENCH_FRMT_ACT_UNKNOWN = "Unknown command keyword: '%s'";
	ENCH_FRMT_ACT_UNKNOWN_LOCALE = "The locale you specified ('%s') is unknown. Valid locales are:";
	ENCH_FRMT_ACT_DEFAULT_ALL= "All Enchantrix options have been reset to default settings.";
	ENCH_FRMT_ACT_DEFAULT = "Enchantrix's %s option has been reset to its default setting";
	
	
	ENCH_FRMT_DISINTO = "Disenchants into:";
	ENCH_FRMT_FOUND = "Found that %s disenchants into:";
	ENCH_FRMT_USAGE = "Usage:";
	
	ENCH_FRMT_COUNTS = "    (base=%d, old=%d, new=%d)";
	ENCH_FRMT_VALUE_AUCT_HSP = "Disenchant value (HSP)";
	ENCH_FRMT_VALUE_AUCT_MED = "Disenchant value (Median)";
	ENCH_FRMT_VALUE_MARKET = "Disenchant value (Baseline)";
	
	ENCH_FRMT_BIDBROKER_HEADER = "Bids having %s silver savings on average disenchant value:";
	ENCH_FRMT_BIDBROKER_MINBID = "minBid"
	ENCH_FRMT_BIDBROKER_CURBID = "curBid"
	ENCH_FRMT_BIDBROKER_LINE = "%s, Valued at: %s, %s: %s, Save: %s, Less %s, Time: %s";
	ENCH_FRMT_BIDBROKER_DONE = "Bid brokering done";
	
	ENCH_FRMT_PCTLESS_HEADER = "Buyouts having %d%% savings over average item disenchant value:";
	ENCH_FRMT_PCTLESS_LINE = "%s, Valued at: %s, BO: %s, Save: %s, Less %s";
	ENCH_FRMT_PCTLESS_DONE = "Percent less done.";
	ENCH_FRMT_PRINTIN = "Encantrix's messages will now print on the \"%s\" chat frame";
	
	ENCH_TEXT_GENERAL = "General";
	ENCH_TEXT_COMBAT = "Combat";
	
	
	
	ENCH_GUI_MAIN_HELP = "Contains settings for Enchantrix \nan AddOn that displays information in item tooltips pertaining to the results of disenchanting said item.";
	ENCH_GUI_MAIN_ENABLE = "Enable Enchantrix";
	ENCH_GUI_LOCALE = "Set locale to";
	ENCH_GUI_RELOADUI_BUTTON = "ReloadUI";
	ENCH_GUI_RELOADUI = "Reload User Interface";
	ENCH_GUI_RELOADUI_HELP = "Click here to reload the WoW User Interface after changing the locale so that the language in this configuration screen matches the one you selected.\nNote: This operation may take a few minutes.";
	ENCH_GUI_RELOADUI_FEEDBACK = "Now Reloading the WoW UI";
	ENCH_GUI_EMBED = "Embed info in in-game tooltip";
	ENCH_GUI_COUNT = "Show the exact counts in the database"
	ENCH_GUI_RATE = "Show the average quantity of disenchant";
	ENCH_GUI_VALUATE_HEADER = "Valuation";
	ENCH_GUI_VALUATE_ENABLE = "Enable Valuation";
	ENCH_GUI_VALUATE_AVERAGES = "Valuate with Auctioneer Averages";
	ENCH_GUI_VALUATE_MEDIAN = "Valuate with Auctioneer Medians";
	ENCH_GUI_VALUATE_BASELINE = "Valuate with Built-in Data";
	ENCH_GUI_OTHER_HEADER = "Other Options";
	ENCH_GUI_OTHER_HELP = "Miscellaneous Enchantrix Options";
	ENCH_GUI_CLEARALL_BUTTON = "Clear All";
	ENCH_GUI_CLEARALL = "Clear All Enchantrix Data";
	ENCH_GUI_CLEARALL_HELP = "Click here to clear all of Enchantrix data for the current server-realm.";
	ENCH_GUI_CLEARALL_NOTE = "for the current server-faction";
	ENCH_GUI_DEFAULT_ALL_BUTTON = "Reset All";
	ENCH_GUI_DEFAULT_ALL = "Reset All Enchantrix Options";
	ENCH_GUI_DEFAULT_ALL_HELP= "Click here to set all Enchantrix options to their default values.\nWARNING: This action is NOT undoable.";
	ENCH_GUI_DEFAULT_OPTION = "Reset this setting";
	ENCH_GUI_PRINTIN = "Select the desired message frame";
	
	
	
	EssenceItemIDs = {};
	EssenceItemIDs["Greater Astral Essence"] = 11082;
	EssenceItemIDs["Greater Eternal Essence"] = 16203;
	EssenceItemIDs["Greater Magic Essence"] = 10939;
	EssenceItemIDs["Greater Mystic Essence"] = 11135;
	EssenceItemIDs["Greater Nether Essence"] = 11175;
	EssenceItemIDs["Lesser Astral Essence"] = 10998;
	EssenceItemIDs["Lesser Eternal Essence"] = 16202;
	EssenceItemIDs["Lesser Magic Essence"] = 10938;
	EssenceItemIDs["Lesser Mystic Essence"] = 11134;
	EssenceItemIDs["Lesser Nether Essence"] = 11174;
	EssenceItemIDs["Large Brilliant Shard"] = 14344;
	EssenceItemIDs["Large Glimmering Shard"] = 11084;
	EssenceItemIDs["Large Glowing Shard"] = 11139;
	EssenceItemIDs["Large Radiant Shard"] = 11178;
	EssenceItemIDs["Small Brilliant Shard"] = 14343;
	EssenceItemIDs["Small Glimmering Shard"] = 10978;
	EssenceItemIDs["Small Glowing Shard"] = 11138;
	EssenceItemIDs["Small Radiant Shard"] = 11177;
	EssenceItemIDs["Dream Dust"] = 11176;
	EssenceItemIDs["Illusion Dust"] = 16204;
	EssenceItemIDs["Soul Dust"] = 11083;
	EssenceItemIDs["Strange Dust"] = 10940;
	EssenceItemIDs["Vision Dust"] = 11137;



	-- Locale strings for the daDK locale
	if locale == "daDK" then
		-- Encoded in UTF8
		-- English localization for Enchantrix
		
		
		ENCH_FRMT_WELCOME="Enchantrix v%s loaded";
		ENCH_FRMT_CREDIT="  (go to http://enchantrix.org/ to share your data)";
		
		ENCH_ARG_SPELLNAME="Disenchant";
		
		ENCH_CMD_OFF="off";
		ENCH_CMD_ON="on";
		ENCH_CMD_TOGGLE="toggle";
		ENCH_CMD_DISABLE="disable";
		ENCH_CMD_CLEAR="clear";
		ENCH_CMD_CLEAR_ALL="all";
		ENCH_CMD_LOCALE="locale";
		ENCH_CMD_DEFAULT="default";
		ENCH_CMD_PRINTIN="print-in";
		
		ENCH_CMD_FIND_BUYAUCT="percentless";
		ENCH_CMD_FIND_BIDAUCT="bidbroker";
		
		ENCH_CMD_FIND_BUYAUCT_SHORT="pl";
		ENCH_CMD_FIND_BIDAUCT_SHORT="bb";
		
		ENCH_OPT_CLEAR="([Item]|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_LOCALE="<locale>";
		ENCH_OPT_FIND_BUYAUCT="<percent>";
		ENCH_OPT_FIND_BIDAUCT="<silver>";
		ENCH_OPT_DEFAULT="(<option>|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_PRINTIN="(<frameIndex>[Number]|<frameName>[String])";
		
		ENCH_SHOW_EMBED="embed";
		ENCH_SHOW_HEADER="header";
		ENCH_SHOW_COUNT="counts";
		ENCH_SHOW_RATE="rates";
		ENCH_SHOW_VALUE="valuate";
		ENCH_SHOW_GUESS_AUCTIONEER_HSP="valuate-hsp";
		ENCH_SHOW_GUESS_AUCTIONEER_MED="valuate-median";
		ENCH_SHOW_GUESS_BASELINE="valuate-baseline";
		
		ENCH_HELP_ONOFF="Turns the enchant data display on and off";
		ENCH_HELP_DISABLE="Stops enchantrix from automatically loading next time you log in";
		ENCH_HELP_EMBED="Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
		ENCH_HELP_HEADER="Select whether to show the header line";
		ENCH_HELP_COUNT="Select whether to show the exact counts in the database";
		ENCH_HELP_RATE="Select whether to show the average quantity of disenchant";
		
		ENCH_HELP_VALUE="Select whether to show item's estimated values based on the proportions of possible disenchants";
		ENCH_HELP_GUESS_AUCTIONEER_HSP="If valuation is enabled, and you have Auctioneer installed, display the sellable price (HSP) valuation of disenchanting the item.";
		ENCH_HELP_GUESS_AUCTIONEER_MEDIAN="If valuation is enabled, and you have Auctioneer installed, display the median based valuation of disenchanting the item.";
		ENCH_HELP_GUESS_NOAUCTIONEER="The "..ENCH_SHOW_GUESS_AUCTIONEER_HSP.." and "..ENCH_SHOW_GUESS_AUCTIONEER_MED.." commands are not available because you do not have auctioneer installed";
		ENCH_HELP_GUESS_BASELINE="If valuation is enabled, (Auctioneer not needed) display the baseline valuation of disenchanting the item, based upon the inbuilt prices.";
		
		ENCH_HELP_CLEAR="Clear the specified item's data (you must shift click insert the item(s) into the command) You may also specify the special keyword \"all\"";
		ENCH_HELP_LOCALE="Change the locale that is used to display Enchantrix messages";
		ENCH_HELP_FIND_BUYAUCT="Find auctions whose possible disenchant value is a certain percent less than the buyout price";
		ENCH_HELP_FIND_BIDAUCT="Find auctions whose possible disenchant value is a certain silver amount less than the bid price";
		ENCH_HELP_DEFAULT="Set an Enchantrix option to it's default value. You may also specify the special keyword \"all\" to set all Enchantrix options to their default values."
		ENCH_HELP_PRINTIN="Select which frame Enchantix will print out it's messages. You can either specify the frame's name or the frame's index.";
		
		ENCH_MESG_NOTLOADED="Enchantrix is not loaded. Type /enchantrix for more info.";
		
		ENCH_STAT_ON="Displaying configured enchant data";
		ENCH_STAT_OFF="Not displaying any enchant data";
		
		ENCH_FRMT_ACT_CLEARALL="Clearing all enchant data";
		ENCH_FRMT_ACT_CLEAR_OK="Cleared data for item: %s";
		ENCH_FRMT_ACT_CLEAR_FAIL="Unable to find item: %s";
		ENCH_FRMT_ACT_ENABLE="Displaying item's %s data";
		ENCH_FRMT_ACT_DISABLE="Not displaying item's %s data";
		ENCH_FRMT_ACT_ENABLED_ON="Displaying item's %s on %s";
		ENCH_FRMT_ACT_SET="Set %s to '%s'";
		
		ENCH_FRMT_ACT_UNKNOWN="Unknown command keyword: '%s'";
		ENCH_FRMT_ACT_UNKNOWN_LOCALE="The locale you specified ('%s') is unknown. Valid locales are:";
		ENCH_FRMT_ACT_DEFAULT_ALL="All Enchantrix options have been reset to default settings.";
		ENCH_FRMT_ACT_DEFAULT="Enchantrix's %s option has been reset to its default setting";
		
		ENCH_FRMT_DISINTO="Disenchants into:";
		ENCH_FRMT_FOUND="Found that %s disenchants into:";
		ENCH_FRMT_USAGE="Usage:";
		
		ENCH_FRMT_COUNTS="    (base=%d, old=%d, new=%d)";
		ENCH_FRMT_VALUE_AUCT_HSP="Disenchant value (HSP)";
		ENCH_FRMT_VALUE_AUCT_MED="Disenchant value (Median)";
		ENCH_FRMT_VALUE_MARKET="Disenchant value (Baseline)";
		
		ENCH_FRMT_BIDBROKER_HEADER="Bids having %s silver savings on average disenchant value:";
		ENCH_FRMT_BIDBROKER_MINBID="minBid"
		ENCH_FRMT_BIDBROKER_CURBID="curBid"
		ENCH_FRMT_BIDBROKER_LINE="%s, Valued at: %s, %s: %s, Save: %s, Less %s, Time: %s";
		ENCH_FRMT_BIDBROKER_DONE="Bid brokering done";
		
		ENCH_FRMT_PCTLESS_HEADER="Buyouts having %d%% savings over average item disenchant value:";
		ENCH_FRMT_PCTLESS_LINE="%s, Valued at: %s, BO: %s, Save: %s, Less %s";
		ENCH_FRMT_PCTLESS_DONE="Percent less done.";
		ENCH_FRMT_PRINTIN="Encantrix's messages will now print on the \"%s\" chat frame";
		
		--GUI localizations
		
		ENCH_GUI_MAIN_HELP="Contains settings for Enchantrix \nan AddOn that displays information in item tooltips pertaining to the results of disenchanting said item.";
		ENCH_GUI_MAIN_ENABLE="Enable Enchantrix";
		ENCH_GUI_LOCALE="Set locale to";
		ENCH_GUI_RELOADUI_BUTTON="ReloadUI";
		ENCH_GUI_RELOADUI="Reload User Interface";
		ENCH_GUI_RELOADUI_HELP="Click here to reload the WoW User Interface after changing the locale so that the language in this configuration screen matches the one you selected.\nNote: This operation may take a few minutes.";
		ENCH_GUI_RELOADUI_FEEDBACK="Now Reloading the WoW UI";
		ENCH_GUI_EMBED="Embed info in in-game tooltip";
		ENCH_GUI_VALUATE_HEADER="Valuation";
		ENCH_GUI_VALUATE_ENABLE="Enable Valuation";
		ENCH_GUI_VALUATE_AVERAGES="Valuate with Auctioneer Averages";
		ENCH_GUI_VALUATE_MEDIAN="Valuate with Auctioneer Medians";
		ENCH_GUI_VALUATE_BASELINE="Valuate with Built-in Data";
		ENCH_GUI_OTHER_HEADER="Other Options";
		ENCH_GUI_OTHER_HELP="Miscellaneous Enchantrix Options";
		ENCH_GUI_CLEARALL_BUTTON="Clear All";
		ENCH_GUI_CLEARALL="Clear All Enchantrix Data";
		ENCH_GUI_CLEARALL_HELP="Click here to clear all of Enchantrix data for the current server-realm.";
		ENCH_GUI_CLEARALL_NOTE="for the current server-faction";
		ENCH_GUI_DEFAULT_ALL_BUTTON="Reset All";
		ENCH_GUI_DEFAULT_ALL="Reset All Enchantrix Options";
		ENCH_GUI_DEFAULT_ALL_HELP="Click here to set all Enchantrix options to their default values.\nWARNING: This action is NOT undoable.";
		ENCH_GUI_DEFAULT_OPTION="Reset this setting";
		ENCH_GUI_PRINTIN="Select the desired message frame";
		
		--ID Numbers
		
		EssenceItemIDs={};
		EssenceItemIDs["Greater Astral Essence"] = 11082;
		EssenceItemIDs["Greater Eternal Essence"] = 16203;
		EssenceItemIDs["Greater Magic Essence"] = 10939;
		EssenceItemIDs["Greater Mystic Essence"] = 11135;
		EssenceItemIDs["Greater Nether Essence"] = 11175;
		EssenceItemIDs["Lesser Astral Essence"] = 10998;
		EssenceItemIDs["Lesser Eternal Essence"] = 16202;
		EssenceItemIDs["Lesser Magic Essence"] = 10938;
		EssenceItemIDs["Lesser Mystic Essence"] = 11134;
		EssenceItemIDs["Lesser Nether Essence"] = 11174;
		EssenceItemIDs["Large Brilliant Shard"] = 14344;
		EssenceItemIDs["Large Glimmering Shard"] = 11084;
		EssenceItemIDs["Large Glowing Shard"] = 11139;
		EssenceItemIDs["Large Radiant Shard"] = 11178;
		EssenceItemIDs["Small Brilliant Shard"] = 14343;
		EssenceItemIDs["Small Glimmering Shard"] = 10978;
		EssenceItemIDs["Small Glowing Shard"] = 11138;
		EssenceItemIDs["Small Radiant Shard"] = 11177;
		EssenceItemIDs["Dream Dust"] = 11176;
		EssenceItemIDs["Illusion Dust"] = 16204;
		EssenceItemIDs["Soul Dust"] = 11083;
		EssenceItemIDs["Strange Dust"] = 10940;
		EssenceItemIDs["Vision Dust"] = 11137;


		-- The following definitions are missing in this locale:
		--	ENCH_GUI_COUNT = "";
		--	ENCH_GUI_RATE = "";
		--	ENCH_MESG_DISABLE = "";
		--	ENCH_TEXT_COMBAT = "";
		--	ENCH_TEXT_GENERAL = "";

	end



	-- Locale strings for the deDE locale
	if locale == "deDE" then
		-- Encoded in UTF8
		-- German localization for Enchantrix by FtKxDE
		
		
		ENCH_FRMT_WELCOME="Enchantrix v%s geladen";
		ENCH_FRMT_CREDIT=" (besuche http://enchantrix.org/ um deine Daten zur Verf\195\188gung zu stellen)";
		
		ENCH_ARG_SPELLNAME="Entzaubern";
		
		ENCH_CMD_OFF="off";
		ENCH_CMD_ON="on";
		ENCH_CMD_TOGGLE="toggle";
		ENCH_CMD_DISABLE="disable";
		ENCH_CMD_CLEAR="clear";
		ENCH_CMD_CLEAR_ALL="all";
		ENCH_CMD_LOCALE="locale";
		ENCH_CMD_DEFAULT="default";
		ENCH_CMD_PRINTIN="print-in";
		
		ENCH_CMD_FIND_BUYAUCT="percentless";
		ENCH_CMD_FIND_BIDAUCT="bidbroker";
		
		ENCH_CMD_FIND_BUYAUCT_SHORT="pl";
		ENCH_CMD_FIND_BIDAUCT_SHORT="bb";
		
		ENCH_OPT_CLEAR="([Gegenstand]|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_LOCALE="<Gebietsschema>";
		ENCH_OPT_FIND_BUYAUCT="<Prozent>";
		ENCH_OPT_FIND_BIDAUCT="<Silber>";
		ENCH_OPT_DEFAULT="(<Option>|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_PRINTIN="(<Index>[Nummer]|<Name>[Zeichenfolge])";
		
		ENCH_SHOW_EMBED="embed";
		ENCH_SHOW_HEADER="header";
		ENCH_SHOW_COUNT="counts";
		ENCH_SHOW_RATE="rates";
		ENCH_SHOW_VALUE="valuate";
		ENCH_SHOW_GUESS_AUCTIONEER_HSP="valuate-hsp";
		ENCH_SHOW_GUESS_AUCTIONEER_MED="valuate-median";
		ENCH_SHOW_GUESS_BASELINE="valuate-baseline";
		
		ENCH_HELP_ONOFF="Schaltet die Anzeige von Entzauberungsdaten ein oder aus";
		ENCH_HELP_DISABLE="Verhindert das automatische Laden von Enchantrix beim Login";
		ENCH_HELP_EMBED="Zeige den Text im In-Game Tooltip \n(Hinweis: Einige Funktionen stehen dann nicht zur Verf\195\188gung)";
		ENCH_HELP_HEADER="Ausw\195\164hlen ob die Kopfzeile angezeigt werden soll";
		ENCH_HELP_COUNT="Ausw\195\164hlen ob die genaue Anzahl der Entzauberungen aus der Datenbank angezeigt wird";
		ENCH_HELP_RATE="Ausw\195\164hlen ob die durchschnittliche Anzahl der Entzauberungen angezeigt wird";
		
		ENCH_HELP_VALUE="Ausw\195\164hlen ob gesch\195\164tzte Verkaufspreise aufgrund \nder Anteile an m\195\182glichen Entzauberungen angezeigt werden";
		ENCH_HELP_GUESS_AUCTIONEER_HSP="Wenn die Wertsch\195\164tzung aktiviert und Auctioneer installiert ist, zeige den maximalen Verkaufspreis (Auctioneer-HSP) f\195\188r das Entzaubern";
		ENCH_HELP_GUESS_AUCTIONEER_MEDIAN="Wenn die Wertsch\195\164tzung aktiviert und Auctioneer installiert ist, zeige den durchschnittlichen Verkaufspreis (Auctioneer-MEDIAN) f\195\188r das Entzaubern";
		ENCH_HELP_GUESS_NOAUCTIONEER="Die Befehle \""..ENCH_SHOW_GUESS_AUCTIONEER_HSP.."\" und \""..ENCH_SHOW_GUESS_AUCTIONEER_MED.."\" sind nicht verf\195\188gbar weil Auctioneer nicht installiert ist";
		ENCH_HELP_GUESS_BASELINE="Wenn die Wertsch\195\164tzung aktiviert ist, zeige den \195\188blichen Verkaufspreis aus der internen Preisliste (Auctioneer wird nicht ben\195\182tigt)";
		
		ENCH_HELP_CLEAR="L\195\182sche die Daten des angegebenen Gegenstands (Gegenst\195\164nde m\195\188ssen mit Shift-Klick einf\195\188gt werden). Mit dem Schl\195\188sselwort \""..ENCH_CMD_CLEAR_ALL.."\" werden alle Daten gel\195\182scht.";
		ENCH_HELP_LOCALE="\195\132ndern des Gebietsschemas das zur Anzeige \nvon Enchantrix-Meldungen verwendet wird";
		ENCH_HELP_FIND_BUYAUCT="Suche Auktionen deren Entzauberungswert einen bestimmten Prozentsatz unter dem Sofortkaufpreis liegt";
		ENCH_HELP_FIND_BIDAUCT="Suche Auktionen deren Entzauberungswert einen bestimmten Betrag (in Silber) unter dem Gebotspreis liegt";
		ENCH_HELP_DEFAULT="Setzt die angegebene Enchantrix-Option auf ihren Standardwert zur\195\188ck. Mit dem Schl\195\188sselwort \""..ENCH_CMD_CLEAR_ALL.."\" werden alle Enchantrix-Optionen zur\195\188ckgesetzt."
		ENCH_HELP_PRINTIN="Ausw\195\164hlen in welchem Fenster die Enchantrix-Meldungen angezeigt werden. Es kann entweder der Fensterindex oder der Fenstername angegeben werden.";
		
		ENCH_MESG_NOTLOADED="Enchantrix ist nicht geladen. Geben Sie /enchantrix ein um mehr Informationen zu erhalten.";
		ENCH_MESG_DISABLE="Das automatische Laden von Enchantrix wird deaktiviert";
		
		ENCH_STAT_ON="Die Anzeige von Entzauberungsdaten wurde aktiviert";
		ENCH_STAT_OFF="Die Anzeige von Entzauberungsdaten wurde deaktiviert";
		
		ENCH_FRMT_ACT_CLEARALL="L\195\182sche alle Entzauberungsdaten";
		ENCH_FRMT_ACT_CLEAR_OK="Daten f\195\188r Gegenstand %s gel\195\182scht";
		ENCH_FRMT_ACT_CLEAR_FAIL="Kann Gegenstand %s nicht finden";
		ENCH_FRMT_ACT_ENABLE="Zeige Daten von Gegenstand %s";
		ENCH_FRMT_ACT_DISABLE="Zeige keine Daten von Gegenstand %s";
		ENCH_FRMT_ACT_ENABLED_ON="Zeige Gegenstand %s auf %s";
		ENCH_FRMT_ACT_SET="Setze %s zu '%s'";
		
		ENCH_FRMT_ACT_UNKNOWN="Unbekannter Befehl: '%s'";
		ENCH_FRMT_ACT_UNKNOWN_LOCALE="Das angegebene Gebietsschema ('%s') ist unbekannt. G\195\188ltige Gebietsschemen sind:";
		ENCH_FRMT_ACT_DEFAULT_ALL="Alle Enchantrix-Optionen wurden auf die Standardwerte zur\195\188ckgesetzt.";
		ENCH_FRMT_ACT_DEFAULT="Die Enchantrix-Option '%s' wurde auf den Standardwert zur\195\188ckgesetzt.";
		
		
		ENCH_FRMT_DISINTO="M\195\182gliche Entzauberung zu:";
		ENCH_FRMT_FOUND="%s wird entzaubert zu:";
		ENCH_FRMT_USAGE="Verwendung:";
		
		ENCH_FRMT_COUNTS=" (Basis=%d, Alt=%d, Neu=%d)";
		ENCH_FRMT_VALUE_AUCT_HSP="Entzauberungswert (Maximum)";
		ENCH_FRMT_VALUE_AUCT_MED="Entzauberungswert (Durchschnitt)";
		ENCH_FRMT_VALUE_MARKET="Entzauberungswert (Built-In)";
		
		ENCH_FRMT_BIDBROKER_HEADER="Auktionen mit %s Silber Einsparung auf den durchschnittlichen Entzauberungswert:";
		ENCH_FRMT_BIDBROKER_MINBID="minGeb"
		ENCH_FRMT_BIDBROKER_CURBID="aktGeb"
		ENCH_FRMT_BIDBROKER_LINE="%s, Wert bei: %s, %s: %s, Ersparnis: %s, %s weniger, Zeit: %s";
		ENCH_FRMT_BIDBROKER_DONE="Die Auktionssuche (Betrag unter Gebotspreis) ist abgeschlossen.";
		
		ENCH_FRMT_PCTLESS_HEADER="Auktionen mit %d%% Einsparung auf durchschnittlichen Entzauberungswert:";
		ENCH_FRMT_PCTLESS_LINE="%s, Wert bei: %s, SK: %s, Ersparnis: %s, %s weniger";
		ENCH_FRMT_PCTLESS_DONE="Die Auktionssuche (Prozent unter Sofortkauf) ist abgeschlossen.";
		ENCH_FRMT_PRINTIN="Die Enchantrix-Meldungen werden nun im Chat-Fenster \"%s\" angezeigt";
		
		ENCH_TEXT_GENERAL="Allgemein";
		ENCH_TEXT_COMBAT="Kampflog";
		
		
		
		ENCH_GUI_MAIN_HELP="Einstellungen f\195\188r Enchantrix, einem AddOn das Informationen \195\188ber die m\195\182glichen Entzauberungen eines Gegenstands in Tooltips anzeigt.";
		ENCH_GUI_MAIN_ENABLE="Enchantrix aktivieren";
		ENCH_GUI_LOCALE="Setze das Gebietsschema auf";
		ENCH_GUI_RELOADUI_BUTTON="Neu laden";
		ENCH_GUI_RELOADUI="Benutzeroberfl\195\164che neu laden";
		ENCH_GUI_RELOADUI_HELP="Hier klicken um die WoW-Benutzeroberfl\195\164che nach einer \n\195\132nderung des Gebietsschemas neu zu laden, und dadurch \ndie Sprache des Konfigurationsmen\195\188s diesem entspricht.\nHinweis: Dieser Vorgang kann einige Minuten dauern.";
		ENCH_GUI_RELOADUI_FEEDBACK="WoW-Benutzeroberfl\195\164che wird neu geladen";
		ENCH_GUI_EMBED="In-Game Tooltip zur Anzeige verwenden";
		ENCH_GUI_COUNT="Zeige die genaue Anzahl aus der Datenbank"
		ENCH_GUI_RATE="Zeige die durchschnittliche Anzahl der Entzauberungen";
		ENCH_GUI_VALUATE_HEADER="Wertsch\195\164tzung";
		ENCH_GUI_VALUATE_ENABLE="Wertsch\195\164tzung aktivieren";
		ENCH_GUI_VALUATE_AVERAGES="H\195\182chstm\195\182glichen Verkaufspreis anzeigen (Auctioneer)";
		ENCH_GUI_VALUATE_MEDIAN="Durchschnittlichen Verkaufspreis anzeigen (Auctioneer)";
		ENCH_GUI_VALUATE_BASELINE="\195\156blichen Verkaufspreis anzeigen (Built-In Preisliste)";
		ENCH_GUI_OTHER_HEADER="Sonstige Optionen";
		ENCH_GUI_OTHER_HELP="Sonstige Enchantrix-Optionen";
		ENCH_GUI_CLEARALL_BUTTON="Alles l\195\182schen";
		ENCH_GUI_CLEARALL="Alle Enchantrix-Daten l\195\182schen";
		ENCH_GUI_CLEARALL_HELP="Hier klicken um alle Enchantrix-Daten auf dem aktuellen Realm zu l\195\182schen.";
		ENCH_GUI_CLEARALL_NOTE="der aktuellen Fraktion auf dem aktuellen Realm";
		ENCH_GUI_DEFAULT_ALL_BUTTON="Zur\195\188cksetzen";
		ENCH_GUI_DEFAULT_ALL="Alle Einstellungen zur\195\188cksetzen";
		ENCH_GUI_DEFAULT_ALL_HELP="Hier klicken um alle Enchantrix-Optionen auf ihren Standardwert zu setzen.\nWARNUNG: Dieser Vorgang kann NICHT r\195\188ckg\195\164ngig gemacht werden.";
		ENCH_GUI_DEFAULT_OPTION="Zur\195\188cksetzen folgender Einstellung";
		ENCH_GUI_PRINTIN="Gew\195\188nschtes Fenster f\195\188r Meldungen ausw\195\164hlen";
		
		
		
		EssenceItemIDs={};
		EssenceItemIDs["Gro\195\159e Astralessenz"] = 11082;
		EssenceItemIDs["Gro\195\159e ewige Essenz"] = 16203;
		EssenceItemIDs["Gro\195\159e Magie-Essenz"] = 10939;
		EssenceItemIDs["Gro\195\159e Mystikeressenz"] = 11135;
		EssenceItemIDs["Gro\195\159e Nether-Essenz"] = 11175;
		EssenceItemIDs["Geringe Astralessenz"] = 10998;
		EssenceItemIDs["Geringe ewige Essenz"] = 16202;
		EssenceItemIDs["Geringe Magie-Essenz"] = 10938;
		EssenceItemIDs["Geringe Mystikeressenz"] = 11134;
		EssenceItemIDs["Geringe Nether-Essenz"] = 11174;
		EssenceItemIDs["Gro\195\159er gl\195\164nzender Splitter"] = 14344;
		EssenceItemIDs["Gro\195\159er glei\195\159ender Splitter"] = 11084;
		EssenceItemIDs["Gro\195\159er leuchtender Splitter"] = 11139;
		EssenceItemIDs["Gro\195\159er strahlender Splitter"] = 11178;
		EssenceItemIDs["Kleiner gl\195\164nzender Splitter"] = 14343;
		EssenceItemIDs["Kleiner glei\195\159ender Splitter"] = 10978;
		EssenceItemIDs["Kleiner leuchtender Splitter"] = 11138;
		EssenceItemIDs["Kleiner strahlender Splitter"] = 11177;
		EssenceItemIDs["Traumstaub"] = 11176;
		EssenceItemIDs["Illusionsstaub"] = 16204;
		EssenceItemIDs["Seelenstaub"] = 11083;
		EssenceItemIDs["Seltsamer Staub"] = 10940;
		EssenceItemIDs["Visionenstaub"] = 11137;

	end



	-- Locale strings for the esES locale
	if locale == "esES" then
		-- Encoded in UTF8
		-- English localization for Enchantrix
		
		
		ENCH_FRMT_WELCOME="Enchantrix versi\195\179n %s cargado";
		ENCH_FRMT_CREDIT="  (vaya a http://enchantrix.org/ para compart\195\173r su data)";
		
		ENCH_ARG_SPELLNAME=ENCH_ARG_SPELLNAME; --Since there is currently no Spanish WoW client, changing this value to a localized version would essentially break Enchantrix.
		
		ENCH_CMD_OFF="apagado";
		ENCH_CMD_ON="prendido";
		ENCH_CMD_TOGGLE="invertir";
		ENCH_CMD_DISABLE="deshabilitar";
		ENCH_CMD_CLEAR="borrar";
		ENCH_CMD_CLEAR_ALL="todo";
		ENCH_CMD_LOCALE="localidad";
		ENCH_CMD_DEFAULT="original";
		ENCH_CMD_PRINTIN="imprimir-en";
		
		ENCH_CMD_FIND_BUYAUCT="porcientomenos";
		ENCH_CMD_FIND_BIDAUCT="corredorofertas";
		
		ENCH_CMD_FIND_BUYAUCT_SHORT="pm";
		ENCH_CMD_FIND_BIDAUCT_SHORT="co";
		
		ENCH_OPT_CLEAR="([Item]|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_LOCALE="<localidad>";
		ENCH_OPT_FIND_BUYAUCT="<percent>";
		ENCH_OPT_FIND_BIDAUCT="<silver>";
		ENCH_OPT_DEFAULT="(<opci\195\179n>|"..ENCH_CMD_CLEAR_ALL..")";
		ENCH_OPT_PRINTIN="(<indiceVentana>[N\195\186mero]|<nombreVentana>[Serie])";
		
		ENCH_SHOW_EMBED="integrar";
		ENCH_SHOW_HEADER="titulo";
		ENCH_SHOW_COUNT="conteo";
		ENCH_SHOW_RATE="razones";
		ENCH_SHOW_VALUE="valorizar";
		ENCH_SHOW_GUESS_AUCTIONEER_HSP="valorizar-pmv";
		ENCH_SHOW_GUESS_AUCTIONEER_MED="valorizar-mediano";
		ENCH_SHOW_GUESS_BASELINE="valorizar-referencia";
		
		ENCH_HELP_ONOFF="Enciende o apaga la informaci\195\179n de encantos";
		ENCH_HELP_DISABLE="Impide que Enchantrix se carge automaticamente la proxima vez que usted entre al juego";
		ENCH_HELP_EMBED="Insertar el texto en la caja de ayuda original del juego (nota: Algunas capacidades se desabilitan cuando esta opci\195\179n es seleccionada)";
		ENCH_HELP_HEADER="Selecciona para mostrar la l\195\173nea del t\195\173tulo";
		ENCH_HELP_COUNT="Selecciona para mostrar los valores exactos de la base de datos";
		ENCH_HELP_RATE="Selecciona para mostrar las cantidades promedio de los desencantamientos";
		
		ENCH_HELP_VALUE="Selecciona para mostrar el precio estimado de los art\195\173culos basandose en la proporci\195\179n de los desencantamientos posibles";
		ENCH_HELP_GUESS_AUCTIONEER_HSP="Si la valorizaci\195\179n esta seleccionada, y usted tiene Auctioneer instalado, mostrar la valorizaci\195\179n de los desencantamientos del art\195\173culo basandose en los precios m\195\161ximos de venta (PMV) de Auctioneer.";
		ENCH_HELP_GUESS_AUCTIONEER_MEDIAN="Si la valorizaci\195\179n esta seleccionada, y usted tiene Auctioneer instalado, mostrar la valorizaci\195\179n de los desencantamientos del art\195\173culo basandose en los precios medianos de Auctioneer.";
		ENCH_HELP_GUESS_NOAUCTIONEER="Los comandos "..ENCH_SHOW_GUESS_AUCTIONEER_HSP.." y "..ENCH_SHOW_GUESS_AUCTIONEER_MED.." no estan disponibles porque usted no tiene Auctioneer instalado";
		ENCH_HELP_GUESS_BASELINE="Si la valorizaci\195\179n esta seleccionada, (Auctioneer no es necesario) mostrar la valorizaci\195\179n de los desencantamientos del art\195\173culo, basandose en los valores de referencia incluidos.";
		
		ENCH_HELP_CLEAR="Eliminar la informacion existente sobre el art\195\173culo(se debe usar shift-click para insertar el/los articulo(s) en el comando) Tambien se pueden especificar las palabra clave \"todo\"";
		ENCH_HELP_LOCALE="Cambiar la localidad que Enchantrix usa para sus mensajes";
		ENCH_HELP_FIND_BUYAUCT="Encontrar subastas donde el valor posible de los desencantamientos es un cierto porciento menos que el precio de la opci\195\179n a compra";
		ENCH_HELP_FIND_BIDAUCT="Encontrar subastas donde el valor posible de los desencantamientos es una cierta cantidad de plata menos que el precio de oferta";
		ENCH_HELP_DEFAULT="Revertir una opci\195\179n de Enchantrix a su configuraci\195\179n de f\195\161brica. Tambi\195\169n puede especificar la palabra clave \"todo\" pata revertir todas las opciones de Enchantrix a sus configuraciones de f\195\161brica."
		ENCH_HELP_PRINTIN="Selecciona cual ventana de mensajes va a usar Enchantrix para imprimir su informacion. Puede especificar el nombre o el \195\173ndice de la ventana.";
		
		ENCH_MESG_NOTLOADED="Enchantrix no esta cargado. Escriba /enchantrix para mas informaci\195\179n.";
		
		ENCH_STAT_ON="Mostrando la configuracion corriente para la informacion de los desencantamientos";
		ENCH_STAT_OFF="Ocultando toda informaci\195\179n de los desencantamientos";
		
		ENCH_FRMT_ACT_CLEARALL="Eliminando toda informaci\195\179n de desencantamientos";
		ENCH_FRMT_ACT_CLEAR_OK="Informacion eliminada para el art\195\173culo: %s";
		ENCH_FRMT_ACT_CLEAR_FAIL="Imposible encontrar art\195\173culo: %s";
		ENCH_FRMT_ACT_ENABLE="Mostrando informacion del art\195\173culo: %s ";
		ENCH_FRMT_ACT_DISABLE="Ocultando informacion de articulo: %s ";
		ENCH_FRMT_ACT_ENABLED_ON="Mostrando %s de los art\195\173culos usando %s";
		ENCH_FRMT_ACT_SET="%s ajustado(a) a '%s'";
		
		ENCH_FRMT_ACT_UNKNOWN="Comando o palabra clave desconocida: '%s'";
		ENCH_FRMT_ACT_UNKNOWN_LOCALE="La localizaci\195\179n que usted especifico ('%s') no es valida. Locales v\195\161lidos son:";
		ENCH_FRMT_ACT_DEFAULT_ALL="Todas las opciones de Enchantrix han sido revertidas a sus configuraciones de f\195\161brica.";
		ENCH_FRMT_ACT_DEFAULT="La opci\195\179n %s de Enchantrix ha sido revertida a su configuraci\195\179n de f\195\161brica.";
		
		ENCH_FRMT_DISINTO="Se convierte en:";
		ENCH_FRMT_FOUND="Se encontro que %s se convierte en:";
		ENCH_FRMT_USAGE="Uso:";
		
		ENCH_FRMT_COUNTS="    (referencia=%d, viejo=%d, nuevo=%d)";
		ENCH_FRMT_VALUE_AUCT_HSP="Valor de desencantamientos (PMV)";
		ENCH_FRMT_VALUE_AUCT_MED="Valor de desencantamientos (Mediano)";
		ENCH_FRMT_VALUE_MARKET="Valor de desencantamientos (Referencia)";
		
		ENCH_FRMT_BIDBROKER_HEADER="Ofertas teniendo promedios de ahorros de %s plata en el valor de los desencantamientos:";
		ENCH_FRMT_BIDBROKER_MINBID="ofertaMin"
		ENCH_FRMT_BIDBROKER_CURBID="ofertaCorr"
		ENCH_FRMT_BIDBROKER_LINE="%s, Valorado en: %s, %s: %s, Ahorra: %s, Menos %s, Tiempo: %s";
		ENCH_FRMT_BIDBROKER_DONE="Corredor de ofertas finalizado";
		
		ENCH_FRMT_PCTLESS_HEADER="Opciones a compra teniendo %d%% de ahorro sobre el precio promedio de desencantar el art\195\173culo:";
		ENCH_FRMT_PCTLESS_LINE="%s, Valorado en: %s, OC: %s, Ahorra: %s, Menos %s";
		ENCH_FRMT_PCTLESS_DONE="Porcentajes menores finalizado.";
		ENCH_FRMT_PRINTIN="Los mensajes de Enchantrix se imprimir\195\161n en la ventana de comunicaci\195\179n \"%s\"";
		
		ENCH_TEXT_GENERAL=ENCH_TEXT_GENERAL;
		ENCH_TEXT_COMBAT=ENCH_TEXT_COMBAT;
		
		--GUI localizations
		
		ENCH_GUI_MAIN_HELP="Contiene ajustes para Enchantrix \nun aditamento que muestra informaci\195\179n en la caja de ayuda con relaci\195\179n a los resultados de desencantar el art\195\173culo.";
		ENCH_GUI_MAIN_ENABLE="Encender Enchantrix";
		ENCH_GUI_LOCALE="Ajustar localidad a";
		ENCH_GUI_RELOADUI_BUTTON="Recargar";
		ENCH_GUI_RELOADUI="Recargar Interf\195\161z";
		ENCH_GUI_RELOADUI_HELP="Presione aqui para recargar el interf\195\161z de WoW luego de haber seleccionado una localidad diferente. Esto es para que el lenguaje de configuraci\195\179n sea el mismo que el de Auctioneer.\nNota: Esta operaci\195\179n puede tomar unos minutos.";
		ENCH_GUI_RELOADUI_FEEDBACK="Recargando el Interf\195\161z de WoW";
		ENCH_GUI_EMBED="Integrar informaci\195\179n en la caja de ayuda";
		ENCH_GUI_VALUATE_HEADER="Valorizaci\195\179nes";
		ENCH_GUI_VALUATE_ENABLE="Encender Valorizaci\195\179nes";
		ENCH_GUI_VALUATE_AVERAGES="Valorizar con promedios de Auctioneer";
		ENCH_GUI_VALUATE_MEDIAN="Valorizar con medianos de Auctioneer";
		ENCH_GUI_VALUATE_BASELINE="Valorizar con valores de referencia";
		ENCH_GUI_OTHER_HEADER="Otras Opciones";
		ENCH_GUI_OTHER_HELP="Opciones miscel\195\161neas de Enchantrix";
		ENCH_GUI_CLEARALL_BUTTON="Eliminar Todo";
		ENCH_GUI_CLEARALL="Eliminar toda la informaci\195\179n";
		ENCH_GUI_CLEARALL_HELP="Seleccione aqui para eliminar toda la informaci\195\179n de Enchantrix para el reino-facci\195\179n corriente.";
		ENCH_GUI_CLEARALL_NOTE="el reino-facci\195\179n corriente.";
		ENCH_GUI_DEFAULT_ALL_BUTTON="Revertir Todo";
		ENCH_GUI_DEFAULT_ALL="Revertir todas las opciones de Enchantrix";
		ENCH_GUI_DEFAULT_ALL_HELP="Seleccione aqui para revertir todas las opciones de Auctioneer a sus configuraciones de f\195\161brica.\nADVERTENCIA: Esta acci\195\179n NO es reversible.";
		ENCH_GUI_DEFAULT_OPTION="Revertir esta opci\195\179n";
		ENCH_GUI_PRINTIN="Seleccione la ventana deseada";
		
		--ID Numbers 
		EssenceItemIDs=EssenceItemIDs; --This section has been removed from this file because, like the Disenchanting spell name, there is no Spanish WoW client.

		-- The following definitions are missing in this locale:
		--	ENCH_GUI_COUNT = "";
		--	ENCH_GUI_RATE = "";
		--	ENCH_MESG_DISABLE = "";

	end



	-- Locale strings for the frFR locale
	if locale == "frFR" then
		-- Encoded in UTF8
		-- French localization for Enchantrix
		-- Were currently looking for french translators. Apply at norganna.com/bb
		


		-- The following definitions are missing in this locale:
		--	ENCH_ARG_SPELLNAME = "";
		--	ENCH_CMD_CLEAR = "";
		--	ENCH_CMD_CLEAR_ALL = "";
		--	ENCH_CMD_DEFAULT = "";
		--	ENCH_CMD_DISABLE = "";
		--	ENCH_CMD_FIND_BIDAUCT = "";
		--	ENCH_CMD_FIND_BIDAUCT_SHORT = "";
		--	ENCH_CMD_FIND_BUYAUCT = "";
		--	ENCH_CMD_FIND_BUYAUCT_SHORT = "";
		--	ENCH_CMD_LOCALE = "";
		--	ENCH_CMD_OFF = "";
		--	ENCH_CMD_ON = "";
		--	ENCH_CMD_PRINTIN = "";
		--	ENCH_CMD_TOGGLE = "";
		--	ENCH_FRMT_ACT_CLEARALL = "";
		--	ENCH_FRMT_ACT_CLEAR_FAIL = "";
		--	ENCH_FRMT_ACT_CLEAR_OK = "";
		--	ENCH_FRMT_ACT_DEFAULT = "";
		--	ENCH_FRMT_ACT_DEFAULT_ALL = "";
		--	ENCH_FRMT_ACT_DISABLE = "";
		--	ENCH_FRMT_ACT_ENABLE = "";
		--	ENCH_FRMT_ACT_ENABLED_ON = "";
		--	ENCH_FRMT_ACT_SET = "";
		--	ENCH_FRMT_ACT_UNKNOWN = "";
		--	ENCH_FRMT_ACT_UNKNOWN_LOCALE = "";
		--	ENCH_FRMT_BIDBROKER_CURBID = "";
		--	ENCH_FRMT_BIDBROKER_DONE = "";
		--	ENCH_FRMT_BIDBROKER_HEADER = "";
		--	ENCH_FRMT_BIDBROKER_LINE = "";
		--	ENCH_FRMT_BIDBROKER_MINBID = "";
		--	ENCH_FRMT_COUNTS = "";
		--	ENCH_FRMT_CREDIT = "";
		--	ENCH_FRMT_DISINTO = "";
		--	ENCH_FRMT_FOUND = "";
		--	ENCH_FRMT_PCTLESS_DONE = "";
		--	ENCH_FRMT_PCTLESS_HEADER = "";
		--	ENCH_FRMT_PCTLESS_LINE = "";
		--	ENCH_FRMT_PRINTIN = "";
		--	ENCH_FRMT_USAGE = "";
		--	ENCH_FRMT_VALUE_AUCT_HSP = "";
		--	ENCH_FRMT_VALUE_AUCT_MED = "";
		--	ENCH_FRMT_VALUE_MARKET = "";
		--	ENCH_FRMT_WELCOME = "";
		--	ENCH_GUI_CLEARALL = "";
		--	ENCH_GUI_CLEARALL_BUTTON = "";
		--	ENCH_GUI_CLEARALL_HELP = "";
		--	ENCH_GUI_CLEARALL_NOTE = "";
		--	ENCH_GUI_COUNT = "";
		--	ENCH_GUI_DEFAULT_ALL = "";
		--	ENCH_GUI_DEFAULT_ALL_BUTTON = "";
		--	ENCH_GUI_DEFAULT_ALL_HELP = "";
		--	ENCH_GUI_DEFAULT_OPTION = "";
		--	ENCH_GUI_EMBED = "";
		--	ENCH_GUI_LOCALE = "";
		--	ENCH_GUI_MAIN_ENABLE = "";
		--	ENCH_GUI_MAIN_HELP = "";
		--	ENCH_GUI_OTHER_HEADER = "";
		--	ENCH_GUI_OTHER_HELP = "";
		--	ENCH_GUI_PRINTIN = "";
		--	ENCH_GUI_RATE = "";
		--	ENCH_GUI_RELOADUI = "";
		--	ENCH_GUI_RELOADUI_BUTTON = "";
		--	ENCH_GUI_RELOADUI_FEEDBACK = "";
		--	ENCH_GUI_RELOADUI_HELP = "";
		--	ENCH_GUI_VALUATE_AVERAGES = "";
		--	ENCH_GUI_VALUATE_BASELINE = "";
		--	ENCH_GUI_VALUATE_ENABLE = "";
		--	ENCH_GUI_VALUATE_HEADER = "";
		--	ENCH_GUI_VALUATE_MEDIAN = "";
		--	ENCH_HELP_CLEAR = "";
		--	ENCH_HELP_COUNT = "";
		--	ENCH_HELP_DEFAULT = "";
		--	ENCH_HELP_DISABLE = "";
		--	ENCH_HELP_EMBED = "";
		--	ENCH_HELP_FIND_BIDAUCT = "";
		--	ENCH_HELP_FIND_BUYAUCT = "";
		--	ENCH_HELP_GUESS_AUCTIONEER_HSP = "";
		--	ENCH_HELP_GUESS_AUCTIONEER_MEDIAN = "";
		--	ENCH_HELP_GUESS_BASELINE = "";
		--	ENCH_HELP_GUESS_NOAUCTIONEER = "";
		--	ENCH_HELP_HEADER = "";
		--	ENCH_HELP_LOCALE = "";
		--	ENCH_HELP_ONOFF = "";
		--	ENCH_HELP_PRINTIN = "";
		--	ENCH_HELP_RATE = "";
		--	ENCH_HELP_VALUE = "";
		--	ENCH_MESG_DISABLE = "";
		--	ENCH_MESG_NOTLOADED = "";
		--	ENCH_OPT_CLEAR = "";
		--	ENCH_OPT_DEFAULT = "";
		--	ENCH_OPT_FIND_BIDAUCT = "";
		--	ENCH_OPT_FIND_BUYAUCT = "";
		--	ENCH_OPT_LOCALE = "";
		--	ENCH_OPT_PRINTIN = "";
		--	ENCH_SHOW_COUNT = "";
		--	ENCH_SHOW_EMBED = "";
		--	ENCH_SHOW_GUESS_AUCTIONEER_HSP = "";
		--	ENCH_SHOW_GUESS_AUCTIONEER_MED = "";
		--	ENCH_SHOW_GUESS_BASELINE = "";
		--	ENCH_SHOW_HEADER = "";
		--	ENCH_SHOW_RATE = "";
		--	ENCH_SHOW_VALUE = "";
		--	ENCH_STAT_OFF = "";
		--	ENCH_STAT_ON = "";
		--	ENCH_TEXT_COMBAT = "";
		--	ENCH_TEXT_GENERAL = "";
		--	EssenceItemIDs = "";

	end

end

Enchantrix_SetLocaleStrings(GetLocale());

