--[[
	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.


	$Id$
	Version: <%version%>
]]






-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================






_INFORMER = {};

INFORMER_VALID_LOCALES = {["deDE"] = true, ["enUS"] = true, ["esES"] = true, ["frFR"] = true};

function Informer_SetLocaleStrings(locale)
-- Default locale strings are defined in English
	
	
	_INFORMER['AdditAlcohol'] = "Alcohol";
	_INFORMER['AdditBuff'] = "Buff";
	_INFORMER['AdditDrink'] = "Drink";
	_INFORMER['AdditFirework'] = "Firework";
	_INFORMER['AdditFood'] = "Food";
	_INFORMER['AdditGiftwrap'] = "Giftwrap";
	_INFORMER['AdditLure'] = "Lure";
	_INFORMER['AdditPoison'] = "Poison";
	_INFORMER['AdditPotion'] = "Potion";
	_INFORMER['AdditRestorative'] = "Restorative";
	_INFORMER['AdditScroll'] = "Scroll";
	
	_INFORMER['SkillAlchemy'] = "Alchemy";
	_INFORMER['SkillBlacksmithing'] = "Smithing";
	_INFORMER['SkillCooking'] = "Cooking";
	_INFORMER['SkillEnchanting'] = "Enchanting";
	_INFORMER['SkillEngineering'] = "Engineering";
	_INFORMER['SkillFirstaid'] = "First Aid";
	_INFORMER['SkillLeatherworking'] = "Leatherworking";
	_INFORMER['SkillMining'] = "Mining";
	_INFORMER['SkillTailoring'] = "Tailoring";
	_INFORMER['SkillDruid'] = "Druid spells";
	_INFORMER['SkillMage'] = "Mage spells";
	_INFORMER['SkillPaladin'] = "Paladin spells";
	_INFORMER['SkillPriest'] = "Priest spells";
	_INFORMER['SkillRogue'] = "Rogue skills";
	_INFORMER['SkillShaman'] = "Shaman spells";
	_INFORMER['SkillWarlock'] = "Warlock spells";
	
	
	_INFORMER['FrmtWelcome'] = "Auctioneer v%s loaded";
	
	
	_INFORMER['FrmtInfoMerchants'] = "Sold by %d merchants";
	_INFORMER['FrmtInfoQuest'] = "Quest item in %d quests";
	_INFORMER['FrmtInfoClassuse'] = "Class: %s used for %s";
	_INFORMER['FrmtInfoClass'] = "Class: %s";
	_INFORMER['FrmtInfoUse'] = "Used for: %s";
	_INFORMER['FrmtInfoBuy'] = "Buy from vendor";
	_INFORMER['FrmtInfoSell'] = "Sell to vendor";
	_INFORMER['FrmtInfoBuymult'] = "Buy %d (%s each)";
	_INFORMER['FrmtInfoSellmult'] = "Sell %d (%s each)";
	_INFORMER['FrmtInfoStx'] = "Stacks in lots of %d";
	
	_INFORMER['FrmtInfoBuyMulti'] = "  Buyout (%s%s ea)";
	
	_INFORMER['FrmtInfoBuyOne'] = "  Buyout%s";
	
	_INFORMER['FrmtInfoBuymedian'] = "  Buyout median";
	
	
	
	
	
	
	_INFORMER['CmdOff'] = "off";
	_INFORMER['CmdOn'] = "on";
	_INFORMER['CmdToggle'] = "toggle";
	_INFORMER['CmdDefault'] = "default";
	
	_INFORMER['CmdEmbed'] = "embed";
	
	
	
	
	
	_INFORMER['ShowStack'] = "show-stack";
	_INFORMER['ShowUsage'] = "show-usage";
	_INFORMER['ShowQuest'] = "show-quest";
	_INFORMER['ShowMerchant'] = "show-merchant";
	_INFORMER['ShowVendor'] = "show-vendor";
	_INFORMER['ShowVendorBuy'] = "show-vendor-buy";
	_INFORMER['ShowVendorSell'] = "show-vendor-sell";
	
	_INFORMER['HelpOnoff'] = "Turns the auction data display on and off";
	_INFORMER['HelpVerbose'] = "Select whether to show averages and suggestions verbosely (or off to show them on a single line)";
	_INFORMER['HelpVendor'] = "Select whether to show item's vendor pricing";
	_INFORMER['HelpVendorSell'] = "Select whether to show item's vendor sell pricing (req show-vendor=on)";
	_INFORMER['HelpVendorBuy'] = "Select whether to show item's vendor buy pricing (req show-vendor=on)";
	_INFORMER['HelpUsage'] = "Select whether to show tradeskill item's usage";
	_INFORMER['HelpStack'] = "Select whether to show the item's stackable size";
	_INFORMER['HelpEmbedBlank'] = "Select whether to show a blank line between the tooltip info and the auction info when embedded mode is on";
	_INFORMER['HelpEmbed'] = "Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
	
	_INFORMER['StatOn'] = "Displaying configured auction data";
	_INFORMER['StatOff'] = "Not displaying any auction data";
	
	_INFORMER['FrmtActEnable'] = "Displaying item's %s data";
	_INFORMER['FrmtActDisable'] = "Not displaying item's %s data";
	_INFORMER['FrmtActEnabledOn'] = "Displaying item's %s on %s";
	_INFORMER['FrmtActSet'] = "Set %s to '%s'";
	_INFORMER['FrmtActUnknown'] = "Unknown command keyword: '%s'";
	_INFORMER['FrmtActDefaultall'] = "All Auctioneer options have been reset to default settings.";
	_INFORMER['FrmtActDefault'] = "Auctioneer's %s option has been reset to its default setting";
	
	
	
	
	
	
	
	
	

-- Locale strings for the deDE locale
if locale == "deDE" then
		-- Encoded in UTF8
		
		_INFORMER['AdditAlcohol']     = "Alkohol";
		_INFORMER['AdditBuff']        = "Buff";
		_INFORMER['AdditDrink']       = "Getr\195\164nk";
		_INFORMER['AdditFirework']    = "Feuerwerk";
		_INFORMER['AdditFood']        = "Nahrung";
		_INFORMER['AdditGiftwrap']    = "Geschenkpapier";
		_INFORMER['AdditLure']        = "K\195\182der";
		_INFORMER['AdditPoison']      = "Gift";
		_INFORMER['AdditPotion']      = "Trank";
		_INFORMER['AdditRestorative'] = "St\195\164rkungstrank";
		_INFORMER['AdditScroll']      = "Zauberspruchrolle";
		
		_INFORMER['SkillAlchemy']        = "Alchimie";
		_INFORMER['SkillBlacksmithing']  = "Schmieden";
		_INFORMER['SkillCooking']        = "Kochen";
		_INFORMER['SkillEnchanting']     = "Verzauberungen";
		_INFORMER['SkillEngineering']    = "Ingenieurskunst";
		_INFORMER['SkillFirstaid']       = "Erste Hilfe";
		_INFORMER['SkillLeatherworking'] = "Lederverarbeitung";
		_INFORMER['SkillMining']         = "Bergbau";
		_INFORMER['SkillTailoring']      = "Schneiderei";
		_INFORMER['SkillDruid']          = "Druidenzauber";
		_INFORMER['SkillMage']           = "Magierzauber";
		_INFORMER['SkillPaladin']        = "Paladinzauber";
		_INFORMER['SkillPriest']         = "Priesterzauber";
		_INFORMER['SkillRogue']          = "Diebeszubeh\195\182r";
		_INFORMER['SkillShaman']         = "Schamanenzauber";
		_INFORMER['SkillWarlock']        = "Hexerzauber";
		
		_INFORMER['FrmtWelcome'] = "Informer v%s geladen";
		
		_INFORMER['FrmtInfoClass']    = "Klasse: %s";
		_INFORMER['FrmtInfoUse']      = "Benutzt f\195\188r: %s";
		_INFORMER['FrmtInfoBuy']      = "Einkauf beim H\195\164ndler";
		_INFORMER['FrmtInfoSell']     = "Verkauf beim H\195\164ndler";
		_INFORMER['FrmtInfoBuymult']  = "Einkauf f\195\188r %d (%s pro St\195\188ck)";
		_INFORMER['FrmtInfoSellmult'] = "Verkauf f\195\188r %d (%s pro St\195\188ck)";
		_INFORMER['FrmtInfoStx']      = "%d pro Stapel";
		
		_INFORMER['CmdOff']           = "off";
		_INFORMER['CmdOn']            = "on";
		_INFORMER['CmdToggle']        = "toggle";
		_INFORMER['CmdDefault']       = "default";
		
		_INFORMER['CmdEmbed']            = "embed";
		
		_INFORMER['ShowStack']      = "show-stack";
		_INFORMER['ShowUsage']      = "show-usage";
		_INFORMER['ShowVendor']     = "show-vendor";
		_INFORMER['ShowVendorBuy']  = "show-vendor-buy";
		_INFORMER['ShowVendorSell'] = "show-vendor-sell";
		
		_INFORMER['HelpOnoff']          = "Schaltet die Anzeige der Auktionsdaten ein/aus.";
		_INFORMER['HelpVerbose']        = "Schaltet die detaillierte Anzeige der Durchschnittswerte und Preisempfehlungen ein/aus. Deaktivieren reduziert die Datenanzeige auf eine Zeile.";
		_INFORMER['HelpVendor']         = "Schaltet die Anzeige des H\195\164ndlerpreieses ein/aus.";
		_INFORMER['HelpVendorSell']     = "Schaltet die Anzeige des H\195\164ndlerverkaufspreises ein/aus (show-vendor muss eingeschaltet sein).";
		_INFORMER['HelpVendorBuy']      = "Schaltet die Anzeige des H\195\164ndlerkaufspreises ein/aus (show-vendor muss eingeschaltet sein).";
		_INFORMER['HelpUsage']          = "Schaltet die Anzeige des Verwendungszweckes f\195\188r Handwerker ein/aus.";
		_INFORMER['HelpStack']          = "Schaltet die Anzeige der Stapelgr\195\182\195\159e ein/aus.";
		_INFORMER['HelpEmbed']          = "Bindet den Auktionsinfotext in den WoW-Tooltip ein (Hinweis: Einige Funktionen sind in diesem Modus deaktiviert).";
		
		_INFORMER['StatOn']  = "Auktionsdaten werden angezeigt.";
		_INFORMER['StatOff'] = "Auktionsdaten werden nicht angezeigt.";
		
		_INFORMER['FrmtActEnable']     = "%s wird angezeigt";
		_INFORMER['FrmtActDisable']    = "%s wird nicht angezeigt";
		_INFORMER['FrmtActEnabledOn']  = "Zeige %s auf %s";
		_INFORMER['FrmtActSet']        = "Setze %s auf '%s'";
		_INFORMER['FrmtActUnknown']    = "Unbekannter Befehl: '%s'";
		_INFORMER['FrmtActDefaultall'] = "Alle Einstellungen wurden auf Standardwerte zur\195\188ckgesetzt.";
		_INFORMER['FrmtActDefault']    = "%s wurde auf den Standardwert zur\195\188ckgesetzt.";
		

end

-- Locale strings for the esES locale
if locale == "esES" then
		-- Encoded in UTF8
		
		_INFORMER['AdditAlcohol'] = "Alcohol";
		_INFORMER['AdditBuff'] = "Mejora";
		_INFORMER['AdditDrink'] = "Bebida";
		_INFORMER['AdditFirework'] = "Fuegos Artificiales";
		_INFORMER['AdditFood'] = "Comida";
		_INFORMER['AdditGiftwrap'] = "Envoltura";
		_INFORMER['AdditLure'] = "Se\195\177uelo";
		_INFORMER['AdditPoison'] = "Veneno";
		_INFORMER['AdditPotion'] = "Poci\195\179n";
		_INFORMER['AdditRestorative'] = "Restaurativo";
		_INFORMER['AdditScroll'] = "Voluta";
		
		_INFORMER['SkillAlchemy'] = "Alqu\195\173mia";
		_INFORMER['SkillBlacksmithing'] = "Herrer\195\173a";
		_INFORMER['SkillCooking'] = "Cocinar";
		_INFORMER['SkillEnchanting'] = "Encantar";
		_INFORMER['SkillEngineering'] = "Ingenier\195\173a";
		_INFORMER['SkillFirstaid'] = "Primeros Auxilios";
		_INFORMER['SkillLeatherworking'] = "Peleter\195\173a";
		_INFORMER['SkillMining'] = "Miner\195\173a";
		_INFORMER['SkillTailoring'] = "Sastrer\195\173a";
		_INFORMER['SkillDruid'] = "Encantos de Druidas";
		_INFORMER['SkillMage'] = "Encantos de Magos";
		_INFORMER['SkillPaladin'] = "Encantos de Paladines";
		_INFORMER['SkillPriest'] = "Encantos de Sacerdotes";
		_INFORMER['SkillRogue'] = "Encantos de P\195\173caros";
		_INFORMER['SkillShaman'] = "Encantos de Chamanes";
		_INFORMER['SkillWarlock'] = "Encantos de Brujos";
		
		
		_INFORMER['FrmtWelcome'] = "Auctioneer versi\195\179n %s cargado";
		
		
		
		_INFORMER['FrmtInfoClassuse'] = "Clase: %s usado para %s";
		_INFORMER['FrmtInfoClass'] = "Clase: %s";
		_INFORMER['FrmtInfoUse'] = "Usado para: %s";
		_INFORMER['FrmtInfoBuy'] = "Compra del vendedor";
		_INFORMER['FrmtInfoSell'] = "Vende al vendedor";
		_INFORMER['FrmtInfoBuymult'] = "Compra %d (%s c/u)";
		_INFORMER['FrmtInfoSellmult'] = "Vende %d (%s c/u)";
		_INFORMER['FrmtInfoStx'] = "Amontonable en lotes de art\195\173culos %d por paquete";
		
		_INFORMER['FrmtInfoBuyMulti'] = "  Opci\195\179n a compra(%s%s c/u)";
		
		_INFORMER['FrmtInfoBuyOne'] = " %s con opci\195\179n a compra";
		
		_INFORMER['FrmtInfoBuymedian'] = "  Opci\195\179n a compra mediano";
		
		
		
		
		
		
		_INFORMER['CmdOff'] = "apagado";
		_INFORMER['CmdOn'] = "prendido";
		_INFORMER['CmdToggle'] = "invertir";
		_INFORMER['CmdDefault'] = "original";
		
		_INFORMER['CmdEmbed'] = "integrado";
		
		
		
		
		
		_INFORMER['ShowStack'] = "ver-paquete";
		_INFORMER['ShowUsage'] = "ver-uso";
		_INFORMER['ShowVendor'] = "ver-vendedor";
		_INFORMER['ShowVendorBuy'] = "ver-vendedor-compra";
		_INFORMER['ShowVendorSell'] = "ver-vendedor-venta";
		
		_INFORMER['HelpOnoff'] = "Enciande o apaga la informacion sobre las subastas";
		_INFORMER['HelpVerbose'] = "Selecciona para mostrar promedios literales (O apaga para que aparezcan en una sola linea)";
		_INFORMER['HelpVendor'] = "Selecciona para mostrar precios de vendedor para el art\195\173culo";
		_INFORMER['HelpVendorSell'] = "Selecciona para mostrar precio de venta del vendedor (requiere ver-vendedor prendido)";
		_INFORMER['HelpVendorBuy'] = "Selecciona para mostrar precio de compra del vendedor (requiere ver-vendedor prendido)";
		_INFORMER['HelpUsage'] = "Selecciona para mostrar uso del art\195\173culo en profesiones";
		_INFORMER['HelpStack'] = "Selecciona para mostrar tama\195\177o maximo del paquete";
		_INFORMER['HelpEmbedBlank'] = "Selecciona para mostrar una linea en blanco entre informacion de la caja de ayuda y la informacion de subasta cuando el modo integrado esta seleccionado";
		_INFORMER['HelpEmbed'] = "Insertar el texto en la caja de ayuda original del juego (nota: Algunas funciones se desabilitan cuando esta opci\195\179n es seleccionada)";
		
		_INFORMER['StatOn'] = "Mostrando la configuracion corriente para la informacion de subastas";
		_INFORMER['StatOff'] = "Ocultando toda la informacion de subastas";
		
		_INFORMER['FrmtActEnable'] = "Mostrando informacion del art\195\173culo: %s ";
		_INFORMER['FrmtActDisable'] = "Ocultando informacion de articulo: %s ";
		_INFORMER['FrmtActEnabledOn'] = "Mostrando %s de los art\195\173culos usando %s";
		_INFORMER['FrmtActSet'] = "%s ajustado(a) a '%s'";
		_INFORMER['FrmtActUnknown'] = "Comando o palabra clave desconocida: '%s'";
		_INFORMER['FrmtActDefaultall'] = "Todas las opciones de Auctioneer han sido revertidas a sus configuraciones de f\195\161brica.";
		_INFORMER['FrmtActDefault'] = "La opci\195\179n %s de Auctioneer ha sido revertida a su configuraci\195\179n de f\195\161brica.";
		
		
		-- AH Scanning localizations
		
		
		
		
		-- GUI localizations
		

end

-- Locale strings for the frFR locale
if locale == "frFR" then
		-- Encoded in UTF8
		_INFORMER['AdditBuff']        = "Buff";
		_INFORMER['AdditDrink']       = "Boisson";
		_INFORMER['AdditFood']        = "Nourriture";
		_INFORMER['AdditPoison']      = "Poison";
		_INFORMER['AdditPotion']      = "Potion";
		
		_INFORMER['SkillAlchemy']        = "Alchimie";
		_INFORMER['SkillBlacksmithing']  = "Forgeron";
		_INFORMER['SkillCooking']        = "Cuisine";
		_INFORMER['SkillEnchanting']     = "Enchantement";
		_INFORMER['SkillEngineering']    = "Ing\195\169nieur";
		_INFORMER['SkillFirstaid']       = "Premiers Soins";
		_INFORMER['SkillLeatherworking'] = "Travail du Cuir";
		_INFORMER['SkillMining']         = "Minage";
		_INFORMER['SkillTailoring']      = "Tailleur";
		
		_INFORMER['FrmtInfoClassuse'] = "Classe: %s utilis\195\169 pour %s";
		_INFORMER['FrmtInfoClass'] = "Classe: %s";
		_INFORMER['FrmtInfoUse'] = "Utilis\195\169 pour: %s";
		_INFORMER['FrmtInfoBuy'] = "Achat%s au marchand";
		_INFORMER['FrmtInfoSell'] = "Vente%s au marchand";
		_INFORMER['FrmtInfoBuymult'] = "Achat%s %d (%s chacun)";
		_INFORMER['FrmtInfoSellmult'] = "Vente%s %d (%s chacun)";
		_INFORMER['FrmtInfoStx'] = "Pile par lots de %d";
		
		-- AH Scanning localizations
		

end

end

Informer_SetLocaleStrings(GetLocale);

