--[[
	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.


	$Id$
	Version: <%version%>
]]






-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================






_INFORMANT = {};

INFORMANT_VALID_LOCALES = {["deDE"] = true, ["enUS"] = true, ["esES"] = true, ["frFR"] = true};

function Informant_SetLocaleStrings(locale)
-- Default locale strings are defined in English
	
	
	_INFORMANT['AdditAlcohol'] = "Alcohol";
	_INFORMANT['AdditBuff'] = "Buff";
	_INFORMANT['AdditDrink'] = "Drink";
	_INFORMANT['AdditFirework'] = "Firework";
	_INFORMANT['AdditFood'] = "Food";
	_INFORMANT['AdditGiftwrap'] = "Giftwrap";
	_INFORMANT['AdditLure'] = "Lure";
	_INFORMANT['AdditPoison'] = "Poison";
	_INFORMANT['AdditPotion'] = "Potion";
	_INFORMANT['AdditRestorative'] = "Restorative";
	_INFORMANT['AdditScroll'] = "Scroll";
	
	_INFORMANT['SkillAlchemy'] = "Alchemy";
	_INFORMANT['SkillBlacksmithing'] = "Smithing";
	_INFORMANT['SkillCooking'] = "Cooking";
	_INFORMANT['SkillEnchanting'] = "Enchanting";
	_INFORMANT['SkillEngineering'] = "Engineering";
	_INFORMANT['SkillFirstaid'] = "First Aid";
	_INFORMANT['SkillLeatherworking'] = "Leatherworking";
	_INFORMANT['SkillMining'] = "Mining";
	_INFORMANT['SkillTailoring'] = "Tailoring";
	_INFORMANT['SkillDruid'] = "Druid spells";
	_INFORMANT['SkillMage'] = "Mage spells";
	_INFORMANT['SkillPaladin'] = "Paladin spells";
	_INFORMANT['SkillPriest'] = "Priest spells";
	_INFORMANT['SkillRogue'] = "Rogue skills";
	_INFORMANT['SkillShaman'] = "Shaman spells";
	_INFORMANT['SkillWarlock'] = "Warlock spells";
	
	
	_INFORMANT['FrmtWelcome'] = "Auctioneer v%s loaded";
	
	
	_INFORMANT['FrmtInfoMerchants'] = "Sold by %d merchants";
	_INFORMANT['FrmtInfoQuest'] = "Quest item in %d quests";
	_INFORMANT['FrmtInfoClassuse'] = "Class: %s used for %s";
	_INFORMANT['FrmtInfoClass'] = "Class: %s";
	_INFORMANT['FrmtInfoUse'] = "Used for: %s";
	_INFORMANT['FrmtInfoBuy'] = "Buy from vendor";
	_INFORMANT['FrmtInfoSell'] = "Sell to vendor";
	_INFORMANT['FrmtInfoBuymult'] = "Buy %d (%s each)";
	_INFORMANT['FrmtInfoSellmult'] = "Sell %d (%s each)";
	_INFORMANT['FrmtInfoStx'] = "Stacks in lots of %d";
	
	_INFORMANT['FrmtInfoBuyMulti'] = "  Buyout (%s%s ea)";
	
	_INFORMANT['FrmtInfoBuyOne'] = "  Buyout%s";
	
	_INFORMANT['FrmtInfoBuymedian'] = "  Buyout median";
	
	
	
	
	
	
	_INFORMANT['CmdOff'] = "off";
	_INFORMANT['CmdOn'] = "on";
	_INFORMANT['CmdToggle'] = "toggle";
	_INFORMANT['CmdDefault'] = "default";
	
	_INFORMANT['CmdEmbed'] = "embed";
	
	
	
	
	
	_INFORMANT['ShowStack'] = "show-stack";
	_INFORMANT['ShowUsage'] = "show-usage";
	_INFORMANT['ShowQuest'] = "show-quest";
	_INFORMANT['ShowMerchant'] = "show-merchant";
	_INFORMANT['ShowVendor'] = "show-vendor";
	_INFORMANT['ShowVendorBuy'] = "show-vendor-buy";
	_INFORMANT['ShowVendorSell'] = "show-vendor-sell";
	
	_INFORMANT['HelpOnoff'] = "Turns the auction data display on and off";
	_INFORMANT['HelpVerbose'] = "Select whether to show averages and suggestions verbosely (or off to show them on a single line)";
	_INFORMANT['HelpVendor'] = "Select whether to show item's vendor pricing";
	_INFORMANT['HelpVendorSell'] = "Select whether to show item's vendor sell pricing (req show-vendor=on)";
	_INFORMANT['HelpVendorBuy'] = "Select whether to show item's vendor buy pricing (req show-vendor=on)";
	_INFORMANT['HelpUsage'] = "Select whether to show tradeskill item's usage";
	_INFORMANT['HelpStack'] = "Select whether to show the item's stackable size";
	_INFORMANT['HelpEmbedBlank'] = "Select whether to show a blank line between the tooltip info and the auction info when embedded mode is on";
	_INFORMANT['HelpEmbed'] = "Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
	
	_INFORMANT['StatOn'] = "Displaying configured auction data";
	_INFORMANT['StatOff'] = "Not displaying any auction data";
	
	_INFORMANT['FrmtActEnable'] = "Displaying item's %s data";
	_INFORMANT['FrmtActDisable'] = "Not displaying item's %s data";
	_INFORMANT['FrmtActEnabledOn'] = "Displaying item's %s on %s";
	_INFORMANT['FrmtActSet'] = "Set %s to '%s'";
	_INFORMANT['FrmtActUnknown'] = "Unknown command keyword: '%s'";
	_INFORMANT['FrmtActDefaultall'] = "All Auctioneer options have been reset to default settings.";
	_INFORMANT['FrmtActDefault'] = "Auctioneer's %s option has been reset to its default setting";
	
	
	
	
	
	
	
	
	

-- Locale strings for the deDE locale
if locale == "deDE" then
		-- Encoded in UTF8
		
		_INFORMANT['AdditAlcohol']     = "Alkohol";
		_INFORMANT['AdditBuff']        = "Buff";
		_INFORMANT['AdditDrink']       = "Getr\195\164nk";
		_INFORMANT['AdditFirework']    = "Feuerwerk";
		_INFORMANT['AdditFood']        = "Nahrung";
		_INFORMANT['AdditGiftwrap']    = "Geschenkpapier";
		_INFORMANT['AdditLure']        = "K\195\182der";
		_INFORMANT['AdditPoison']      = "Gift";
		_INFORMANT['AdditPotion']      = "Trank";
		_INFORMANT['AdditRestorative'] = "St\195\164rkungstrank";
		_INFORMANT['AdditScroll']      = "Zauberspruchrolle";
		
		_INFORMANT['SkillAlchemy']        = "Alchimie";
		_INFORMANT['SkillBlacksmithing']  = "Schmieden";
		_INFORMANT['SkillCooking']        = "Kochen";
		_INFORMANT['SkillEnchanting']     = "Verzauberungen";
		_INFORMANT['SkillEngineering']    = "Ingenieurskunst";
		_INFORMANT['SkillFirstaid']       = "Erste Hilfe";
		_INFORMANT['SkillLeatherworking'] = "Lederverarbeitung";
		_INFORMANT['SkillMining']         = "Bergbau";
		_INFORMANT['SkillTailoring']      = "Schneiderei";
		_INFORMANT['SkillDruid']          = "Druidenzauber";
		_INFORMANT['SkillMage']           = "Magierzauber";
		_INFORMANT['SkillPaladin']        = "Paladinzauber";
		_INFORMANT['SkillPriest']         = "Priesterzauber";
		_INFORMANT['SkillRogue']          = "Diebeszubeh\195\182r";
		_INFORMANT['SkillShaman']         = "Schamanenzauber";
		_INFORMANT['SkillWarlock']        = "Hexerzauber";
		
		_INFORMANT['FrmtWelcome'] = "Informant v%s geladen";
		
		_INFORMANT['FrmtInfoClass']    = "Klasse: %s";
		_INFORMANT['FrmtInfoUse']      = "Benutzt f\195\188r: %s";
		_INFORMANT['FrmtInfoBuy']      = "Einkauf beim H\195\164ndler";
		_INFORMANT['FrmtInfoSell']     = "Verkauf beim H\195\164ndler";
		_INFORMANT['FrmtInfoBuymult']  = "Einkauf f\195\188r %d (%s pro St\195\188ck)";
		_INFORMANT['FrmtInfoSellmult'] = "Verkauf f\195\188r %d (%s pro St\195\188ck)";
		_INFORMANT['FrmtInfoStx']      = "%d pro Stapel";
		
		_INFORMANT['CmdOff']           = "off";
		_INFORMANT['CmdOn']            = "on";
		_INFORMANT['CmdToggle']        = "toggle";
		_INFORMANT['CmdDefault']       = "default";
		
		_INFORMANT['CmdEmbed']            = "embed";
		
		_INFORMANT['ShowStack']      = "show-stack";
		_INFORMANT['ShowUsage']      = "show-usage";
		_INFORMANT['ShowVendor']     = "show-vendor";
		_INFORMANT['ShowVendorBuy']  = "show-vendor-buy";
		_INFORMANT['ShowVendorSell'] = "show-vendor-sell";
		
		_INFORMANT['HelpOnoff']          = "Schaltet die Anzeige der Auktionsdaten ein/aus.";
		_INFORMANT['HelpVerbose']        = "Schaltet die detaillierte Anzeige der Durchschnittswerte und Preisempfehlungen ein/aus. Deaktivieren reduziert die Datenanzeige auf eine Zeile.";
		_INFORMANT['HelpVendor']         = "Schaltet die Anzeige des H\195\164ndlerpreieses ein/aus.";
		_INFORMANT['HelpVendorSell']     = "Schaltet die Anzeige des H\195\164ndlerverkaufspreises ein/aus (show-vendor muss eingeschaltet sein).";
		_INFORMANT['HelpVendorBuy']      = "Schaltet die Anzeige des H\195\164ndlerkaufspreises ein/aus (show-vendor muss eingeschaltet sein).";
		_INFORMANT['HelpUsage']          = "Schaltet die Anzeige des Verwendungszweckes f\195\188r Handwerker ein/aus.";
		_INFORMANT['HelpStack']          = "Schaltet die Anzeige der Stapelgr\195\182\195\159e ein/aus.";
		_INFORMANT['HelpEmbed']          = "Bindet den Auktionsinfotext in den WoW-Tooltip ein (Hinweis: Einige Funktionen sind in diesem Modus deaktiviert).";
		
		_INFORMANT['StatOn']  = "Auktionsdaten werden angezeigt.";
		_INFORMANT['StatOff'] = "Auktionsdaten werden nicht angezeigt.";
		
		_INFORMANT['FrmtActEnable']     = "%s wird angezeigt";
		_INFORMANT['FrmtActDisable']    = "%s wird nicht angezeigt";
		_INFORMANT['FrmtActEnabledOn']  = "Zeige %s auf %s";
		_INFORMANT['FrmtActSet']        = "Setze %s auf '%s'";
		_INFORMANT['FrmtActUnknown']    = "Unbekannter Befehl: '%s'";
		_INFORMANT['FrmtActDefaultall'] = "Alle Einstellungen wurden auf Standardwerte zur\195\188ckgesetzt.";
		_INFORMANT['FrmtActDefault']    = "%s wurde auf den Standardwert zur\195\188ckgesetzt.";
		

end

-- Locale strings for the esES locale
if locale == "esES" then
		-- Encoded in UTF8
		
		_INFORMANT['AdditAlcohol'] = "Alcohol";
		_INFORMANT['AdditBuff'] = "Mejora";
		_INFORMANT['AdditDrink'] = "Bebida";
		_INFORMANT['AdditFirework'] = "Fuegos Artificiales";
		_INFORMANT['AdditFood'] = "Comida";
		_INFORMANT['AdditGiftwrap'] = "Envoltura";
		_INFORMANT['AdditLure'] = "Se\195\177uelo";
		_INFORMANT['AdditPoison'] = "Veneno";
		_INFORMANT['AdditPotion'] = "Poci\195\179n";
		_INFORMANT['AdditRestorative'] = "Restaurativo";
		_INFORMANT['AdditScroll'] = "Voluta";
		
		_INFORMANT['SkillAlchemy'] = "Alqu\195\173mia";
		_INFORMANT['SkillBlacksmithing'] = "Herrer\195\173a";
		_INFORMANT['SkillCooking'] = "Cocinar";
		_INFORMANT['SkillEnchanting'] = "Encantar";
		_INFORMANT['SkillEngineering'] = "Ingenier\195\173a";
		_INFORMANT['SkillFirstaid'] = "Primeros Auxilios";
		_INFORMANT['SkillLeatherworking'] = "Peleter\195\173a";
		_INFORMANT['SkillMining'] = "Miner\195\173a";
		_INFORMANT['SkillTailoring'] = "Sastrer\195\173a";
		_INFORMANT['SkillDruid'] = "Encantos de Druidas";
		_INFORMANT['SkillMage'] = "Encantos de Magos";
		_INFORMANT['SkillPaladin'] = "Encantos de Paladines";
		_INFORMANT['SkillPriest'] = "Encantos de Sacerdotes";
		_INFORMANT['SkillRogue'] = "Encantos de P\195\173caros";
		_INFORMANT['SkillShaman'] = "Encantos de Chamanes";
		_INFORMANT['SkillWarlock'] = "Encantos de Brujos";
		
		
		_INFORMANT['FrmtWelcome'] = "Auctioneer versi\195\179n %s cargado";
		
		
		
		_INFORMANT['FrmtInfoClassuse'] = "Clase: %s usado para %s";
		_INFORMANT['FrmtInfoClass'] = "Clase: %s";
		_INFORMANT['FrmtInfoUse'] = "Usado para: %s";
		_INFORMANT['FrmtInfoBuy'] = "Compra del vendedor";
		_INFORMANT['FrmtInfoSell'] = "Vende al vendedor";
		_INFORMANT['FrmtInfoBuymult'] = "Compra %d (%s c/u)";
		_INFORMANT['FrmtInfoSellmult'] = "Vende %d (%s c/u)";
		_INFORMANT['FrmtInfoStx'] = "Amontonable en lotes de art\195\173culos %d por paquete";
		
		_INFORMANT['FrmtInfoBuyMulti'] = "  Opci\195\179n a compra(%s%s c/u)";
		
		_INFORMANT['FrmtInfoBuyOne'] = " %s con opci\195\179n a compra";
		
		_INFORMANT['FrmtInfoBuymedian'] = "  Opci\195\179n a compra mediano";
		
		
		
		
		
		
		_INFORMANT['CmdOff'] = "apagado";
		_INFORMANT['CmdOn'] = "prendido";
		_INFORMANT['CmdToggle'] = "invertir";
		_INFORMANT['CmdDefault'] = "original";
		
		_INFORMANT['CmdEmbed'] = "integrado";
		
		
		
		
		
		_INFORMANT['ShowStack'] = "ver-paquete";
		_INFORMANT['ShowUsage'] = "ver-uso";
		_INFORMANT['ShowVendor'] = "ver-vendedor";
		_INFORMANT['ShowVendorBuy'] = "ver-vendedor-compra";
		_INFORMANT['ShowVendorSell'] = "ver-vendedor-venta";
		
		_INFORMANT['HelpOnoff'] = "Enciande o apaga la informacion sobre las subastas";
		_INFORMANT['HelpVerbose'] = "Selecciona para mostrar promedios literales (O apaga para que aparezcan en una sola linea)";
		_INFORMANT['HelpVendor'] = "Selecciona para mostrar precios de vendedor para el art\195\173culo";
		_INFORMANT['HelpVendorSell'] = "Selecciona para mostrar precio de venta del vendedor (requiere ver-vendedor prendido)";
		_INFORMANT['HelpVendorBuy'] = "Selecciona para mostrar precio de compra del vendedor (requiere ver-vendedor prendido)";
		_INFORMANT['HelpUsage'] = "Selecciona para mostrar uso del art\195\173culo en profesiones";
		_INFORMANT['HelpStack'] = "Selecciona para mostrar tama\195\177o maximo del paquete";
		_INFORMANT['HelpEmbedBlank'] = "Selecciona para mostrar una linea en blanco entre informacion de la caja de ayuda y la informacion de subasta cuando el modo integrado esta seleccionado";
		_INFORMANT['HelpEmbed'] = "Insertar el texto en la caja de ayuda original del juego (nota: Algunas funciones se desabilitan cuando esta opci\195\179n es seleccionada)";
		
		_INFORMANT['StatOn'] = "Mostrando la configuracion corriente para la informacion de subastas";
		_INFORMANT['StatOff'] = "Ocultando toda la informacion de subastas";
		
		_INFORMANT['FrmtActEnable'] = "Mostrando informacion del art\195\173culo: %s ";
		_INFORMANT['FrmtActDisable'] = "Ocultando informacion de articulo: %s ";
		_INFORMANT['FrmtActEnabledOn'] = "Mostrando %s de los art\195\173culos usando %s";
		_INFORMANT['FrmtActSet'] = "%s ajustado(a) a '%s'";
		_INFORMANT['FrmtActUnknown'] = "Comando o palabra clave desconocida: '%s'";
		_INFORMANT['FrmtActDefaultall'] = "Todas las opciones de Auctioneer han sido revertidas a sus configuraciones de f\195\161brica.";
		_INFORMANT['FrmtActDefault'] = "La opci\195\179n %s de Auctioneer ha sido revertida a su configuraci\195\179n de f\195\161brica.";
		
		
		-- AH Scanning localizations
		
		
		
		
		-- GUI localizations
		

end

-- Locale strings for the frFR locale
if locale == "frFR" then
		-- Encoded in UTF8
		_INFORMANT['AdditBuff']        = "Buff";
		_INFORMANT['AdditDrink']       = "Boisson";
		_INFORMANT['AdditFood']        = "Nourriture";
		_INFORMANT['AdditPoison']      = "Poison";
		_INFORMANT['AdditPotion']      = "Potion";
		
		_INFORMANT['SkillAlchemy']        = "Alchimie";
		_INFORMANT['SkillBlacksmithing']  = "Forgeron";
		_INFORMANT['SkillCooking']        = "Cuisine";
		_INFORMANT['SkillEnchanting']     = "Enchantement";
		_INFORMANT['SkillEngineering']    = "Ing\195\169nieur";
		_INFORMANT['SkillFirstaid']       = "Premiers Soins";
		_INFORMANT['SkillLeatherworking'] = "Travail du Cuir";
		_INFORMANT['SkillMining']         = "Minage";
		_INFORMANT['SkillTailoring']      = "Tailleur";
		
		_INFORMANT['FrmtInfoClassuse'] = "Classe: %s utilis\195\169 pour %s";
		_INFORMANT['FrmtInfoClass'] = "Classe: %s";
		_INFORMANT['FrmtInfoUse'] = "Utilis\195\169 pour: %s";
		_INFORMANT['FrmtInfoBuy'] = "Achat%s au marchand";
		_INFORMANT['FrmtInfoSell'] = "Vente%s au marchand";
		_INFORMANT['FrmtInfoBuymult'] = "Achat%s %d (%s chacun)";
		_INFORMANT['FrmtInfoSellmult'] = "Vente%s %d (%s chacun)";
		_INFORMANT['FrmtInfoStx'] = "Pile par lots de %d";
		
		-- AH Scanning localizations
		

end

end

Informant_SetLocaleStrings(GetLocale);

