	LangString DESC_Auctioneer ${LANG_CZECH} "Instalacni program Auctioneeru.$\n$\nTento AddOn skenuje a zaznamenava aukce ve World of Warcraft a vytvari podrobne statistiky pro jednoduche, pokrocile ale i velice komplexni vyuziti."
	LangString DESC_Auctioneer ${LANG_DANISH} "Dette vil installere Auctioneer. $\n$\nDette AddOn skanner og analysere auktionshusene i World of Warcraft og giver tips til varepriser. "
	LangString DESC_Auctioneer ${LANG_GERMAN} "Installiert Auctioneer.$\n$\nDieses Addon durch- sucht die Auktions- häuser von World of Warcraft, um die Preise für Gegenstände zu analysieren und damit Preisempfehlungen zu geben."
	LangString DESC_Auctioneer ${LANG_ENGLISH} "This will install Auctioneer.$\n$\nThis AddOn scans and analyzes the World of Warcraft Auction House and gives item price recomendations."
	LangString DESC_Auctioneer ${LANG_SPANISH} "Esto instalará Auctioneer.$\n$\nEste AddOn explora y analiza la Casa de Subastas de World of Warcraft y da recomendaciones de precios de artí­culos."
	LangString DESC_Auctioneer ${LANG_FRENCH} "Ce programme va installer Auctioneer.$\n$\nCet AddOn scanne et analyse les enchÃ¨res de l\'HÃ´tel des Ventes et donne des recommandations de prix."
	LangString DESC_Auctioneer ${LANG_ITALIAN} "Questo programma installerÃ  Auctioneer.$\n$\nQuesto AddOn scorre e analizza la Casa d\'Aste di World of Warcraft e fornisce raccomandazioni sul prezzo degli articoli."
	LangString DESC_Auctioneer ${LANG_KOREAN} "Auctioneer? ?????.$\n$\n?? ?? ?????? ???? ???? ??, ???? ?? ?? ??? ?????."
	LangString DESC_Auctioneer ${LANG_PORTUGUESE} "Isto instalará o Auctioneer.$\n$\nEste AddOn pesquisa e analiza a casa de leilÃµes do World of Warcraft e dá recomendaçÃµes de preÃ§os de itens."
	LangString DESC_Auctioneer ${LANG_TURKISH} "Bu AuctÄ±oneer i yÃ¼kleyecektir.$\n$\nBu Addon the World of Warcraft MÃ¼zayede Evini tarar, analiz eder ve parÃ§a fiyatlandÄ±rmasÄ± iÃ§in tavsiyelerede bulunur."
	LangString DESC_Auctioneer ${LANG_SIMPCHINESE} "????Auctioneer(????).$\n$\n???????????WOW?????,???????????"
	LangString DESC_Auctioneer ${LANG_TRADCHINESE} "????Auctioneer.$\n$\n??????????????????????,?????????????"
	LangString DESC_Enchantrix ${LANG_CZECH} "Instalacni program Enchantrixu.$\n$\nTento AddOn predvida na jake soucasti lze konkretni predmet disenchantnout."
	LangString DESC_Enchantrix ${LANG_DANISH} "Dette vil installere Enchantrix. $\n$\nDette AddOn forsÃ¸ger at forudsige hvilke komponenter et given item/genstand vil disenchante til."
	LangString DESC_Enchantrix ${LANG_GERMAN} "Installiert Enchantrix.$\n$\nDieses AddOn versucht zu bestimmen, welche Materialien beim entzaubern eines Gegenstands entstehen."
	LangString DESC_Enchantrix ${LANG_ENGLISH} "This will install Enchantrix.$\n$\nThis AddOn attempts to predict what components an item will disenchant into."
	LangString DESC_Enchantrix ${LANG_SPANISH} "Esto instalará Enchantrix.$\n$\nEste AddOn trata de predecir el resultado de desencantar artí­culos."
	LangString DESC_Enchantrix ${LANG_FRENCH} "Ce programme va installer Enchantrix.$\n$\nCet AddOn tente de prédire quels composants seront obtenus lors du désenchantement d\'un objet."
	LangString DESC_Enchantrix ${LANG_ITALIAN} "Questo programma installerÃ  Enchatrix.$\n$\nQuesto AddOn prova a predÃ¬re i componenti nei quali un articolo sarÃ  disincantato."
	LangString DESC_Enchantrix ${LANG_KOREAN} "Enchantrix? ?????.$\n$\n?? ??? ??? ???? ??? ??????."
	LangString DESC_Enchantrix ${LANG_PORTUGUESE} "Isto instalará o Enchantrix.$\n$\nEste AddOn tenta prediser em que componentes um item será desencantado."
	LangString DESC_Enchantrix ${LANG_TURKISH} "Bu Enchantrix i yÃ¼kleyecektir.$\n$\nBu Addon bir parÃ§anÄ±n disenchant yapÄ±lmasÄ± halinde nelere donÃ¼ÅŸeceÄŸini tahmin etmeye Ã§alÄ±ÅŸÄ±r."
	LangString DESC_Enchantrix ${LANG_SIMPCHINESE} "????Enchantrix(????).$\n$\n??????????????????????"
	LangString DESC_Enchantrix ${LANG_TRADCHINESE} "????Enchantrix?$\n$\n????????????????????????$\n"
	LangString DESC_Informant ${LANG_CZECH} "Instalacni program Informantu.$\n$\nTento AddOn poskytuje detailni informace o vlastnostech a vyuziti predmetu."
	LangString DESC_Informant ${LANG_DANISH} "Dette vil installere Informant. $\n$\nDette AddOn giver detaljerede informationer om de egenskaber og brugsmÃ¥der et item/genstand har."
	LangString DESC_Informant ${LANG_GERMAN} "Installiert Informant.$\n$\nDieses Addon zeigt detaillierte Information über Eigenschaften und Verwendungsmöglichkeiten eines Gegenstands an."
	LangString DESC_Informant ${LANG_ENGLISH} "This will install Informant.$\n$\nThis AddOn gives detailed information on the properties and uses of an item."
	LangString DESC_Informant ${LANG_SPANISH} "Esto instalará Informant.$\n$\nEste AddOn da información detallada de las propiedades y usos de los artí­culos."
	LangString DESC_Informant ${LANG_FRENCH} "Ce programme va installer Informant.$\n$\nCet AddOn donne des informations detaillées sur les propriétés et l\'utilisation d\'un objet."
	LangString DESC_Informant ${LANG_ITALIAN} "Questo programma installerÃ  Informant.$\n$\nQuesto AddOn fornisce informazioni dettagliate sulle proprietÃ  e gli usi di un oggetto."
	LangString DESC_Informant ${LANG_KOREAN} "Informant? ?????.$\n$\n???? ??? ??, ?? ??? ?????."
	LangString DESC_Informant ${LANG_PORTUGUESE} "Isto instalará o Informant.$\n$\nEste AddOn dá informaÃ§Ã£o detalhada sobre as propriedades e usos de um item."
	LangString DESC_Informant ${LANG_TURKISH} "Bu Informant i yÃ¼kleyecektir.$\n$\nBu Addon bir parÃ§anÄ±n Ã¶zellikleri hakkÄ±nda detaylÄ± bilgi ve kullanÄ±m bilgilerini verir."
	LangString DESC_Informant ${LANG_SIMPCHINESE} "????Informant(????).$\n$\n????????????????????????"
	LangString DESC_Informant ${LANG_TRADCHINESE} "????Informant?$\n$\n???????????????????"
	LangString DESC_Libraries ${LANG_CZECH} "Instalacni program Stubbyho a Enhanced Tooltips.$\n$\nTy jsou vyzadovany pro fungovani ostatnich AddOnu."
	LangString DESC_Libraries ${LANG_DANISH} "Dette vil installere Stubby og Enhanced Tooltips. $\n$\nDe er pÃ¥krÃ¦vet for at fÃ¥ de andre AddOns til at virke."
	LangString DESC_Libraries ${LANG_GERMAN} "Installiert Stubby und Enhanced Tooltips.$\n$\nDiese werden für die Funktion der anderen AddOns benötigt."
	LangString DESC_Libraries ${LANG_ENGLISH} "This will install Stubby and Enhanced Tooltips.$\n$\nThese are required for the other AddOns to work."
	LangString DESC_Libraries ${LANG_SPANISH} "Esto instalará Stubby y Enhanced Tooltips.$\n$\nEstos son necesarios para la operación de los otros AddOns."
	LangString DESC_Libraries ${LANG_FRENCH} "Ce programme va installer Stubby et Enhanced Tooltips.$\n$\nCes addOns sont nécessaires au bon fonctionnement des autres AddOns."
	LangString DESC_Libraries ${LANG_ITALIAN} "Questo programma installerÃ  Stubby ed Enhanced Tooltips.$\n$\nQuesti componenti sono necessari per il funzionamento degli altri AddOn."
	LangString DESC_Libraries ${LANG_KOREAN} "Stubby ? Enhanced Tooltip? ?????.$\n$\n?? ???? ????? ?????."
	LangString DESC_Libraries ${LANG_PORTUGUESE} "Isto instalará o Stubby e o Enhanced Tooltips.$\n$\nEstes sÃ£o precisos para os outros AddOns funcionarem."
	LangString DESC_Libraries ${LANG_TURKISH} "Bu Stubby ve Enhanced Tooltips i yÃ¼kleyecektir.$\n$\nBunlar diger AddOn larÄ±n Ã§aliÅŸmasÄ± iÃ§in gereklidir."
	LangString DESC_Libraries ${LANG_SIMPCHINESE} "????Stubby?Enhanced Tooltips.$\n$\n??????????????????"
	LangString DESC_Libraries ${LANG_TRADCHINESE} "????Stubby?Enhanced Tooltips.$\n$\n?????Addons?????,???????????"
	LangString DESC_UnInstaller ${LANG_CZECH} "Tento program umisti odinstalacni program do WoW slozky a do Windonws pridat/odebrat programy panelu."
	LangString DESC_UnInstaller ${LANG_DANISH} "Dette vil placere en Uninstaller i WoW mappen og i Windows TilfÃ¸j/Fjern Programmer kontrol panelet."
	LangString DESC_UnInstaller ${LANG_GERMAN} "Kopiert ein Deinstallationsprogramm ins WoW-Verzeichnis und erstellt einen Deinstallationseintrag in der Systemsteuerung von Windows."
	LangString DESC_UnInstaller ${LANG_ENGLISH} "This will place an Uninstaller in the WoW directory and in the Windows Add/Remove Programs control Panel"
	LangString DESC_UnInstaller ${LANG_SPANISH} "Esto pondrá un DesInstalador en el directorio de WoW y en el panel de control de Windows"
	LangString DESC_UnInstaller ${LANG_FRENCH} "Celà  placera une icône de désinstallation dans le répertoire de WoW ainsi que dans le panneau d\'Ajout/Suppression de programmes de Windows."
	LangString DESC_UnInstaller ${LANG_ITALIAN} "Questo metterÃ  un Disinstallatore nella directory di WoW e nel pannello di corntrollo di Windows."
	LangString DESC_UnInstaller ${LANG_KOREAN} "?????? WoW ??? ???? ???? ???? ??/?? ??? ?????."
	LangString DESC_UnInstaller ${LANG_PORTUGUESE} "Isto vai colocar um programa de desinstalaÃ§Ã£o na directoria do WoW e no painel de controlo do Windows em Adicionar/Remover Programas."
	LangString DESC_UnInstaller ${LANG_TURKISH} "Bu program silme secenegini Windows program kontrol paneline ekler."
	LangString DESC_UnInstaller ${LANG_SIMPCHINESE} "???WOW???windows??????????????"
	LangString DESC_UnInstaller ${LANG_TRADCHINESE} "?????????????(World of Warcraft)????,???Windows???????/???????????????"
