	LangString DESC_Auctioneer ${LANG_CZECH} "Instalacni program Auctioneeru. $\n$\nTento AddOn skenuje a zaznamenava aukce ve World of Warcraft a vytvari podrobne statistiky pro jednoduche, pokrocile ale i velice komplexni vyuziti."
	LangString DESC_Auctioneer ${LANG_DANISH} "Dette vil installere Auctioneer. Dette AddOn skanner og analysere auktionshusene i World of Warcraft og giver tips til varepriser. "
	LangString DESC_Auctioneer ${LANG_GERMAN} "Hiermit wird Auctioneer installiert. $\\nDieses Addon durch-$\\nsucht die Auktions-$\\nhäuser von World of Warcraft, um die Preise für Gegenstände zu analysieren und damit Preisempfehlungen zu geben."
	LangString DESC_Auctioneer ${LANG_ENGLISH} "This will install Auctioneer. $\n$\nThis AddOn scans and analyzes the World of Warcraft Auction House and gives item price recomendations."
	LangString DESC_Auctioneer ${LANG_SPANISH} "Esto instalará Auctioneer. $\n$\nEste AddOn explora y analiza la Casa de Subastas de World of Warcraft y da recomendaciones de precios de artí­culos."
	LangString DESC_Auctioneer ${LANG_FRENCH} "Ce programme va installer Auctioneer. $\n$\nCet AddOn scanne et analyse les enchÃ¨res de l\'HÃ´tel des Ventes et donne des recommandations de prix."
	LangString DESC_Auctioneer ${LANG_ITALIAN} "Questo programma installerÃ  Auctioneer. $\n$\nQuesto AddOn scorre e analizza la Casa d\'Aste di World of Warcraft e fornisce raccomandazioni sul prezzo degli articoli."
	LangString DESC_Auctioneer ${LANG_KOREAN} "Auctioneer를 설치합니다. $\n$\n월드 오브 워크래프트의 경매장의 아이템을 조사, 분석하여 추천 경매 가격을 알려줍니다."
	LangString DESC_Auctioneer ${LANG_PORTUGUESE} "Isto instalará o Auctioneer. $\n$\nEste AddOn pesquisa e analiza a casa de leilÃµes do World of Warcraft e dá recomendaçÃµes de preÃ§os de itens."
	LangString DESC_Auctioneer ${LANG_TURKISH} "Bu AuctÄ±oneer i yÃ¼kleyecektir. $\n$\nBu Addon the World of Warcraft MÃ¼zayede Evini tarar, analiz eder ve parÃ§a fiyatlandÄ±rmasÄ± iÃ§in tavsiyelerede bulunur."
	LangString DESC_Auctioneer ${LANG_SIMPCHINESE} "这将安装Auctioneer(拍卖助手). $\n$\n这个插件能够扫描并分析WOW拍卖行数据，并且提供物品价格建议。"
	LangString DESC_Auctioneer ${LANG_TRADCHINESE} "即將安裝Auctioneer. $\n$\n這個插件會掃描並且分析魔獸世界裡的拍賣場資訊，提供你物品的建議拍賣價格。"
	LangString DESC_Enchantrix ${LANG_CZECH} "Instalacni program Enchantrixu. $\n$\nTento AddOn predvida na jake soucasti lze konkretni predmet disenchantnout."
	LangString DESC_Enchantrix ${LANG_DANISH} "Dette vil installere Enchantrix. Dette AddOn forsÃ¸ger at forudsige hvilke komponenter et given item/genstand vil disenchante til."
	LangString DESC_Enchantrix ${LANG_GERMAN} "Hiermit wird Enchantrix installiert. $\n$\nDieses AddOn versucht zu bestimmen, welche Materialien beim entzaubern eines Gegenstands entstehen."
	LangString DESC_Enchantrix ${LANG_ENGLISH} "This will install Enchantrix. $\n$\nThis AddOn attempts to predict what components an item will disenchant into."
	LangString DESC_Enchantrix ${LANG_SPANISH} "Esto instalará Enchantrix. $\n$\nEste AddOn trata de predecir el resultado de desencantar artí­culos."
	LangString DESC_Enchantrix ${LANG_FRENCH} "Ce programme va installer Enchantrix. $\n$\nCet AddOn tente de prÃ©dire quels composants seront obtenus lors du dÃ©senchantement d\'un objet."
	LangString DESC_Enchantrix ${LANG_ITALIAN} "Questo programma installerÃ  Enchatrix. $\n$\nQuesto AddOn prova a predÃ¬re i componenti nei quali un articolo sarÃ  disincantato."
	LangString DESC_Enchantrix ${LANG_KOREAN} "Enchantrix를 설치합니다. $\n$\n마력 추출시 나오는 마법부여 재료를 예측해줍니다."
	LangString DESC_Enchantrix ${LANG_PORTUGUESE} "Isto instalará o Enchantrix. $\n$\nEste AddOn tenta prediser em que componentes um item será desencantado."
	LangString DESC_Enchantrix ${LANG_TURKISH} "Bu Enchantrix i yÃ¼kleyecektir. $\n$\nBu Addon bir parÃ§anÄ±n disenchant yapÄ±lmasÄ± halinde nelere donÃ¼ÅŸeceÄŸini tahmin etmeye Ã§alÄ±ÅŸÄ±r."
	LangString DESC_Enchantrix ${LANG_SIMPCHINESE} "这将安装Enchantrix(附魔助手). $\n$\n这个插件能够预测一个物品能够拆分出什么材料。"
	LangString DESC_Enchantrix ${LANG_TRADCHINESE} "即將安裝Enchantrix。$\n$\n這個插件會嘗試猜測一個物品可以被分解成那些材料。\r\n"
	LangString DESC_Informant ${LANG_CZECH} "Instalacni program Informantu. $\n$\nTento AddOn poskytuje detailni informace o vlastnostech a vyuziti predmetu."
	LangString DESC_Informant ${LANG_DANISH} "Dette vil installere Informant. Dette AddOn giver detaljerede informationer om de egenskaber og brugsmÃ¥der et item/genstand har."
	LangString DESC_Informant ${LANG_GERMAN} "Hiermit wird Informant installiert. $\n$\nDieses Addon zeigt detaillierte Information über Eigenschaften und Verwendungsmöglichkeiten eines Gegenstands an."
	LangString DESC_Informant ${LANG_ENGLISH} "This will install Informant. $\n$\nThis AddOn gives detailed information on the properties and uses of an item."
	LangString DESC_Informant ${LANG_SPANISH} "Esto instalará Informant. $\n$\nEste AddOn da información detallada de las propiedades y usos de los artí­culos."
	LangString DESC_Informant ${LANG_FRENCH} "Ce programme va installer Informant. $\n$\nCet AddOn donne des informations detaillÃ©es sur les propriÃ©tÃ©s et l\'utilisation d\'un objet."
	LangString DESC_Informant ${LANG_ITALIAN} "Questo programma installerÃ  Informant. $\n$\nQuesto AddOn fornisce informazioni dettagliate sulle proprietÃ  e gli usi di un oggetto."
	LangString DESC_Informant ${LANG_KOREAN} "Informant를 설치합니다. $\n$\n아이템의 자세한 속성, 사용 정보를 보여줍니다."
	LangString DESC_Informant ${LANG_PORTUGUESE} "Isto instalará o Informant. $\n$\nEste AddOn dá informaÃ§Ã£o detalhada sobre as propriedades e usos de um item."
	LangString DESC_Informant ${LANG_TURKISH} "Bu Informant i yÃ¼kleyecektir. $\n$\nBu Addon bir parÃ§anÄ±n Ã¶zellikleri hakkÄ±nda detaylÄ± bilgi ve kullanÄ±m bilgilerini verir."
	LangString DESC_Informant ${LANG_SIMPCHINESE} "这将安装Informant(物品助手). $\n$\n这个插件能够记录并提供一个物品的详细信息和用途。"
	LangString DESC_Informant ${LANG_TRADCHINESE} "即將安裝Informant。這個插件可顯示物品的詳細資訊以及用途。"
	LangString DESC_Libraries ${LANG_CZECH} "Instalacni program Stubbyho a Enhanced Tooltips. $\n$\nTy jsou vyzadovany pro fungovani ostatnich AddOnu."
	LangString DESC_Libraries ${LANG_DANISH} "Dette vil installere Stubby og Enhanced Tooltips. De er pÃ¥krÃ¦vet for at fÃ¥ de andre AddOns til at virke."
	LangString DESC_Libraries ${LANG_GERMAN} "Hiermit werden Stubby und Enhanced Tooltips installiert. $\n$\nDiese werden für die Funktion der anderen AddOns benötigt."
	LangString DESC_Libraries ${LANG_ENGLISH} "This will install Stubby and Enhanced Tooltips. $\n$\nThese are required for the other AddOns to work."
	LangString DESC_Libraries ${LANG_SPANISH} "Esto instalará Stubby y Enhanced Tooltips. $\n$\nEstos son necesarios para la operación de los otros AddOns."
	LangString DESC_Libraries ${LANG_FRENCH} "Ce programme va installer Stubby et Enhanced Tooltips. $\n$\nCes addOns sont nÃ©cessaires au bon fonctionnement des autres AddOns."
	LangString DESC_Libraries ${LANG_ITALIAN} "Questo programma installerÃ  Stubby ed Enhanced Tooltips. $\n$\nQuesti componenti sono necessari per il funzionamento degli altri AddOn."
	LangString DESC_Libraries ${LANG_KOREAN} "Stubby 와 Enhanced Tooltip을 설치합니다. $\n$\n다른 애드온이 작동하는데 필요합니다."
	LangString DESC_Libraries ${LANG_PORTUGUESE} "Isto instalará o Stubby e o Enhanced Tooltips. $\n$\nEstes sÃ£o precisos para os outros AddOns funcionarem."
	LangString DESC_Libraries ${LANG_TURKISH} "Bu Stubby ve Enhanced Tooltips i yÃ¼kleyecektir. $\n$\nBunlar diger AddOn larÄ±n Ã§aliÅŸmasÄ± iÃ§in gereklidir."
	LangString DESC_Libraries ${LANG_SIMPCHINESE} "这将安装Stubby和Enhanced Tooltips. $\n$\n其他插件依赖这两个插件才能正常工作。"
	LangString DESC_Libraries ${LANG_TRADCHINESE} "將會安裝Stubby和Enhanced Tooltips. $\n$\n這些是必須的以使其他addon正常運作"
	LangString DESC_UnInstaller ${LANG_CZECH} "Tento program umisti odinstalacni program do WoW slozky a do Windonws pridat/odebrat programy panelu."
	LangString DESC_UnInstaller ${LANG_DANISH} "Dette vil placere en Uninstaller i WoW mappen og i Windows TilfÃ¸j/Fjern Programmer kontrol panelet."
	LangString DESC_UnInstaller ${LANG_GERMAN} "Hiermit wird ein Deinstallationsprogramm im WoW Verzeichnis abgelegt und ein Deinstallationseintrag in der Systemsteuerung von Windows erstellt."
	LangString DESC_UnInstaller ${LANG_ENGLISH} "This will place an Uninstaller in the WoW directory and in the Windows Add/Remove Programs control Panel"
	LangString DESC_UnInstaller ${LANG_SPANISH} "Esto pondrá un DesInstalador en el directorio de WoW y en el panel de control de Windows"
	LangString DESC_UnInstaller ${LANG_FRENCH} "CelÃ  placera une icÃ´ne de dÃ©sinstallation dans le rÃ©pertoire de WoW ainsi que dans le panneau d\'Ajout/Suppression de programmes de Windows."
	LangString DESC_UnInstaller ${LANG_ITALIAN} "Questo metterÃ  un Disinstallatore nella directory di WoW e nel pannello di corntrollo di Windows."
	LangString DESC_UnInstaller ${LANG_KOREAN} "언인스톨러는 WoW 폴더와 윈도우즈 제어판의 프로그램 추가/삭제 메뉴에 위치합니다."
	LangString DESC_UnInstaller ${LANG_PORTUGUESE} "Isto vai colocar um programa de desinstalaÃ§Ã£o na directoria do WoW e no painel de controlo do Windows em Adicionar/Remover Programas."
	LangString DESC_UnInstaller ${LANG_TURKISH} "Bu program silme secenegini Windows program kontrol paneline ekler."
	LangString DESC_UnInstaller ${LANG_SIMPCHINESE} "这将在WOW目录和windows添加删除程序中添加卸载程序。"
	LangString DESC_UnInstaller ${LANG_TRADCHINESE} "This will place an Uninstaller in the WoW directory and in the Windows Add/Remove Programs control Panel"
