	LangString DESC_Auctioneer ${LANG_CZECH} "Instalacni program Auctioneeru.$\r$\n$\r$\nTento AddOn skenuje a zaznamenava aukce ve World of Warcraft a vytvari podrobne statistiky pro jednoduche, pokrocile ale i velice komplexni vyuziti."
	LangString DESC_Auctioneer ${LANG_DANISH} "Dette vil installere Auctioneer. $\r$\n$\r$\nDette AddOn skanner og analysere auktionshusene i World of Warcraft og giver tips til varepriser. "
	LangString DESC_Auctioneer ${LANG_GERMAN} "Installiert Auctioneer.$\r$\n$\r$\nDieses AddOn durchsucht die Auktionshäuser von World of Warcraft, um die Preise für Gegenstände zu analysieren und damit Preisempfehlungen zu geben."
	LangString DESC_Auctioneer ${LANG_ENGLISH} "This will install Auctioneer.$\r$\n$\r$\nThis AddOn scans and analyzes the World of Warcraft Auction House and gives item price recomendations."
	LangString DESC_Auctioneer ${LANG_SPANISH} "Esto instalará Auctioneer.$\r$\n$\r$\nEste AddOn explora y analiza la Casa de Subastas de World of Warcraft y da recomendaciones de precios de artí­culos."
	LangString DESC_Auctioneer ${LANG_FRENCH} "Ce programme va installer Auctioneer.$\r$\n$\r$\nCet AddOn scan et analyse les enchères de l\'Hôtel des Ventes et donne des recommandations de prix."
	LangString DESC_Auctioneer ${LANG_ITALIAN} "Questo programma installerà Auctioneer.$\r$\n$\r$\nQuesto AddOn scorre e analizza la Casa d\'Aste di World of Warcraft e fornisce raccomandazioni sul prezzo degli articoli."
	LangString DESC_Auctioneer ${LANG_KOREAN} "Auctioneer를 설치합니다.$\r$\n$\r$\n월드 오브 워크래프트의 경매장의 아이템을 조사, 분석하여 추천 경매 가격을 알려줍니다."
	LangString DESC_Auctioneer ${LANG_PORTUGUESE} "Isto instalará o Auctioneer.$\r$\n$\r$\nEste AddOn pesquisa e analiza a casa de leilÃµes do World of Warcraft e dá recomendaçÃµes de preÃ§os de itens."
	LangString DESC_Auctioneer ${LANG_RUSSIAN} "Установка Auctioneer.  Этот AddOn читает и анализирует информацию на World of Warcraft аукционах и рекомендует цены."
	LangString DESC_Auctioneer ${LANG_TURKISH} "Bu AuctÄ±oneer i yÃ¼kleyecektir.$\r$\n$\r$\nBu Addon the World of Warcraft MÃ¼zayede Evini tarar, analiz eder ve parÃ§a fiyatlandÄ±rmasÄ± iÃ§in tavsiyelerede bulunur."
	LangString DESC_Auctioneer ${LANG_SIMPCHINESE} "这将安装Auctioneer(拍卖助手).$\r$\n$\r$\n这个插件能够扫描并分析WOW拍卖行数据，并且提供物品价格建议。"
	LangString DESC_Auctioneer ${LANG_TRADCHINESE} "即將安裝Auctioneer.$\r$\n$\r$\n這個插件會掃描並且分析魔獸世界裡的拍賣場資訊，提供你物品的建議拍賣價格。"
	LangString DESC_Enchantrix ${LANG_CZECH} "Instalacni program Enchantrixu.$\r$\n$\r$\nTento AddOn predvida na jake soucasti lze konkretni predmet disenchantnout."
	LangString DESC_Enchantrix ${LANG_DANISH} "Dette vil installere Enchantrix. $\r$\n$\r$\nDette AddOn forsoeger at forudsige hvilke komponenter et given item/genstand vil disenchante til."
	LangString DESC_Enchantrix ${LANG_GERMAN} "Installiert Enchantrix.$\r$\n$\r$\nDieses AddOn versucht zu bestimmen, welche Materialien beim Entzaubern eines Gegenstands entstehen."
	LangString DESC_Enchantrix ${LANG_ENGLISH} "This will install Enchantrix.$\r$\n$\r$\nThis AddOn attempts to predict what components an item will disenchant into."
	LangString DESC_Enchantrix ${LANG_SPANISH} "Esto instalará Enchantrix.$\r$\n$\r$\nEste AddOn trata de predecir el resultado de desencantar artículos."
	LangString DESC_Enchantrix ${LANG_FRENCH} "Ce programme va installer Enchantrix.$\r$\n$\r$\nCet AddOn tente de prédire quels composants seront obtenus lors du désenchantement d\'un objet."
	LangString DESC_Enchantrix ${LANG_ITALIAN} "Questo programma installerà  Enchatrix.$\r$\n$\r$\nQuesto AddOn prova a predire i componenti nei quali un articolo sarà  disincantato."
	LangString DESC_Enchantrix ${LANG_KOREAN} "Enchantrix를 설치합니다.$\r$\n$\r$\n마력 추출시 나오는 마법부여 재료를 예측해줍니다."
	LangString DESC_Enchantrix ${LANG_PORTUGUESE} "Isto instalará o Enchantrix.$\r$\n$\r$\nEste AddOn tenta prediser em que componentes um item será desencantado."
	LangString DESC_Enchantrix ${LANG_RUSSIAN} "Установка Enchantrix.  Этот AddOn пытается предсказать, какие компоненты получатся из предмета после disenchant."
	LangString DESC_Enchantrix ${LANG_TURKISH} "Bu Enchantrix i yÃ¼kleyecektir.$\r$\n$\r$\nBu Addon bir parÃ§anÄ±n disenchant yapÄ±lmasÄ± halinde nelere donÃ¼ÅŸeceÄŸini tahmin etmeye Ã§alÄ±ÅŸÄ±r."
	LangString DESC_Enchantrix ${LANG_SIMPCHINESE} "这将安装Enchantrix(附魔助手).$\r$\n$\r$\n这个插件能够预测一个物品能够拆分出什么材料。"
	LangString DESC_Enchantrix ${LANG_TRADCHINESE} "即將安裝Enchantrix。$\r$\n$\r$\n這個插件會嘗試猜測一個物品可以被分解成那些材料。$\r$\n"
	LangString DESC_Informant ${LANG_CZECH} "Instalacni program Informantu.$\r$\n$\r$\nTento AddOn poskytuje detailni informace o vlastnostech a vyuziti predmetu."
	LangString DESC_Informant ${LANG_DANISH} "Dette vil installere Informant. $\r$\n$\r$\nDette AddOn giver detaljerede informationer om de egenskaber og brugsmaader et item/genstand har."
	LangString DESC_Informant ${LANG_GERMAN} "Installiert Informant.$\r$\n$\r$\nDieses AddOn zeigt detaillierte Informationen über Eigenschaften und Verwendungsmöglichkeiten eines Gegenstands an."
	LangString DESC_Informant ${LANG_ENGLISH} "This will install Informant.$\r$\n$\r$\nThis AddOn gives detailed information on the properties and uses of an item."
	LangString DESC_Informant ${LANG_SPANISH} "Esto instalará Informant.$\r$\n$\r$\nEste AddOn da información detallada de las propiedades y usos de los artí­culos."
	LangString DESC_Informant ${LANG_FRENCH} "Ce programme va installer Informant.$\r$\n$\r$\nCet AddOn donne des informations detaillées sur les propriétés et l\'utilisation d\'un objet."
	LangString DESC_Informant ${LANG_ITALIAN} "Questo programma installerà  Informant.$\r$\n$\r$\nQuesto AddOn fornisce informazioni dettagliate sulle proprietà  e gli usi di un oggetto."
	LangString DESC_Informant ${LANG_KOREAN} "Informant를 설치합니다.$\r$\n$\r$\n아이템의 자세한 속성, 사용 정보를 보여줍니다."
	LangString DESC_Informant ${LANG_PORTUGUESE} "Isto instalará o Informant.$\r$\n$\r$\nEste AddOn dá informaÃ§Ã£o detalhada sobre as propriedades e usos de um item."
	LangString DESC_Informant ${LANG_RUSSIAN} "Установка Informant.  Этот AddOn показывает подробную информацию про предметы и их использование."
	LangString DESC_Informant ${LANG_TURKISH} "Bu Informant i yÃ¼kleyecektir.$\r$\n$\r$\nBu Addon bir parÃ§anÄ±n Ã¶zellikleri hakkÄ±nda detaylÄ± bilgi ve kullanÄ±m bilgilerini verir."
	LangString DESC_Informant ${LANG_SIMPCHINESE} "这将安装Informant(物品助手).$\r$\n$\r$\n这个插件能够记录并提供一个物品的详细信息和用途。"
	LangString DESC_Informant ${LANG_TRADCHINESE} "即將安裝Informant。$\r$\n$\r$\n這個插件可顯示物品的詳細資訊以及用途。"
	LangString DESC_Libraries ${LANG_CZECH} "Instalacni program Stubbyho a Enhanced Tooltips.$\r$\n$\r$\nTy jsou vyzadovany pro fungovani ostatnich AddOnu."
	LangString DESC_Libraries ${LANG_DANISH} "Dette vil installere Stubby og Enhanced Tooltips. $\r$\n$\r$\nDe er paakraevet for at faa de andre AddOns til at virke."
	LangString DESC_Libraries ${LANG_GERMAN} "Installiert Stubby und Enhanced Tooltips.$\r$\n$\r$\nDiese werden für die Funktion der anderen AddOns benötigt."
	LangString DESC_Libraries ${LANG_ENGLISH} "This will install Stubby and Enhanced Tooltips.$\r$\n$\r$\nThese are required for the other AddOns to work."
	LangString DESC_Libraries ${LANG_SPANISH} "Esto instalará Stubby y Enhanced Tooltips.$\r$\n$\r$\nEstos son necesarios para la operación de los otros AddOns."
	LangString DESC_Libraries ${LANG_FRENCH} "Ce programme va installer Stubby et Enhanced Tooltips.$\r$\n$\r$\nCes AddOns sont nécessaires au bon fonctionnement des autres AddOns."
	LangString DESC_Libraries ${LANG_ITALIAN} "Questo programma installerà  Stubby ed Enhanced Tooltips.$\r$\n$\r$\nQuesti componenti sono necessari per il funzionamento degli altri AddOn."
	LangString DESC_Libraries ${LANG_KOREAN} "Stubby 와 Enhanced Tooltip을 설치합니다.$\r$\n$\r$\n다른 애드온이 작동하는데 필요합니다."
	LangString DESC_Libraries ${LANG_PORTUGUESE} "Isto instalará o Stubby e o Enhanced Tooltips.$\r$\n$\r$\nEstes sÃ£o precisos para os outros AddOns funcionarem."
	LangString DESC_Libraries ${LANG_RUSSIAN} "Установка Stubby и Enhanced Tooltips.  Эти компоненты требуются для работы остальных AddOns пакета."
	LangString DESC_Libraries ${LANG_TURKISH} "Bu Stubby ve Enhanced Tooltips i yÃ¼kleyecektir.$\r$\n$\r$\nBunlar diger AddOn larÄ±n Ã§aliÅŸmasÄ± iÃ§in gereklidir."
	LangString DESC_Libraries ${LANG_SIMPCHINESE} "这将安装Stubby和Enhanced Tooltips.$\r$\n$\r$\n其他插件依赖这两个插件才能正常工作。"
	LangString DESC_Libraries ${LANG_TRADCHINESE} "將會安裝Stubby和Enhanced Tooltips.$\r$\n$\r$\n若要使其他Addons的功能正常，必須使用到這兩個插件。"
	LangString DESC_UnInstaller ${LANG_CZECH} "Tento program umisti odinstalacni program do WoW slozky a do Windonws pridat/odebrat programy panelu."
	LangString DESC_UnInstaller ${LANG_DANISH} "Dette vil placere en Uninstaller i WoW mappen og i Windows Tilfoej/Fjern Programmer kontrol panelet."
	LangString DESC_UnInstaller ${LANG_GERMAN} "Kopiert ein Deinstallationsprogramm ins WoW-Verzeichnis und erstellt einen Deinstallationseintrag in der Systemsteuerung von Windows."
	LangString DESC_UnInstaller ${LANG_ENGLISH} "This will place an Uninstaller in the WoW directory and in the Windows Add/Remove Programs control Panel"
	LangString DESC_UnInstaller ${LANG_SPANISH} "Esto pondrá un DesInstalador en el directorio de WoW y en el panel de control de Windows"
	LangString DESC_UnInstaller ${LANG_FRENCH} "Cela  placera une icône de désinstallation dans le répertoire de WoW ainsi que dans le panneau d\'Ajout/Suppression de programmes de Windows."
	LangString DESC_UnInstaller ${LANG_ITALIAN} "Questo metterà un Disinstallatore nella directory di WoW e nel pannello di corntrollo di Windows."
	LangString DESC_UnInstaller ${LANG_KOREAN} "언인스톨러는 WoW 폴더와 윈도우즈 제어판의 프로그램 추가/삭제 메뉴에 위치합니다."
	LangString DESC_UnInstaller ${LANG_PORTUGUESE} "Isto vai colocar um programa de desinstalaÃ§Ã£o na directoria do WoW e no painel de controlo do Windows em Adicionar/Remover Programas."
	LangString DESC_UnInstaller ${LANG_RUSSIAN} "Установка Uninstaller в папку WoW и в Windows Add/Remove Programs control panel."
	LangString DESC_UnInstaller ${LANG_TURKISH} "Bu program silme secenegini Windows program kontrol paneline ekler."
	LangString DESC_UnInstaller ${LANG_SIMPCHINESE} "这将在WOW目录和windows添加删除程序中添加卸载程序。"
	LangString DESC_UnInstaller ${LANG_TRADCHINESE} "將移除程式放在你的魔獸世界(World of Warcraft)資料夾裡，同時在Windows控制台裡的新增/移除程式清單裡列出此移除程式。"
